### ISSUE TITLE
Broken account that does not update

### ISSUE THREAD

**Issue by delwyn** [jedi-gg/swgoh.gg.public#109]
There is an account in our guild that never updates. They have been removed from the guild for a while now but as their account does not update, they seem to be displayed in the guild "forever". 

Is there any way to remove them?

Guild: [https://swgoh.gg/g/3244/judgement-uk/](https://swgoh.gg/g/3244/judgement-uk/)
User: [https://swgoh.gg/u/kieran1/](https://swgoh.gg/u/kieran1/)

**Comment by delwyn** [comment]
Any update on this?

**Comment by zbarresse** [comment]
We're having the exact same issue with a member. The member started a new account and changed guilds, but their old one is left on our guild roster still. Shows the last stats, but oddly enough the Arena Average value is missing.

Guild: https://swgoh.gg/g/27607/heros-of-a-fallen-empire/
User: https://swgoh.gg/u/invictus/

Not trying to crowd @delwyn, just got the same issue, no need for another ticket.
