### ISSUE TITLE
Squad builder issue

### ISSUE THREAD

**Issue by Mishawnuodo** [jedi-gg/swgoh.gg.public#117]
https://swgoh.gg/u/mishawnuodo/squads/

Love the site, wonderfully useful!!!

That said, squad builder needs a little improvement... Some units can be found easily, others not so much. I don't expect to be able too find units based on nicknames like CLS, but I do expect to find them by names within their full name... Example: try finding Zeb or Cody. You can't. You have to look for Garazeb and CC-2224 (I consider myself a huge star wars fan but I can't remember all the identification numbers for each clone 😉). I know it can be done (Luke brings both CLS and farm boy)

**Comment by danpaulson** [comment]
I hear ya - the filtering on that search is pretty bad. I need to refactor that for a new feature, so it'll be worked on soon.
