### ISSUE TITLE
403 forbidden when trying to sync

### ISSUE THREAD

**Issue by YwingPilot** [jedi-gg/swgoh.gg.public#146]
Hi
Trying to Sync and I'm getting a "Forbidden (403) CSRF verification failed. Request aborted" message when trying to sync for the first time. 
Ally code is 252-634-577 and used my player ID copied from the tool.

**Comment by DrValance** [comment]
I am having the same issue when trying to sync as well.  My ally code is 593-191-363 and I used my player ID as well from the tool. I would like this fixed aswell.

**Comment by brunoalr** [comment]
This seems to be happening with IOS/Safari users. Try to use another browser (say Chrome).

**Comment by YwingPilot** [comment]
Thanks but I am using chrome…

**Comment by bobbir90** [comment]
Hello 
I have the same problem my ally code is 651-485-643.
Please fix. thanks

**Comment by danpaulson** [comment]
Attempting to track this down, a solution eludes us.
