### ISSUE TITLE
Guild unit API bugs

### ISSUE THREAD

**Issue by guruzim** [jedi-gg/swgoh.gg.public#155]
I am not sure what is causing this, just wanted to report a couple of bugs in the guild unit api.

For guild 9303, user "Beardmonk 75" is duplicated in the result set.

https://swgoh.gg/api/guilds/9303/units/

![image](https://user-images.githubusercontent.com/36273537/35984846-20119c78-0caa-11e8-917a-2f335b16ff2b.png)

For guild 2519, user f1rstorder is being assigned player value "Knights of Ren"

https://swgoh.gg/api/guilds/2519/units/

![image](https://user-images.githubusercontent.com/36273537/35985020-7fd6a964-0caa-11e8-96cd-2d3e06302b1c.png)

**Comment by FingolfinTEK** [comment]
The API is also not including player collection URLs into ships, which is fine in cases where a guild doesn't have multiple members with the same name but there's lots  of guilds where that's not the case, e.g. https://swgoh.gg/api/guilds/14280/units/

Could you please include the URLs for ships as well?
