### ISSUE TITLE
Sync time suggestion / enchancement

### ISSUE THREAD

**Issue by swgity** [jedi-gg/swgoh.gg.public#164]
How about sorting the sync update list for each time zone by current arena rank so that those with a higher rank get synced before those with a lower rank?

It would mean people who no longer play (so have dropped down the ranks a lot) or don't care about arena rank so much (so are much lower ranked) get synced after those who are more active / trying to achieve a top rank.

**Comment by danpaulson** [comment]
This is such a good idea that I feel stupid for not thinking of it. Will take a look tonight and see if we can make that happen.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by swgity** [comment]
Hopefully its fairly easy to do

**Comment by ZhenyaKanaeva** [comment]
Any update on this issue ? My account always sync half hour late but my shard mate sync 6:01pm his local time...

**Comment by hurky** [comment]
Same problem how do we change the sync time?
