### ISSUE TITLE
[RE-OPEN] Stuck user in guild page.

### ISSUE THREAD

**Issue by SteveDave89** [jedi-gg/swgoh.gg.public#218]
We have a member that has never been a part of our guild stuck at the bottom of our roster. His swgoh has been out of sync for over a year. Any help in removing this would be great.
Roster: https://swgoh.gg/g/13231/gamma-g/
Member in question: https://swgoh.gg/u/clayton/

Previous Ticket: https://github.com/danpaulson/swgoh.gg.public/issues/196

**Comment by SteveDave89** [comment]
https://swgoh.gg/u/jarentol/ also stuck in guild roster after member left guild.

**Comment by danpaulson** [comment]
This is now fixed for sure. I'm investigating why there are 51 Profiles - could you identify they player that doesn't belong?
