### ISSUE TITLE
Player id not found

### ISSUE THREAD

**Issue by Krilliks** [jedi-gg/swgoh.gg.public#224]
I keep getting error message that play ID not found even though I use the player ID lookup tool please fix this
https://swgoh.gg/u/settings/

**Comment by yodaman98** [comment]
I've had this same issue for almost a month and nothing has been done yet. Ever since the last QOL update

**Comment by Krilliks** [comment]
Here is my profile  Pleeasssse fix this.
https://swgoh.gg/u/kilshot/

**Comment by Krilliks** [comment]
Here is my profile  Pleeasssse fix this.
https://swgoh.gg/u/kilshot/

**Comment by Krilliks** [comment]
@danpaulson please i have same issue and no response to my post for help, please.

Username: Kilshot
Ally code: 435-568-666
Player ID: G9DS8BtSCGJzO87yH09Qw

**Comment by Conde-Mor** [comment]
I had the same use and the problem was the numbers and letters with the same shape, like zero and o letter, or capital o letter, number one and l letter, or capital i, etc. Try it again taking this in mind.

**Comment by Krilliks** [comment]
This has been done numerous times
