### ISSUE TITLE
Placement planner for TW map

### ISSUE THREAD

**Issue by SnakeHughes** [jedi-gg/swgoh.gg.public#234]
Hi!
Territorial Wars are held several times each month. At the current moment, all use markers on the zones to indicate which squad to deploy and where. But the text of the markers is limited by the number of characters and the saved markers are not enough for all zones: (
It would be very comfortable if there could be an opportunity to do this offline on. 
As a simple vision of implementation:
-Add a section with a schematic background of the defending part of the map.(with add/del/save option)
-On the map zones make it possible to select squads from the guild squad templates.
It is necessary at least 3 layout row of squads to display on the zone.
-Display selected squads as an image of the squad members, which is a hyperlink to the template.
I think it will be very cool....

**Comment by SdtBarbarossa** [comment]
You could try my old app while waiting... it provides exact same function that xou request... there will be a PWA soon

https://drive.google.com/file/d/1aDHUoA75h4tz680cSzsUtUL3smcc_6rO/view?usp=drivesdk
