### ISSUE TITLE
Feature Request: Sort Omega/Zeta Report

### ISSUE THREAD

**Issue by kbisho12** [jedi-gg/swgoh.gg.public#255]
The Omega/Zeta report sorts the data based on the number of active instances, but it may be more useful if the user can choose to sort the data based on any column.  For instance, being able to sort based on % of character or % of G10+ character may be more useful in deciding who to zeta next.

**Comment by scoot1585** [comment]
This may be something we introduce once we have the new site updates go live.   Appreciate the suggestion!

New updates I am referencing: https://www.reddit.com/r/SWGalaxyOfHeroes/comments/8jhb3m/swgohgg_upcoming_changes/

**Comment by kbisho12** [comment]
Thank you for adding the additional filters to the zeta report.
