### ISSUE TITLE
Guild GP wrong

### ISSUE THREAD

**Issue by userrule** [jedi-gg/swgoh.gg.public#267]
Our Guild GP is wrong on SWGOH.GG, it says 105,604,359 (I understand that it is missing three players, however, their GP adds up to 8,142,210) our actual Guild GP is 126,827,416 as of this moment. The strange part is that I manually added up all the numbers for each individual on there and it came to 118,601,955 which if I add the 8.1 million from the other 3 players would come out to the proper number.

Guild link is below
https://swgoh.gg/g/590/thrawns-renegades/

**Comment by scoot1585** [comment]
So this seems to be a problem with how we have to basically use the ingame search to find guilds to update info.  Your apostrophe in your guild name is throwing off the search results, so we aren't finding your guild, when I strip the apostrophe, it finds your guild and I see:

```
GuildProfile: {
_guildGalacticPower: 127153852,
}
```

I'm going to talk through this with the other guys to see how we want to handle this.  Thanks for letting us know.

**Comment by choil34** [comment]
https://swgoh.gg/g/2929/legion-501/ Our profile has been inaccurate for about a month now. Our guild gp is only about 114M

**Comment by garrot7** [comment]
Our profile is inaccurate too. User TWIST left  the guild  one week agoand his account is still listed. User Maja has 130 character percentage, and doble amound of zetas.
https://swgoh.gg/g/19132/malevolent-marauders/

**Comment by VoidACB** [comment]
https://swgoh.gg/g/34211/australian-commandos-b/
I'm having the same issue. Our guild GP hasn't updated in months and the image above it is broken. Our guild description is missing as well. However the member list and their individual GP's are correct.
![guild gp](https://user-images.githubusercontent.com/39395328/40453036-325e72e6-5f27-11e8-8f1f-dc67e39fb03d.jpg)

**Comment by randocalrissiantheoriginal** [comment]
https://swgoh.gg/g/5946/black-suns-savages/

Our guild is experiencing the same issues, we’re close to 1 million gp but the app hasn’t updated in months.  Can you please get that looked into? Thanks mang!

**Comment by scoot1585** [comment]
So we updated the code to use a new way we found to get guild information that is much more reliable.  I'm running the guild info sync right now to use the new updated code.  The way I am currently running the command it will only sync guilds that have at least 10 swgoh.gg account profiles registered.  The full 20k guilds will sync on sunday night otherwise.

And just FYI the guild sync for the guilds with at least 10 swgoh.gg accounts is run at midnight Monday through Saturday and then a full sync is run every sunday night for all guilds.

Let me know if people are still seeing data super far off after 6 hours from now (just being safe for the sync to run as I will be going to sleep soon)

Thanks for everyone being patient, but this should be much better going forward!

PS. I am going to leave this open for a bit until I hear people saying things are looking better.

**Comment by scoot1585** [comment]
yes, just to reiterate what I said above: 

The guild sync will run at midnight Monday through Saturday for the guilds with at least 10 swgoh.gg accounts in it.

And the guild sync will run on Sunday at midnight for every guild on the site.

**Comment by userrule** [comment]
Thrawns renegade is working properly now. Thank you


Sent from my Sprint Samsung Galaxy S8+.
-------- Original message --------From: Scott Benes <notifications@github.com> Date: 6/6/18  12:33 AM  (GMT-06:00) To: "danpaulson/swgoh.gg.public" <swgoh.gg.public@noreply.github.com> Cc: userrule <shaperlst@gmail.com>, Author <author@noreply.github.com> Subject: Re: [danpaulson/swgoh.gg.public] Guild GP wrong (#267) 
yes, just to reiterate what I said above:
The guild sync will run at midnight Monday through Saturday for the guilds with at least 10 swgoh.gg accounts in it.
And the guild sync will run on Sunday at midnight for every guild on the site.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/danpaulson/swgoh.gg.public/issues/267#issuecomment-394945278","url":"https://github.com/danpaulson/swgoh.gg.public/issues/267#issuecomment-394945278","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/danpaulson/swgoh.gg.public","title":"danpaulson/swgoh.gg.public","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/danpaulson/swgoh.gg.public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@scoot1585 in #267: yes, just to reiterate what I said above: \r\n\r\nThe guild sync will run at midnight Monday through Saturday for the guilds with at least 10 swgoh.gg accounts in it.\r\n\r\nAnd the guild sync will run on Sunday at midnight for every guild on the site."}],"action":{"name":"View Issue","url":"https://github.com/danpaulson/swgoh.gg.public/issues/267#issuecomment-394945278"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [danpaulson/swgoh.gg.public] Guild GP wrong (#267)",
"sections": [
{
"text": "",
"activityTitle": "**Scott Benes**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@scoot1585",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"danpaulson/swgoh.gg.public\",\n\"issueId\": 267,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"danpaulson/swgoh.gg.public\",\n\"issueId\": 267\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/danpaulson/swgoh.gg.public/issues/267#issuecomment-394945278"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 334510860\n}"
}
],
"themeColor": "26292E"
}

**Comment by oXAllMightXo** [comment]
Thanks! It works great, now!

**Comment by randocalrissiantheoriginal** [comment]
Hey scoot, we’re right back where we started again. It eventually adds/drops players to the guilds list of members as the come and go but the information inthe top remains unchanged.  Our guild information hasn’t changed in 10 days including number of members/ number of profiles/ and guild GP.  It would appear the syncing tool isn’t syncing at all.  Thanks for the the help.

https://swgoh.gg/g/5946/black-suns-savages/
