### ISSUE TITLE
BUG - TONS of ships missing abilites or attacks on site

### ISSUE THREAD

**Issue by jayjonbeach** [jedi-gg/swgoh.gg.public#284]
missing prot up ability https://swgoh.gg/ships/jedi-consulars-starfighter/
missing attack where others assist  https://swgoh.gg/ships/geonosian-spys-starfighter/
missing attack with assist  https://swgoh.gg/ships/geonosian-soldiers-starfighter/
missing attack  https://swgoh.gg/ships/first-order-tie-fighter/
missing attack  https://swgoh.gg/ships/biggs-darklighters-x-wing/

etc many more

**Comment by scoot1585** [comment]
I think this got fixed with our remap of abilities.  Leaving this up as we need to figure out why this happens sometimes and ship abilities go away.
