### ISSUE TITLE
Form Errors Player ID not found

### ISSUE THREAD

**Issue by demon-chaser** [jedi-gg/swgoh.gg.public#288]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
https://swgoh.gg/u/settings/
Here is the screen shot, I will also include a screen shot from my device showing my PlayerID

![image](https://user-images.githubusercontent.com/22546566/41308821-3a7221c2-6e3a-11e8-82f9-cfd7e5144c80.png)

![screenshot_20180611-103451](https://user-images.githubusercontent.com/22546566/41308945-7fb50c90-6e3a-11e8-9df6-de721c04cc04.png)

**Comment by ACEMLC** [comment]
My problem seems to occur when I input a zero and it changes it to a O. I’ve used the lookup tool and it still doesn’t register
