### ISSUE TITLE
Numbers for ablilties in stat pages are sorted alphabetically

### ISSUE THREAD

**Issue by azgo** [jedi-gg/swgoh.gg.public#289]
Hey,

Just noticed alphabetical sorting order on the stat pages https://swgoh.gg/characters/stats/ where the values can contain 'None', namely:

Base stat tab: 'Max Ability' column
Abilities tab: 'Max Damage Ability', 'Base Ability' columns

I'd suggest to use 0 value as for the Abilities tab: AoE Ability and maybe display them 'None', but sure you know it better!

Brgds,
AZgo

**Comment by azgo** [comment]
Hi,
Sorry to say, but the list ordering is still wrong.
E.g. setting ordering on 'Max Ability' descending shows:
None
None
9964
9939...7282...2869
14057
13813...10198

Is this fix already deployed?

Brgds,
AZgo

**Comment by scoot1585** [comment]
ah we were just closing out old tickets after the launch of the new stuff and starting with a fresh slate. I'll update this tonight. Thanks for the confirming it was still happening

**Comment by scoot1585** [comment]
This should be fixed

**Comment by azgo** [comment]
Working fine now!
Thank you, guys!
