### ISSUE TITLE
Request the ability to sync Raid Tickets Earned from CG

### ISSUE THREAD

**Issue by misiagrj** [jedi-gg/swgoh.gg.public#297]
As I'm sure you're aware, the ability to track Raid Tickets would be a life-changing new feature (especially if it was not guild dependent). I know this feature has been requested in the past and those requests have been closed since that information is not currently available through the Sync. In some of the Q&As with CG, they mention that they do work with you guys from time to time. If you have not done so already, it would make Officers lives so much easier if you could work with CG to include Raid Tickets Earned to the sync, in the same way the site already syncs Guild Currency Earned. Ideally, it would not reset when you change guilds, but even if it did, that would be so much better than what officers currently have to do. **Thank you so much for all of your effort. You guys truly are doing amazing work.**

**Comment by misiagrj** [comment]
@danpaulson what do you think the chances of this happening might be?

**Comment by danpaulson** [comment]
Unlikely unfortunately. We've proposed it, but hopefully the latest updates by CG lessens the need for this.

**Comment by misiagrj** [comment]
Please keep trying. The "recent" updates help when looking at day to day operations, but does nothing to reduce the manual data entry required for guilds that keep track of this sort of thing.
