### ISSUE TITLE
Duplicate User on Guild Page

### ISSUE THREAD

**Issue by Trajos** [jedi-gg/swgoh.gg.public#301]
Hi,
In our guild page:
https://swgoh.gg/g/3530/advantageup/
we have VincentAT twice, even though we only have one member with this name in our guild, could just the single one be displayed?

**Comment by danpaulson** [comment]
Thanks for this report. On our to-do to fix.

**Comment by Trajos** [comment]
Thanks for your response. Another (possibly related) problem: on the above webpage, we have another member 1234, and when sorting members by name, he appears after Trav78 and before TuSin AI. If you could also look at fixing sorting by name - would be great.

**Comment by danpaulson** [comment]
This all looks to be fixed.
