### ISSUE TITLE
Ships GM in site and game is different

### ISSUE THREAD

**Issue by rayderua** [jedi-gg/swgoh.gg.public#316]
Hello!
Ships GM again is different on site and in game :(
For example my TIE Advanced x1:
Game GM: 56085
Site GM: 53048

Gm different for all ships in all players ships.

**Comment by Benjact** [comment]
And I don't know if it's related, but the sum in the profile's box
![image](https://user-images.githubusercontent.com/22514769/44354840-3035df80-a4ab-11e8-9ac0-0997ba0728a1.png)
is not the sum of each ship, neither counting those in the web, nor in the game or even in the json (in the guild json is exactly the sum of each ship), while it fits in characters

**Comment by rayderua** [comment]
Stat in the profile box - corrent, because this is stat from player game statistics.
Statistics for individual ships are incorrect[](url)

**Comment by scobenes** [comment]
This is prob no longer applicable
