### ISSUE TITLE
Mk 12 ArmatTek Holo Lens Component Info is wrong

### ISSUE THREAD

**Issue by KalSarkon** [jedi-gg/swgoh.gg.public#317]
[This page](https://swgoh.gg/db/gear/170Component/mk-12-armatek-holo-lens-component/) currently shows the incorrect gear to build this component.  It does require 2x Armatek Armor Plating.  It does require:
- 1x Mk 8 Biotech Implant Prototype
- 2x Mk 7 Chiewab Hypo Syringes.

**Comment by danpaulson** [comment]
Good catch. Not sure what's up with this because it's all based on game data. Will dig in.

**Comment by scobenes** [comment]
This is no longer applicable
