### ISSUE TITLE
Bug - Choosing Unlisted for privacy doesn't remove my character from guild lists

### ISSUE THREAD

**Issue by CorporalPikachu** [jedi-gg/swgoh.gg.public#319]
Hi Dan,

I've tried a number of ways to remove my name from my guild listing but it is still there.  I've chosen 'Unlisted', I've waited over 2-3 days for it to drop off but it is still there.  Even if I log out of my account on SWGOH.gg it still is listed.

Can you either manually remove it for me or ensure that the Unlisted button does unlist me please?

https://swgoh.gg/g/18613/tie-brides/ is the guild
and I'm 'The Fist'.

Many thanks.

Nick

**Comment by danpaulson** [comment]
Unfortunately the Unlisted or Private functionality is being deprecated. We are moving towards a system where accounts are sync'd all the time regardless of accounts created on our system - is there a specific use case to be unlisted from a guild?

**Comment by CorporalPikachu** [comment]
Hi Dan, yes we are a guild of 110M GP and we happen to have 4 trayas in the guild.  I would rather be able to plan our effective battle plan for TW without the opposition seeing that we have specifically 4 trayas in the guild.  I have 2 on the front line and it doesn't take a rocket scientist to guess where the other 2 are if they know that we have 4.  I feel that this negatively affects our TW.  Also surely from a GDPR perspective this should work and be left in?

**Comment by danpaulson** [comment]
We'll take that under consideration. Picking and choosing accounts to hide is exactly why we did away with the unlisted system - it allows people to game the resource. Having all accounts shown provides a level playing field for the tools.

GDPR protects personal information such as name and email, none of which is displayed. We display no GDPR information on the site.

**Comment by danpaulson** [comment]
The one thing GDPR would cover that we will implement is the right to be forgotten, IE not use the site or have an account. That's something we do manually currently but will have a delete account option eventually.

**Comment by CorporalPikachu** [comment]
I get what you are saying but surely this is a bit invasive you automatically listing every single users data?  I mean I haven't read the eula so I can't comment but who does the data belong to EA or us? Does that mean that by playing we automatically sign up to SWGOH.gg?  I love it but it is affecting how we play our TW which is unfair on some guilds we play that have 15/50 profiles on SWGOH.gg but we have all 50.
So yes if you automatically add every user of every guild that would change that issue for us, but I honestly would just prefer and the 49 remaining people would enjoy TW more if we had the ability to not show our entire hand before TW even dropped.
Can you imagine a poker tournament that simply showed everyones 2 cards at the start, wouldn't be as fun don't you think?

**Comment by danpaulson** [comment]
GDPR only protects personal data, not game data or meta data. The issue would have to be with CG, and we have not heard anything negative about providing game data to the playerbase. If anything, we have been encouraged to share more.

We are working towards syncing every guild's full profile, regardless of if they have an account or not. I agree this would make it much more fair, and that is the intention.

These type of tools exist for every major game (Overwatch, LoL, World of Warcraft), and are generally seen as a positive. I would contend in your Poker example, we are simply showing what cards are in the deck, not necessarily how guilds will play them. We do not reveal Squad Templates for that reason.

I'll also say that we are not the only ones with access to this information, there are plenty of Discord bots that source their own data and would be unaffected if we were to re-implement unlisted accounts. If there's a will, there's a way, and the data is there for the taking.
