### ISSUE TITLE
Platoon unit search UI suggestions

### ISSUE THREAD

**Issue by CrouchingRancor** [jedi-gg/swgoh.gg.public#32]
Hi,
Thanks for this search tool !

**Filtering**
The filtering form could be enhanced. 
Currently you need to fill the number of stars searched first, then look for a character.
If you selected a character first, you can't choose your star filters from the results, you must back to add this filter. 
Added to that, the "stars" filter is on the right or the form, that means you don't see it at first glance (at least I didn't).

My suggestion : 
- remove the stars filter from the modal window
- when showing the results of the search, make the first row a line of button, one for every star level (they may already be present and disabled until a character is searched)

Having the 7 buttons already lined up reduces the time needed to filter by stars. Only 1 click is needed to get an instant filter. 

**Unit Count**
After filtering the stars, you could display the total number of characters matching the criteria.
ex: I select the number of 5\* or better Captain Han Solo, before the results I can see "*33 players own Captain Han Solo at 5\* or better*"
Then the current list or players

**Comment by scoot1585** [comment]
Yea I like the suggestions.  This current iteration of the search tool was Dan's quick tool he through together.  I am going to be doing a prob more indepth one using React.  I just have a few other things I am working on before I start that.

So if Dan wants to fix it, he could update the existing UI, but I'll definitely keep this in mind for my rework.

**Comment by CrouchingRancor** [comment]
Glad to here React is coming :)
Dunno if you'll have a separate (maybe public ?) repo for front end with react (unless you go for isomorphism), but I could probably contribute and make small PRs (such as these suggestions).

Thanks for your answer, and keep up the good work !
