### ISSUE TITLE
Values from SWGOH.GG Don't match ingame values

### ISSUE THREAD

**Issue by dwcullop** [jedi-gg/swgoh.gg.public#321]
I'm trying to determine the armor values of characters at G12, L85, 7* who do NOT have any G12 pieces, and I can't get the numbers from your site to match what I see in game.  (Sep on Discord asked me to post this here).  I'm starting with the maxed out values and then subtracting the values from the 5 G12+ pieces.  The values for Health, Protection, Speed, Physical Damage, Special Damage, Crit Chance, Tenacity, and Potency are all working great.  The value for Armor is wrong.

Test Case is  [TFP](https://swgoh.gg/characters/tie-fighter-pilot/).  His max Armor Rating is 273.  He gets 55 Armor from the Gear, which drops him down to 218.  He gets 150 STR and 40 AGI from the gear pieces.  Subtracting 0.07 for each point of AGI and 0.14 for each point of STR, removes another 23.8 putting his armor rating at 194.2, which is 24.45%.

However,  [my G12 TFP without any gear pieces](https://swgoh.gg/u/dexatronic/collection/124/tie-fighter-pilot/) has armor of 23.33% (or an armor rating of 182.57 or so). 

In other words... SWGOH.GG says this:
```
Armor Rating = 273 - 55 - (0.07)*40 - (0.14)*150
             = 273 - 55 - 2.8 - 21
             = 273 - 78.8
             = 194.2

Armor %      = (194.2 * 100) / (600 + 194.2)
             = 19420 / 794.2
             = 24.45%
```
But the game says this:
```
Armor %      = (31.93 - 8.6)
             = 23.33%

Armor Rating = (600 * 23.33) / (100 - 23.33)
             = 13998 / 76.67
             = 182.57
```

I'm hoping it's my math that's wrong, or that I'm missing something trivial, instead of an issue with SWGOH.GG.  24.45% vs 23.33% might not seem like much, but I'm trying to make a modding tool that factors in Health+Protection+Armor into a "Tankiness" stat, so I want it to be as exact as possible.

Here is my TFP's stats from the ingame info:
![screenshot_20180710-094743](https://user-images.githubusercontent.com/11876551/42606451-838976da-8532-11e8-8721-60ef793cc605.png)

Any help you can give me with this would be very appreciated.

**Comment by scobenes** [comment]
This is most likely an old bug
