### ISSUE TITLE
Add Protection Up ability classes for toons

### ISSUE THREAD

**Issue by azgo** [jedi-gg/swgoh.gg.public#324]
Hi,
Could you add please `Leader: Protection Up` ability classes for chars like Bastila, Cassian Andor, and `Protection Up` for Grand Master Yoda, Zeb, Kanan, Ezra, Wampa, Young Han Solo, Vandor Chewbacca, Chopper, Sith Trooper, Ahsoka Tano (Fulcrum), Range Trooper, Chief Nebit.

Thanks!!

**Comment by scobenes** [comment]
These should be added thanks

**Comment by azgo** [comment]
Thanks!!
