### ISSUE TITLE
QUESTON - image bundle download?

### ISSUE THREAD

**Issue by DennisBecker** [jedi-gg/swgoh.gg.public#325]
Is it possible if you could provide all images from the game as download?

Or is it allowed to copy the images for own usage (I don't want to link images from your domain!)?

**Comment by danpaulson** [comment]
What is the use case?

**Comment by DennisBecker** [comment]
Using for private or public projects which use your API

**Comment by danpaulson** [comment]
We don't currently have a good way of providing this, and it isn't on our roadmap.
