### ISSUE TITLE
Arena rank not showing properly in guild listing

### ISSUE THREAD

**Issue by dyanetta** [jedi-gg/swgoh.gg.public#327]
Hello!

I took some time off and my arena rank tanked:
https://swgoh.gg/u/relo/
https://swgoh.gg/g/84/team-steroid/

I've somewhat recovered my rank, but it's still showing up in our guild roster as still being very low.  I probably did some putzing around earlier, like making my profile not public or searchable, but I cant remember exactly what I did...

**Comment by Vaexqua** [comment]
I have the same issue, but I have been consistently active and haven't changed any settings! I had the same issue on my profile for a while, but that eventually resolved itself...
https://swgoh.gg/g/6906/annointed-rebels/
https://swgoh.gg/u/vaexqua/

**Comment by Backspace65** [comment]
Similar issues with my account. My arena rank in my profile stayed the same for months but resolved itself. My arena rank in the guild listing is frozen and has been for months.
https://swgoh.gg/u/backspace65/
https://swgoh.gg/g/15667/fragments0ftheempire/

**Comment by NosajSiad** [comment]
Same issue here, there is a blank space where my arena rank should be.
https://swgoh.gg/u/nosajsiad/
https://swgoh.gg/g/13826/rebellion-quebecoise/

**Comment by Madox91** [comment]
Same here, doesnt update for months. Please help, empty space.

https://swgoh.gg/u/pagani/
https://swgoh.gg/g/3081/federacja-zonama-sekot/

**Comment by Eoram** [comment]
Same issue is happening for quite a long time.

[](https://swgoh.gg/u/eoram/)
[](https://swgoh.gg/g/26547/korean-forces/)

**Comment by scobenes** [comment]
This is most likely an old bug
