### ISSUE TITLE
Can you please sync my account?

### ISSUE THREAD

**Issue by gfox8** [jedi-gg/swgoh.gg.public#331]
Name: Yovack
Ally code: 297-125-718
Player ID: Lcb3ilLwTSG5dEqezwBmpw 

500: Internal Server Error
It's not my fault!
It probably is.

Thank you.

**Comment by gfox8** [comment]
Is this forum even active anymore? I would love to be able to sync my account.

**Comment by sanktanglia** [comment]
its active but we dont have much time to debug individual user issues. Have you tried creating a new account and syncing it there to see if that has any effect?

**Comment by gfox8** [comment]
No. No I have not.

**Comment by gfox8** [comment]
Ok. I created a new account. Is there anyway you can delete my old account User #
278333, name: Yovack? That said, I was able to go to the settings page but it took about six times to actually get things working. Everytime I tried to submit my info I received the following error:

Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.


Anyway, this new profile is working.
