### ISSUE TITLE
51 profiles

### ISSUE THREAD

**Issue by yohan0407** [jedi-gg/swgoh.gg.public#337]
Hello, I'm a member of Hexagone Moon (https://swgoh.gg/g/25393/hexagone-moon/) and we have 51 profiles because Dace Joy (who left on 14th July in game) is still there. Is possible to remove him for swgoh.gg ?
Thanks

**Comment by Achille-CH** [comment]
Hi guys,

We are having the same problem since a while now and haven’t been able to see it fix. Could you help us please ?


Below, our guild link and the extra profile we need to get rid of:
https://swgoh.gg/g/8643/latinoamericanos-mx/
https://swgoh.gg/u/gerakno/

Thanks for the help !
