### ISSUE TITLE
Request x2

### ISSUE THREAD

**Issue by PrimeAlphaSierra** [jedi-gg/swgoh.gg.public#340]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

https://swgoh.gg/u/alphasierra/mods/

I would like to be able to pull a .csv or something that I can manipulate in spreadsheet that contains all of my current MODs.  So that I better remove/reallocate MODs as cheap as possible.  

I would also like it if a section can be added of all available MODs that are in my inventory and not just what is already assigned to a character.  

Please and thank you,
Alpha

**Comment by danpaulson** [comment]
We don't currently have plans to add csv download, and do not have access to inventory mods.
