### ISSUE TITLE
lack of arena history on account page

### ISSUE THREAD

**Issue by drummaniac83** [jedi-gg/swgoh.gg.public#342]
No arena history for my user account. Requesting either my account to be deleted so I can recreate or fixing the lack of arena history.

https://swgoh.gg/u/drummaniac83/

Thanks,
Josh

**Comment by cyberbully420** [comment]
apparently these guys are too busy with moving their servers for the past 2-3 weeks to even answer you. pathetic.

**Comment by PixEye** [comment]
Above linked as [mine](https://swgoh.gg/p/649159626/) are missing fleet arena history for several days (last records are from the 10th or 11th of November while we are the 16th). It already happened several times.

**Comment by scobenes** [comment]
This is most likely an old bug
