### ISSUE TITLE
Arena rank refreshes at incorrect time

### ISSUE THREAD

**Issue by mfiiknee** [jedi-gg/swgoh.gg.public#344]
My arena rank refreshes on this site consistently between 8:30 and 8:45 PM CDT when it should be happening at 7 PM CDT. The site says it should refresh at 6 PM and DST is not observed. Am I missing a setting somewhere? Since the refresh is happening over an hour after my payout, my rank appears artificially low on this site. Can this be fixed to refresh between 7:30 and 7:45 PM CDT?

Here's my URL: https://swgoh.gg/u/jorus_cbaoth/
Here's my current timezone as set in the Settings page: (GMT-06:00) America/Chicago

**Comment by danpaulson** [comment]
This should be greatly improved, and we have further improvements in the pipe.
