### ISSUE TITLE
Guild Sync not accurate since at least the 20th

### ISSUE THREAD

**Issue by Sysmai** [jedi-gg/swgoh.gg.public#345]
My guild page shows it refreshed 16 hrs ago but I have a member that has been gone since the 20th still showing in the guild. Also, new members not showing up, and one still showing in their old guild for days now. Our numbers have not dropped below 40 members so it can't be the priority.
https://swgoh.gg/g/43121/revans-new-0rder/
For privacy i wont put the members info without their permission but i will attach what the current list is supposed to be. Only one member would fall within the 24hr gap if any. Orca is the only one in the gap.

**Comment by danpaulson** [comment]
Players need to be part of swgoh.gg to show up, and we'll need to know what user isn't showing. Also you've linked a screenshot of a Discord bot - we don't run that bot and have no affiliation with it, nor do we have the power to fix bugs on it.

**Comment by Sysmai** [comment]
yes...sorry it is the only way to give you a list from a non swgoh.gg database. I understand sure ill put the names. 
https://swgoh.gg/u/revansmoo/ has been gone since the 20th


https://swgoh.gg/u/Nabor11/ this member joined days ago and he posted his link last night which is when i noticed since it shows him in the wrong guild.
His in game name is The Chosen One

**Comment by Sysmai** [comment]
Thank you very much for the rapid response.
Too bad EA support isn't like that..lol.

**Comment by cyberbully420** [comment]
@danpaulson alot of accounts are not updating this past week. What is the deal dude? You got the same message about server moving up for 2+ weeks. That shit is getting old. How long does it take you to move a bunch of data? You running this site on dial up? Cmon man. Tell us what is really going on. If you can't maintain that site, might as well shut it down dude.

**Comment by sanktanglia** [comment]
@Sysmai im currently working on fixing up your issue on our new backend, I see your user in the wrong guild still but I see what is causing it now. We should have the issue fixed up for you by the time the new site launches
