### ISSUE TITLE
syncing delays by days

### ISSUE THREAD

**Issue by rmru** [jedi-gg/swgoh.gg.public#346]
Hello

First let me thank you for your website, its been a big help.

My guilds page is: https://swgoh.gg/g/29245/renegade-mercenaries/

We have several people who have not been synced in 2-5 days. Any help would be appreciated.
Less than 1 Day: 26 people,
2 Days: 9 people,
3 Days: 4 people,
4 Days: 1 person (joined guild yesterday)
5 Days: 10 people

Thanks for your time.

**Comment by Sysmai** [comment]
my post just below your is the same thing..probably be better to have multiple on the same issue

**Comment by danpaulson** [comment]
This looks to be resolved.
