### ISSUE TITLE
Arena no longer updating.

### ISSUE THREAD

**Issue by TobrisGaming** [jedi-gg/swgoh.gg.public#347]
My Arena stopped updating almost a week ago now, just discovered it this morning when one of my guild mates made me aware of it. I have tried a manual update, I have tried unsync and resync. I'm not sure what else I could try on my end.

Hoping for some info or help on a solution.

My profile is here: https://swgoh.gg/u/tobris/

**Comment by AgentRG** [comment]
Support. I noticed that mine also didn't update for a few days now.

**Comment by cyberbully420** [comment]
I have  the same problem. Account seem to have froze. The people who are running swgoh.gg dont seem to give a shit. Don't even think there is actual people running that site anyways, probably a bunch of bots from india. Sad.

**Comment by sanktanglia** [comment]
@TobrisGaming and @AgentRG ill make sure to check out your stats on the new backend we are launching in a few days. We had to move all of our infrastructure right around the time of the mods update(which also caused downtime) so theres some issues with our old code missing some people. With the new code we should be able to fix these up much easier. So just drop your ally codes/player ids in here and ill look into it as soon as we launch our new stuff in a few days

**Comment by cyberbully420** [comment]
@sanktanglia so it took you 10 days to reply to his issue but you can't even reply to mine. Instead you delete my post? What the hell dude. Have some pride

**Comment by TobrisGaming** [comment]
@sanktanglia This seems to have resolved itself with the migration finishing. Thanks for the work you all put in on the site!
