### ISSUE TITLE
Wrong sync rank and squad even after manuall sync and 10 min after  pay out time

### ISSUE THREAD

**Issue by Amit30swgoh** [jedi-gg/swgoh.gg.public#349]
![screenshot_20180825-191843_heroes](https://user-images.githubusercontent.com/42430868/44620378-dc0c7000-a89b-11e8-8348-19816a53cad9.jpg)
It shows jtr rank 7 i use traya its always symc in 19:09 and my payout time is 19:00  i sync it manually too and its not working please help 147-197-267 thanks Amit30

**Comment by Amit30swgoh** [comment]
https://swgoh.gg/u/amit30/

**Comment by cyberbully420** [comment]
the guys who run this site obviously dont give a shit. worst than cg

**Comment by danpaulson** [comment]
Looks to be resolved.
