### ISSUE TITLE
Account sync issue

### ISSUE THREAD

**Issue by Porthos72** [jedi-gg/swgoh.gg.public#351]
I have tried on multiple occasions to sync my account to swgoh.gg but every time I try it says my username doesn't exist, despite that being my username. I can send screenshots if I need, but the point is I can't connect, can you please help fix this. Thanks in advance.

**Comment by sanktanglia** [comment]
whats your ally code/player id? we are currently working on a new version of our syncing that is rolling out in a few days and ill check and see if it works there

**Comment by Porthos72** [comment]
My ally code is 448-222-638 and my username is Porthos

**Comment by sanktanglia** [comment]
I can confirm your page loads in our new backend. If you try it out once our new stuff launches in the next day or so you should be good to go, if not reply in here and ill assist

**Comment by Porthos72** [comment]
I'll try it out soon then. Thanks.

**Comment by cyberbully420** [comment]
@sanktanglia Hello, my account has problem with syncing/updating as well. It has not been updated in several days, not sure what is going on. Any help? - Ally code - 777-855-733 / Name = CYBERPUNK X134.

**Comment by Isobuster** [comment]
Have also a problem with syncing. 419-632-827. Username: Isobuster

@sanktanglia

**Comment by sanktanglia** [comment]
@Isobuster i can confirm your profile is syncing correctly on our new backend

**Comment by Isobuster** [comment]
@sanktanglia But i didn't get any data. Just updated my profile

<img width="1289" alt="bildschirmfoto 2018-09-03 um 19 35 38" src="https://user-images.githubusercontent.com/32795057/44997705-a01a8e80-afb0-11e8-9443-e876180f4be0.png">

**Comment by sanktanglia** [comment]
@Isobuster  our new backend isnt live yet, it should be in the next few days

**Comment by Isobuster** [comment]
Ah. Ok. Then i wait a little bit more. Thanks

**Comment by eolias** [comment]
Have same issue on 2 accounts 6 days without sync:
Eolias - 681268934
Phantom - 583621269
Please help. On these both accounts, I ve change guilds and it’s not possible to use the echostation bot without sync.

**Comment by yoemir** [comment]
Same problem 3-4 days could not sync my data
https://swgoh.gg/u/yoemir/
132-712-723

**Comment by Isobuster** [comment]
@sanktanglia My guild is wondering why i'm not in the memberlist. All other 49 members are in the list. 

https://swgoh.gg/g/25260/deathstargermanorder/

**Comment by sanktanglia** [comment]
@Isobuster this will be fixed with our new backend, i can confirm you show just fine on your guild page on the new site

**Comment by Isobuster** [comment]
Great. Thx. Can't wait to use your page again.

**Comment by Porthos72** [comment]
When is the new system coming out? Just wondering

**Comment by sanktanglia** [comment]
We are currently targeting this week, we were hoping to go out today but found an issue or 2 that needs fixing. Might be tomorrow, but more likely this weekend

**Comment by Porthos72** [comment]
Ok, thx

**Comment by sanktanglia** [comment]
have you tried creating a new account? the account is only needed to let you input your player id in, so a new account shouldnt affect anything

**Comment by Porthos72** [comment]
I'll give it a shot

**Comment by Porthos72** [comment]
I would have to make another email to do it, and I don't want to do that.
Is there anything else you can do?

**Comment by Porthos72** [comment]
Can u do anything about it?  It keeps saying the Id is invalid

**Comment by b0th5** [comment]
have issue with syncing as well. I used ally code to ID verification tool. It didn't help.
Still getting:
* Player ID not found. Please ensure you typed it correctly.

**Comment by sanktanglia** [comment]
whats your ally code @b0th5 ?

**Comment by b0th5** [comment]
322-588-773

**Comment by sanktanglia** [comment]
can you try again? think i fixed it

**Comment by b0th5** [comment]
@sanktanglia 
it works now, thank you!

**Comment by DarthMonawe** [comment]
Hi, whole my guild have the same issue with sync. Could you be so kind and fix that? 

My number: 632-776-971
