### ISSUE TITLE
51 profiles 

### ISSUE THREAD

**Issue by Achille-CH** [jedi-gg/swgoh.gg.public#355]
Hi guys,

We are having the same problem as others with 51 profiles on our guild details... we had the problem since a while now and haven’t been able to see it fix. Could you help us please ?

Below, our guild link and the extra profile we need to get rid of:
https://swgoh.gg/g/8643/latinoamericanos-mx/
https://swgoh.gg/u/gerakno/

Thanks for the help !

**Comment by sanktanglia** [comment]
I can confirm your guild does not have that user on our new backend, it should be ready in a few days

**Comment by Achille-CH** [comment]
Thanks for the quick response and cheers to all the team for making the
resources of swgoh.gg... so helpful 👍

Le lun. 3 sept. 2018 à 14:04, sanktanglia <notifications@github.com> a
écrit :
