### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by jdriscoll1972** [jedi-gg/swgoh.gg.public#360]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
I am having manual sync issues with both of my swgoh.gg accts and was wondering how much longer the server update was going to take. I have seen over the last week the response "a couple of days" but no movement. Is there an updated timeframe?

**Comment by sanktanglia** [comment]
nope, still within the next few days, if you can post your ally code i can confirm if your profile is syncing on the new site or not

**Comment by jdriscoll1972** [comment]
914844898

**Comment by Woweom** [comment]
Hello.
If you can also check my profile I will appreciate. 
699653648
Regards.

**Comment by jgstar** [comment]
Please kindly check my profil:
https://swgoh.gg/u/jgstar/
My account is not synced from the beggining.

**Comment by eris3d** [comment]
Hello,

Happened to know why guild is updating, but profiles don't? Is it because of the move you are making?
https://swgoh.gg/u/erised/

**Comment by eolias** [comment]
Could you please check up my account also ?
https://swgoh.gg/u/eolias/
681268934
How long to fix this issue ? It’s been 10 days I can’t sync. All bots are useless for territory battles.
Ty

**Comment by danpaulson** [comment]
These appear to have been fixed with the new update.
