### ISSUE TITLE
Guild members not updating. 

### ISSUE THREAD

**Issue by kevinontheriver** [jedi-gg/swgoh.gg.public#362]
My guild GP info has updated but non of my new guild members names or info have shown up in almost 4 days now. Please help! Thanks
https://swgoh.gg/g/18250/hansolos-other-spaceball/

**Comment by mncubbie813** [comment]
+1 We've been having the issue. Our guild removed 2 members (Crushinator & Holy Snokes) several days ago. However they are continuing to pull into our guild data.
https://swgoh.gg/g/38112/dawo-blue-squadron/

**Comment by sanktanglia** [comment]
I can confirm that both of your guilds are updating correctly on our new backend which should be out in a few days

**Comment by kevinontheriver** [comment]
Thanks for the reply

**Comment by danpaulson** [comment]
This looks to be working now. Let me know otherwise.
