### ISSUE TITLE
Unit search fails

### ISSUE THREAD

**Issue by ragscrag** [jedi-gg/swgoh.gg.public#363]
Much as I love updates, it’s a real bummer when it works not at all.
Using iPhone 6S, system 11.3.1
https://swgoh.gg/g/32937/s1th-happens-again/

2 Please read the FAQs in this repo's README before posting. Once I find it I will

**Comment by sanktanglia** [comment]
what error are you seeing? that page loads for me and im able to filter

**Comment by jfaldanam** [comment]
Unit search is not working for me either in Firefox 61.0.2 on .
It doesnt specify what kind of error it is. When loading tries to fetch data and after a couple seconds it shows this.
![image](https://user-images.githubusercontent.com/22096907/45263001-b77ad100-b421-11e8-8cee-c9a1ad08cf67.png)

**Comment by KalSarkon** [comment]
Also got a similar error when opening a squad template.  
![image](https://user-images.githubusercontent.com/33123458/45264988-f35a6a00-b412-11e8-8b47-16f21af3d302.png)

**Comment by danpaulson** [comment]
This appearsto be fixed.
