### ISSUE TITLE
Guild data sync

### ISSUE THREAD

**Issue by bakou-swgoh** [jedi-gg/swgoh.gg.public#365]
Hello there,

Despite my account appearing to be sync’ed (I can refresh it since last night) and most of my players data being synced my guild information is wrong and thus I can’t access my guild’s swgog.gg page anymore. 

Profile link: https://swgoh.gg/p/392261854/

I seem to be a member of Live Long and Shoot first (without the accents) while I’m a member of An Enterprising Starship (AES) and actually listed as a member of AES on swgog.gg guild page: https://swgoh.gg/g/11104/an-enterprising-starship/

If useful my allycode is: 392-261-854

Is there any way to fix this?

Thanks for the tremendous site !!!

**Comment by Isobuster** [comment]
Unit search is not working.

https://swgoh.gg/g/25260/deathstargermanorder/unit-search/

<img width="1239" alt="bildschirmfoto 2018-09-09 um 10 25 28" src="https://user-images.githubusercontent.com/32795057/45262634-c01bd900-b41a-11e8-8297-fabea27f18d6.png">

**Comment by danpaulson** [comment]
This appears to be fixed.

**Comment by bakou-swgoh** [comment]
I still can’t access my guild’s squad templates and all guild private content. It does say on the overview page that I’m a member of AnEnterprisingStarship but nothing in the drop-down menu despite forcing a new sync. 

Anything else I should try?

**Comment by scoot1585** [comment]
we are going to be rolling out some caching updates soon.  If you changed guilds recently, our code right now is not invalidating your old data properly so it thinks people are in previous guilds.  If this fits your situation, it will most likely fix your situation once that rolls out.
