### ISSUE TITLE
Can you add Mod ID's to the mod API?  They all show as null.

### ISSUE THREAD

**Issue by KalSarkon** [jedi-gg/swgoh.gg.public#368]
Not really an issue, but a request....

With the move to the new servers, the mods display is limited to a single page of 102 mods.  Can you bring back the ability to page through all the mods?  I realize the intent is to use filtering to limit the displayed mods to less than that cap, but that is not always possible (for example when I want to find my fastest mods regardless of type).  Actually, the ideal would be able to view all mods in a single table without the graphics (possibly CSV).  Then I could pop it into a spreadsheet and sort and filter to my heart's content.

**Comment by KalSarkon** [comment]
Found the mods API which addresses my issue.  The only thing missing is that the mod id's are not included.  The id value shows up as null.
I used these to track my unassigned mods.  Would love to see them in the API.

**Comment by scoot1585** [comment]
i just implemented that last night actually as we werent using it yet.  But one thing when I was implementing it I discovered is we weren't recording the unique ID in our new data store.  So we have some updates we are aggregating and will be doing a full sync which will then add IDs back to all mods.  

So you will get them, just have to wait til those changes rollout, and then everyone's mods resync at their payouts.  If it is just your own personal ones, a manual resync will fix it once we deploy the updated code.

**Comment by scoot1585** [comment]
you should have IDs back in the data
