### ISSUE TITLE
After move: Creating new synched account seems not to work

### ISSUE THREAD

**Issue by DonationJoruus** [jedi-gg/swgoh.gg.public#370]
Dear SWGOH.GG Team,

since you finished your move creating a new account and synch it with the account seems not to work.
after enabling synch, typing the player id and setting the timezone and clicking on update profile, puts me back into SWGOH.GG Settings Menu but never updates the collection. Still shows the Synch your collection button. Any help? https://swgoh.gg/u/254615977/ 
Thanks in advance and keep up the great work

**Comment by romanes13** [comment]
i created a new account because i couldn't log in or receive email to reset my password and now i have the above issues. https://swgoh.gg/u/romanes/

**Comment by danpaulson** [comment]
You should be able to reset your password now - let me know if you still don't get an email.

**Comment by romanes13** [comment]
still nothing

**Comment by danpaulson** [comment]
Did you fill out the form again? Tested working on our side.

**Comment by romanes13** [comment]
yes and it couldn't sync. Maybe because i created multiple profiles with the same player id?
the one account i can log in is User # 288414, https://swgoh.gg/u/romanes/

**Comment by DonationJoruus** [comment]
@danpaulson - nice closing this but you only helped the second guy who added his problem to mine - still no idea how I can fix mine from above.

**Comment by romanes13** [comment]
Now its working thanks a lot!!

**Comment by DonationJoruus** [comment]
No still not working @danpaulson sorry 
![grafik](https://user-images.githubusercontent.com/43122314/45393234-51619a00-b62b-11e8-9ef0-2edc47c16020.png)
