### ISSUE TITLE
API calls failing

### ISSUE THREAD

**Issue by mncubbie813** [jedi-gg/swgoh.gg.public#372]
I have an API call that I have been using daily to see what characters & ships my guild has:

https://swgoh.gg/api/guilds/38112/units/

It is no longer moving since the migration

**Comment by sanktanglia** [comment]
is https://swgoh.gg/api/guild/38112/ sufficient for your needs? we refactored how we stored our info so we refactored the apis as well. let me know if theres anything there missing

**Comment by mncubbie813** [comment]
I'll have to rewrite the parser a bit but it appears to have at least most things that I am looking for.

On a related note, do have a list of all the different options I can use to get the json output?

**Comment by gamycheg** [comment]
Old version of API don't work now? i'm not programmer and a write a script to parse of api 1 month. I don't have more time to create new script for new api ^(  if you have a old link give it pls

**Comment by danpaulson** [comment]
@gamycheg the old API is definitely gone forever RIP.

@mncubbie813 One magical day we'd like to flesh out the API documentation and options, but right now we're just getting our migration complete and squashing bugs.
