### ISSUE TITLE
Cannot log in and previously data had not synced for 10+ days

### ISSUE THREAD

**Issue by BBB234** [jedi-gg/swgoh.gg.public#373]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

I cannot log in and my user data has not synced in 10+ days.  My ally code is 984–283-629.  I cannot send link bc when I attempt to reset my password no email arrives....even in my spam folder.

**Comment by danpaulson** [comment]
You should be able to reset your password now - let me know if you still don't get an email.
