### ISSUE TITLE
Wrong Guild

### ISSUE THREAD

**Issue by mncubbie813** [jedi-gg/swgoh.gg.public#374]
Since the migration, swgoh is showing me in the incorrect guild:

Shows - DESTROY ALL WHO OPPOSE
Should Be - DAWO Blue Squadron

**Comment by bakou-swgoh** [comment]
I have the same issue too

**Comment by danpaulson** [comment]
Could you link your accounts + guilds?

**Comment by bakou-swgoh** [comment]
Account link: https://swgoh.gg/p/392261854/ 
Guild page: https://swgoh.gg/g/11104/an-enterprising-starship/

Thanks :)

**Comment by mncubbie813** [comment]
Account: https://swgoh.gg/p/763752939/
Guild: https://swgoh.gg/g/38112/dawo-blue-squadron/

**Comment by sanktanglia** [comment]
fixed
