### ISSUE TITLE
Can't view/find, log in, reset password to account (404: Not Found)

### ISSUE THREAD

**Issue by WASAWPPTRCK** [jedi-gg/swgoh.gg.public#375]
I've recently signed up and synced my account and was fine, but after the server change everything was lost. I can't log in (tried every password I could think of) and I don't receive any emails for resetting my password to my account.

This was the working link to my account on swgoh.gg and now it doesn't exist.
[https://swgoh.gg/u/wasawpptrck/](url)

**Comment by Joeyyyyyyyyy** [comment]
I am having the same Exact issue with my account.

I've had it working for a few years and now I'm unable to log in, or even change the password. 

I select 'reset password' and no email comes through 

https://swgoh.gg/p/685483925/

**Comment by danpaulson** [comment]
You should be able to reset your password now - let me know if you still don't get an email.
