### ISSUE TITLE
Hello, can yoe please chel my Sync https://swgoh.gg/u/jondampfdiagramm12/. 

### ISSUE THREAD

**Issue by JonDampdiagramm12** [jedi-gg/swgoh.gg.public#377]

**Comment by JonDampdiagramm12** [comment]
Hello, can yoe please check my Sync https://swgoh.gg/u/jondampfdiagramm12/.

I have created a new Account, because i coudnt log in at the old one. Now the new one would not sync.

**Comment by danpaulson** [comment]
If you could all go to your settings page (https://swgoh.gg/settings/) and re-sync, I believe it should work now.

**Comment by JonDampdiagramm12** [comment]
Thank you, it works.
