### ISSUE TITLE
Profile don't work

### ISSUE THREAD

**Issue by Bojke89** [jedi-gg/swgoh.gg.public#378]
I have created account, sync it sucessfully but I can't open my profile, getting 404, can someone help?

User
    GeraltOfRivia_117
Joined on
    Sept. 10, 2018, 12:24 p.m. (User # 288434)
Sync Status
    Active
Short URL
    https://swgoh.gg/u/geraltofrivia_117/

**Comment by Brunopl** [comment]
I have the same problem
User
Brunopl
Joined on
Sept. 10, 2018, 4:40 p.m. (User # 288495)
Sync Status
Active
Short URL
https://swgoh.gg/u/brunopl/

**Comment by zerdal** [comment]
I have created account, sync it sucessfully but I can't open my profile, getting 404, can someone help?

User
zerda
Joined on
Sept. 10, 2018, 2:33 p.m. (User # 288464)
Sync Status
Active
Short URL
https://swgoh.gg/u/zerda/

**Comment by danpaulson** [comment]
If you could all go to your settings page (https://swgoh.gg/settings/) and re-sync, I believe it should work now.

**Comment by Bojke89** [comment]
@danpaulson Ty! It's working now for me :)
