### ISSUE TITLE
After move: Creating new synched account seems not to work  (already in #370 but was closed without help)

### ISSUE THREAD

**Issue by DonationJoruus** [jedi-gg/swgoh.gg.public#379]
Dear SWGOH.GG Team,

since you finished your move creating a new account and synch it with the account seems not to work.
after enabling synch, typing the player id and setting the timezone and clicking on update profile, puts me back into SWGOH.GG Settings Menu but never updates the collection. Still shows the Synch your collection button. Any help? https://swgoh.gg/u/254615977/
UPDATE: On the other hand it seems to show now in Guild profile https://swgoh.gg/g/23547/dl-blue-squadron-701st/ nonetheless I still see nothing in my main menu. and i can't interact.
Thanks in advance and keep up the great work

PS: I already posted this issue a day ago but (#370) but it seems to be accidentally closed after @danpaulson  helped the second guy who added his problem to mine - still no idea how I can fix mine from above.

**Comment by PiMagicked** [comment]
I have the same issue. It actually seems the account sync: i can see the toons, zetas etc.. from the guild page but the top-right menu doesn't seem to 'know' about it.

**Comment by romanes13** [comment]
i have the exact same issues still 
https://swgoh.gg/u/romanes/
