### ISSUE TITLE
New account issue

### ISSUE THREAD

**Issue by PiMagicked** [jedi-gg/swgoh.gg.public#381]
Possibly related to #379 but not identical.

I created a new account for an alt. Several times, I input the settings for collection sync but it looks like it doesn't sync (the top-right menu shows only 'Sync your collection', 'Settings' and 'Log-out').

On the other hand, from the guild page, I can see it recognized and partially sync'ed (arena stats are missing) at https://swgoh.gg/p/199671375/

**Comment by DonationJoruus** [comment]
Yes it is an identical problem as i have in #379. Before I read your post I didn't even looked at guild page cause I still saw nothing in my main menu.

**Comment by PiMagicked** [comment]
username is JunKun. You're correct, after re-setting up sync settings, it now works.
Thanks

**Comment by danpaulson** [comment]
Good to hear!
