### ISSUE TITLE
Events Missing, Data Lost?

### ISSUE THREAD

**Issue by PJko777** [jedi-gg/swgoh.gg.public#384]
The "Events" label it's uncomplete, a few months ago there were plenty events on it, now it only shows 10 or even less, will you set them again? some of us need to check them to get info and to make a plan to face those we didn't ever do. please put them all again

**Comment by scoot1585** [comment]
yea, they changed how they send us data, I have a ticket in our private repo to fix this using a different way to process all known events.  I'm going to use this ticket as my main reminder publicly to fix this.

**Comment by keithslater** [comment]
Any update on this?

**Comment by sanktanglia** [comment]
hey sorry about missing this, adding this back to our to do to fix up

**Comment by scoot1585** [comment]
this is all fixed up, sorry about the wait, but now we also show all the times we have seen the events for the entire history of our data :)
