### ISSUE TITLE
API: Player update date

### ISSUE THREAD

**Issue by dlopezp** [jedi-gg/swgoh.gg.public#387]
Would be awesome get the player update date through the API in /api/guild/{guildId} and /api/player/{allyCode}

In the site, this data can be viewed under the profile name

**Comment by OMEGARAZER** [comment]
The date on the updates also seems to be a day behind for whatever reason. Today's update is showing as yesterday rather than today. That may just be me though, I'm not sure.

**Comment by sanktanglia** [comment]
added
