### ISSUE TITLE
Missing ability class: Dispel - All enemies

### ISSUE THREAD

**Issue by EzraCc** [jedi-gg/swgoh.gg.public#389]
Currently (2018-09-13) There are only two characters tagged as having the "Dispel - All enemies" abilities. B2 and Echo.
https://swgoh.gg/characters/f/dispel-all-enemies/

There are other characters who have those abilities. E.g., Assaj Ventress, Baze, Qi'Ra (if prepared).

There appears to be no equivalent "Dispel - All allies" classification. E.g., Ackbar, Talia (NS allies)

**Comment by scobenes** [comment]
This one is sort of fixed and sort of not, especially for dispell allies because of how things are worded and too many edge cases.  We probably wont be doing more til I rewrite how it determines this to be a bit smarter
