### ISSUE TITLE
404 Error for Squad Templates

### ISSUE THREAD

**Issue by NICKSALEX** [jedi-gg/swgoh.gg.public#391]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

I can’t get to the Squad Template Page for my Guild.  Displays 404 Error so I can even get page to load for creating new templates:

https://swgoh.gg/g/31783/porkins-alliance/squad-templates/

I assume the existing squads have been lost in the transition so I would like to create new ones.  Thanks.

**Comment by scobenes** [comment]
This is most likely an old bug
