### ISSUE TITLE
Error with adding a new Squad Template

### ISSUE THREAD

**Issue by CruorV** [jedi-gg/swgoh.gg.public#393]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
Our guild have some squad templates, which were added a long time ago, for example https://swgoh.gg/g/22847/crossroad-keep/squad-templates/20765/
I try to add new ones, and all I can see as a result is a template title https://swgoh.gg/g/22847/crossroad-keep/squad-templates/46869/
But if I try to edit it i have full information on a template.
P.S. Sorry for my bad English :)

**Comment by Nathaire** [comment]
We're experiencing the same issue with this template (just to look for a player having Gamorrean Guard: https://swgoh.gg/g/25019/cartel-insurrection-aurek/squad-templates/47178/

The result is an empty page.

Looking into the console shows following errors:
![image](https://user-images.githubusercontent.com/8290006/45619317-220ebb00-ba79-11e8-8745-11fbc7754460.png)

**Comment by scobenes** [comment]
This is most likely an old bug
