### ISSUE TITLE
dropdown list malfunction in ios safari

### ISSUE THREAD

**Issue by fscanp** [jedi-gg/swgoh.gg.public#394]
Cant pick anything from the dropdown list on Guild Unit Search using ios 11 Safari app. The list is working. Just cant elect anything in it. Tapping on a character name will just close the dropdown without actually highlighting the entry and thus rendering the page useless.

**Comment by Kazanori** [comment]
Yep this is a big issue and needs to be sorted ASAP

**Comment by pcrequest** [comment]
Yes!  The website is not useful on any iOS device.  I play the game on iPad and iPhone.  And third party browsers like Edge or Chrome simply use Safari as the underpinning browser.

**Comment by scobenes** [comment]
I remember sank fixing this back in the day, most likely old bug
