### ISSUE TITLE
Guild not syncing (5 days now)

### ISSUE THREAD

**Issue by Dblade21** [jedi-gg/swgoh.gg.public#395]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Guild account hasnt synced in 5 days. 

https://swgoh.gg/g/21439/sent-by-ravens/

**Comment by psultimate** [comment]
Our guild also hasn't synced in 5 days.

https://swgoh.gg/g/18613/tie-brides/

**Comment by ZiroG** [comment]
And ours.  https://swgoh.gg/g/14047/force-users-anonymous/

**Comment by Dblade21** [comment]
Looks like it finally synced up. Dont know what caused it. Either way, thanks. Closing the thread
