### ISSUE TITLE
Option to hide ally code are missing.

### ISSUE THREAD

**Issue by ZhenyaKanaeva** [jedi-gg/swgoh.gg.public#399]
Hi team, seems like option to hide ally code no longer available. Not everyone like to be contacted all day long for guild recruiting etc etc. Please restore that option if possible. Thank you.

**Comment by mol-gugek** [comment]
This was addressed in #392 ... I don't think this is going to be revisited.

**Comment by sanktanglia** [comment]
yeah this is removed as part of our update
