### ISSUE TITLE
API - connect players with characters

### ISSUE THREAD

**Issue by chmod** [jedi-gg/swgoh.gg.public#401]
Reading a player's characters using the /api/player/{ally_code}/ endpoint doesn't return characters' "pk" field but the "base_id" (string). 
The "pk" (number) is required in order to identify the character directly using the endpoint /api/characters/{id}/ thus it is impossible to fetch the player's characters data unless fetch all and filter out by base_id which is time consuming.

**Comment by scobenes** [comment]
You can get all of the characters from /api/characters/ and then just do memory lookup for whatever unit you need access to
