### ISSUE TITLE
Meta Report All Characters

### ISSUE THREAD

**Issue by TobyCooper** [jedi-gg/swgoh.gg.public#404]
Is it correct that just 25 Characters are on the list? This was in the past a way longer.

**Comment by TobyCooper** [comment]
Sorry i'm bring this back. Is there any chance to get this data? In the current meta i see just the Jedi and Revan Teams. (no FO, BountyHunters. etc.)

The old meta report shows everytime all toons.

**Comment by ExarKunRFS** [comment]
Oh man, _please_ bring back the longer list, my dudes. In the next 24 hours, we'll have 168 characters. Seeing only the top 15% goes virtually unchanged day after day. It was really helpful after a Marquee Event to see if a character was climbing the meta, and actually pointed me where to start farming or spending crystals.

What I'm saying here is, bring this back and I'll give you all tummy scritchems.

Peace and taco grease.

**Comment by sanktanglia** [comment]
Im definitely open to the idea of expanding this to all characters. Im also toying with the idea of saving a snapshot of stats daily so we can track the trends historically

**Comment by scobenes** [comment]
Won't matter anymore since this is for squad arena which isnt useful anymore
