### ISSUE TITLE
Profile syncing at weird times occasionally

### ISSUE THREAD

**Issue by DylanTusler** [jedi-gg/swgoh.gg.public#407]
My normal profile synch time is around 6.00pm

Three times recently the profile has been synched well outside normal time. Once at 2.34am, once at 6.35am and final time shown below at 6.13am.
 
![image](https://user-images.githubusercontent.com/11711132/45924126-3cdea500-bf3b-11e8-9d9e-9153782aa28a.png)

Is this a known issue? What is causing these out-of-band synchs?

https://swgoh.gg/p/445277377/

**Comment by sanktanglia** [comment]
Sometimes we have issues with our syncer that causes it to be backed up and syncs to get behind, we try to get around it but it happens from time to time, should happen alot less with the new system
