### ISSUE TITLE
Guild unit search do not work on iPhone X

### ISSUE THREAD

**Issue by celsogbj** [jedi-gg/swgoh.gg.public#408]
The unit search for guilds is not working on Safari / iPhone X.

**Comment by Kazanori** [comment]
This is iOS wide and really needs sorting asap

**Comment by dkkd** [comment]
Guild unit search don’t work on iPhone

**Comment by scobenes** [comment]
duplicate of https://github.com/jedi-gg/swgoh.gg.public/issues/394
