### ISSUE TITLE
Wrong Guild's Squad Template Button

### ISSUE THREAD

**Issue by oddcow** [jedi-gg/swgoh.gg.public#413]
I switched guilds while your website was moving servers.  For a while after I moved guilds, swgoh.gg showed me still in my old guild.  Though this has been corrected, the main feature I would like to use on the website is the Squad Template feature. However, in my new guild, on the menu on the left of the screen, the squad template button does not exist. If I go to my old guild's page, the squad template button is still there, but if I click it I get an error message. I have taken screen shots showing that I am logged in, and showing which guild I am in to demonstrate my issue:
<img width="1286" alt="no squad template" src="https://user-images.githubusercontent.com/10102287/45971415-f8b8d680-c006-11e8-9731-545e23e21fbd.png">
<img width="1301" alt="wrong guild" src="https://user-images.githubusercontent.com/10102287/45971432-fe162100-c006-11e8-9542-52d6e87983a4.png">

For reference, my account is: https://swgoh.gg/p/492973312/
And my current guild page is: https://swgoh.gg/g/1308/live-long-and-shoot-first/
My former guild page is: https://swgoh.gg/g/12573/op-neptune/

**Comment by oddcow** [comment]
I had a guildmate send me a link to the Squad Templates, and that link worked and I can look at who has what toons and such. I just don't know why the link isn't an option for me when I travel to the website with my account.

**Comment by danpaulson** [comment]
This should be fixed - let me know if it's not.

**Comment by oddcow** [comment]
It has been fixed. Thank you
