### ISSUE TITLE
Internal Server Error for specific Player ID

### ISSUE THREAD

**Issue by iambrainlag** [jedi-gg/swgoh.gg.public#414]
Dear swgoh.gg maintainers  and developers,

thank you for your great efforts on swgoh.gg and of course for your outstanding job .  

We are having issues registering a guild member  with error 500.  This happens only when we try the Player ID: 498547322 . 

Username: pilios-gousis
Joined on: Sept. 25, 2018, 8:37 a.m. (User # 291655)
Player ID: 1FSp2itdTeSImn0ePeLrlg
Ally code: 498547322 
Result: http://prntscr.com/kyez97

Let me know if you need any further information or detail about the issue.

Best Regards,
Alex A.

**Comment by scobenes** [comment]
This is most likely an old bug
