### ISSUE TITLE
Bounty Hunters not displaying when filtered to in the "Characters" page of a player

### ISSUE THREAD

**Issue by CaptanHamm** [jedi-gg/swgoh.gg.public#416]
**_Looking to see what bounty hunters looked like for a shard mate of mine who runs them in arena, instead, saw this:_**

https://swgoh.gg/p/348156715/characters/?f=Bounty+Hunters
![image](https://user-images.githubusercontent.com/36648742/46155257-816c8800-c23c-11e8-8d54-e4b932393c84.png)

**_And here is his arena team:_**

https://swgoh.gg/p/348156715/
![image](https://user-images.githubusercontent.com/36648742/46155279-90533a80-c23c-11e8-8414-89c17f381d9d.png)

I checked on others accounts too, and saw the same behavior.
https://swgoh.gg/p/888136654/characters/?f=Bounty+Hunters
![image](https://user-images.githubusercontent.com/36648742/46155389-ca244100-c23c-11e8-80fb-a12222074cf3.png)

https://swgoh.gg/p/888136654/characters/
![image](https://user-images.githubusercontent.com/36648742/46155443-e922d300-c23c-11e8-8828-91d4639eeab9.png)

**Comment by sanktanglia** [comment]
fixed
