### ISSUE TITLE
Verbiage on guild pages with exactly 10 members

### ISSUE THREAD

**Issue by loudambiance** [jedi-gg/swgoh.gg.public#418]
There is a message on guild pages with less than 10 members stating:

> This guild has less than 10 profiles, and thus has a lower cadence to update. It will update every Sunday evening.

Either the code that displays this message has an error and still displays for guilds with exactly 10 members on swgoh.gg, or the message should read "This guild has 10 or fewer profiles,..."

An example is: https://swgoh.gg/g/20675/eversince/

**Comment by scobenes** [comment]
This is fixed thanks
