### ISSUE TITLE
The name of our guid doesn't appear

### ISSUE THREAD

**Issue by Bleach1st** [jedi-gg/swgoh.gg.public#422]
Hi
Our guild "Reb0rn Zeta Ζ" doesn't appear on swgoh.gg
The last letter comes from the greek alphabet. Can you take a look at my profile please ?
https://swgoh.gg/p/883232683/
Thank you

**Comment by johtr** [comment]
Hello, my guild is also affected by this. It was made about 5-6 days ago. I asked my guild leader to manually sync his profile: https://swgoh.gg/p/138858347/

I have also manually synced my profiles
https://swgoh.gg/p/155265593/
https://swgoh.gg/p/572543852/

The Guild name: GotW Guild With No Name

Thanks,
John

**Comment by Bleach1st** [comment]
It’s ok now
👌🏻

**Comment by robertseb** [comment]
Hello,

My guild "Les Loups de Gîvre" doesn't appear on swgoh.gg
This is the adress for my profile : https://swgoh.gg/p/915165779/
Can you help me please.
thx in advence

Seb
