### ISSUE TITLE
Sith Triumvirate Misspelled 

### ISSUE THREAD

**Issue by tdm00** [jedi-gg/swgoh.gg.public#427]
On the form to create a new squad `https://swgoh.gg/squads/create/` the word "Triumvirate" is misspelled in the Category drop-down (select) list.

![Create Squad Screen](https://cl.ly/f8074f624bb9/Image%2525202018-10-11%252520at%25252012.22.22%252520AM.png)

**Comment by scobenes** [comment]
This seems to have been fixed
