### ISSUE TITLE
API Squads question

### ISSUE THREAD

**Issue by destinio** [jedi-gg/swgoh.gg.public#429]
Could not find a better place to ask this so here goes:

I stumbled upon https://swgoh.gg/api and had a question about what ID is required for /api/players/{id}/squads/

I have tried a few things the main one being my ally code which returns:
`
{
    "count": 0,
    "squads": []
}
`

Wrong ID, endpoint not working? Any and all help is much appreciated!!

**Comment by AlessandroRotatori** [comment]
Maybe my evidences can be of help.
I've tried some random numbers as id and It seems that for specific values the request returns a results (i.e. 134324 or 134325, the latter returns 7 squads).
However, I've tried:
- Id as (my) guild id,
- Id as (my) user id,
- id as (my) squad id.
And i am not able to retrieve any information.

**Comment by scobenes** [comment]
We no longer have this endpoint in the API
