### ISSUE TITLE
API Refresh/Update Time

### ISSUE THREAD

**Issue by xeynx** [jedi-gg/swgoh.gg.public#433]
I have a couple of questions regarding the API data and when it is updated from the website data.

1) Can you please let us know what time it gets refreshed?  (I can't seem to find that anywhere.)
2) Is it possible (perhaps a new API function) the date/time the last refresh occurred?
3) Can you schedule to refresh the data in the API a couple of hours before Territory Wars lock takes place?  We use some of the API data to help with Territory Wars and it's difficult when we may have new members that joined and show the correct guild on the website but do not appear in the API data.

**Comment by sanktanglia** [comment]
refreshing automatically before territory wars is something thats on our list, and I can definitely add the last update time to the api response

**Comment by sanktanglia** [comment]
Added the last updated time to the player api
