### ISSUE TITLE
my guild does not appear in swgoh.gg

### ISSUE THREAD

**Issue by robertseb** [jedi-gg/swgoh.gg.public#435]
Hello,
My guild "Les Loups de Gîvre" does not parear in swgoh.gg
Here is my swgoh profile : https://swgoh.gg/p/915165779/

Could you help me please.

THX in advance

Seb

**Comment by kennethvde** [comment]
Hi,

I have the same problem, although i am not sure if it really is an issue. It is a guild that exists for about 10 days. 

My profile is https://swgoh.gg/p/149968395/

Kind regards,

**Comment by ard2swgoh** [comment]
hello i have The same problem my guild does not appear in swgoh a been created 3 days ago
name of the guild "cantina de mos eisley reborn"
I leave my profile
Thank you
https://swgoh.gg/p/127916653/

**Comment by robertseb** [comment]
hi,

you just have to wait !! about 16 days and the problem disappear alone, the update for a new guild is ... LONG !! but don't worry just wait !!

**Comment by sanktanglia** [comment]
the sync for missing guilds was failing to run causing problems, this should be running daily now
