### ISSUE TITLE
Ship's Ability Levels 106%

### ISSUE THREAD

**Issue by Aveane** [jedi-gg/swgoh.gg.public#436]
I think it's because Reinforcement Abilities. I'm not sure if it's intended.

![image](https://user-images.githubusercontent.com/35532581/47714098-37603300-dc3c-11e8-9fe8-a550b89737b4.png)

**Comment by sanktanglia** [comment]
thanks well get this fixed up

**Comment by sanktanglia** [comment]
this is now fixed
