### ISSUE TITLE
Player ID Issues

### ISSUE THREAD

**Issue by demon-chaser** [jedi-gg/swgoh.gg.public#437]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

I have tried all the different combinations I could think of, I still continue to run into the same error: 
*Player ID not found. Please ensure you typed it correctly. 

I did receive a 403 Error on the type ID listed. 

https://swgoh.gg/id-help/

![20181101_121742](https://user-images.githubusercontent.com/22546566/47874337-26005d80-ddd9-11e8-9f5b-63b80d547580.jpg)

https://swgoh.gg/settings/sync/

![20181101_121857](https://user-images.githubusercontent.com/22546566/47874336-24cf3080-ddd9-11e8-96cb-9470e7f94325).jpg

I have tried all these different combinations for the PlayerID:
YNQDlafSsuUOQlq4EDP0w
YNQDlafSsuU0Qlq4EDP0w
YNQDIafSsuU0Qlq4EDP0w
YNQDIafSsuU0QIq4EDP0w
YNQDlafSsuUOQlq4EDP0w
YNQDlafSsuUOQlq4EDPOw
YNQDIafSsuUOQlq4EDP0w
YNQDlafSsuU0QIq4EDPOw
YNQDIafSsuUOQIq4EDPOw

![20181101_121857](https://user-images.githubusercontent.com/22546566/47874456-7c6d9c00-ddd9-11e8-90a5-a240a6142f47.jpg)

My ally code is: 
215-699-219

Guild Name:
Class of the Rebellion

Username:
DemonChaser

Email associated to account and the game:
bsufan79@gmail.com

**Any assistance in trying to sync my data would be greatly appreciated.

**Comment by sanktanglia** [comment]
you need to use the dash, your player id is -YNQDlafSsuUOQlq4EDP0w including the dash

**Comment by demon-chaser** [comment]
Thank you

**Comment by demon-chaser** [comment]
Good Afternoon,

I tried the Player ID with the - and I got an error. Attached is the
screenshot. And below is the URL

https://swgoh.gg/p/215699219/

Thank you for your assistance.

**Comment by sanktanglia** [comment]
looks like it just cached the 404, https://swgoh.gg/p/215699219/? works for me
