### ISSUE TITLE
Wrong information under Ability Tier

### ISSUE THREAD

**Issue by psytor** [jedi-gg/swgoh.gg.public#440]
Good Day,

I can now see the Ability_Tier under ability but I think the information pulled is wrong...

For example my Jedi Consular is 3 on all skills but I get ability_tier:1

None of my characters seems to pull more that tier:3.

**Comment by sanktanglia** [comment]
can you link the character you are seeing it differ on?

**Comment by psytor** [comment]
https://swgoh.gg/api/player/687777589/

**Comment by sanktanglia** [comment]
fixed

**Comment by psytor** [comment]
Thanks for the quick fix!!
