### ISSUE TITLE
Please add a pilot designation to the /characters API and/or crew members to the /ships API

### ISSUE THREAD

**Issue by grandivory** [jedi-gg/swgoh.gg.public#441]
Currently, the /characters and /ships API endpoints together are a wonderful way to get static data about game resources. One thing that's missing, though, is the ability to tell if a character is a pilot, or for a ship which characters pilot that ship. Please add some indicator to each API to show which characters are pilots and which characters pair with each ship.

**Comment by sanktanglia** [comment]
Added
