### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by Porthos72** [jedi-gg/swgoh.gg.public#443]
Hi, a few days ago I was logged out of my account. Now,  every time I attempt to log into my account, it gives me a message called 403 (I'll add a picture below),  whichtalks about why I can't get in. Any help?  Thanks in advance. 
![screenshot_20181107-194700](https://user-images.githubusercontent.com/42918155/48172555-eac4c980-e2c5-11e8-9462-e95c76581ddd.png)

**Comment by sanktanglia** [comment]
can you try again? should be fixed
