### ISSUE TITLE
Delete my acc.

### ISSUE THREAD

**Issue by DiNoZoTv** [jedi-gg/swgoh.gg.public#444]
Hello!

Iam not play anymore and deleted my swgoh account. 
Can you plz delete my swgoh.gg account?

https://swgoh.gg/p/272383994/

Thank you

**Comment by DiNoZoTv** [comment]
Hello?
Someone here?

**Comment by scobenes** [comment]
If anyone needs to delete an account there is a button in your profile settings to do so. https://swgoh.gg/settings/profile/
