### ISSUE TITLE
Player ID not working 

### ISSUE THREAD

**Issue by rcrawf202** [jedi-gg/swgoh.gg.public#445]
I've looked my account up in the SWGOH look up tool and copied it from that and the player ID seems to be unable to be found. 

Here's what I believe are the correct details:
Ally Code: 126-923-847
Player ID: z1C6BWTcR-qWcLxsKIhCgg
SWGOH.gg Account name: Crawford1996
Ingame name: Crawford

**Comment by sanktanglia** [comment]
https://swgoh.gg/p/126923847/ is your account, looks like it got added for you. im working on fixing up the manual sync so that it should find it right away
