### ISSUE TITLE
collection scores for guild miscalculated

### ISSUE THREAD

**Issue by dloder0** [jedi-gg/swgoh.gg.public#447]
The guild view of 7* character count does not match the individual view, which is correct.

https://swgoh.gg/g/21771/tosche-station-cantina/collection/
ex:
for Slacker036 https://swgoh.gg/p/212641174/ shows 102 7*, but the guild page shows 124

**Comment by sanktanglia** [comment]
the issue is one counting ships while the other does not, we are discussing if we want to update one or the other to match

**Comment by sanktanglia** [comment]
we just updated the guild page to match, thx for the report
