### ISSUE TITLE
Player ID not working

### ISSUE THREAD

**Issue by kudlaty2012** [jedi-gg/swgoh.gg.public#449]
I've looked my account up in the SWGOH look up tool and copied it from that and the player ID seems to be unable to be found.

Here's what I believe are the correct details:
Ally Code: 813-721-249
Player ID: xf-1TKcUTimLII0yTgMww
SWGOH.gg Account name: kudlaty2012
Ingame name: kudlaty2012

**Comment by sanktanglia** [comment]
your player id is xf-1TKcUTimLGllOyTgMww
the 0s and Os are confusing i know

**Comment by kudlaty2012** [comment]
I changed O to 0, and it does not see me

**Comment by sanktanglia** [comment]
https://swgoh.gg/p/813721249/ it looks like there is an issue on the delay for our sync, im looking into it but i got you able to sync, sorry about that!

**Comment by kudlaty2012** [comment]
I will be grateful for your help

**Comment by kudlaty2012** [comment]
I still can not do synchronization

**Comment by sanktanglia** [comment]
@kudlaty2012 id just try again, I was able to sync your character just fine and I have it linked to my account atm. If you copy the player id i posted on here it should work
