### ISSUE TITLE
Average guild arena rank

### ISSUE THREAD

**Issue by gitwengz** [jedi-gg/swgoh.gg.public#452]
Guild page: https://swgoh.gg/g/79/nsftw-black/
Average arena ranking: https://swgoh.gg/g/

Hi, trying to figure out why the average arena ranking for us is not reflecting or averaging correctly. From the guild page, there are a three guildies that joined recently but their average ranking has not been able to be tabulated. Wondering if this is one of the reasons why the average is not reflecting?

Secondly, is it also taking averages of past guild members who left up to a certain period of time? Seeking to get a better understanding and hope you guys can have a look. Thanks.

**Comment by sanktanglia** [comment]
most likely its just a caching thing, as I now see the same average rank on the guild page and the search page(they have different caches) If we rescan old guild members they should get added to their new proper guild though, if you see anyone stuck for more than 24 hours lemme know

**Comment by gitwengz** [comment]
Hi. Thanks for your reply. I did a manual calculation of our current guildmembers and its roughly 1.8. I also note that 3 of our guildmembers’ average rank is still not being averaged in. 

I’m curious could it be because of ex guildmembers who have left the game but are guildless that still may be averaged in?
https://swgoh.gg/p/454346219/
https://swgoh.gg/p/868874326/

With these two averaged in, the manual average calculation becomes more than 4.  We’ve had another two more who quit and are not part of any guild. Could it possibly be the reason ?

**Comment by sanktanglia** [comment]
hmm ill look into it and see exactly how its calculating that value. users shouldnt be without a arena rank on that page for more than a day, so if they continue to show up blank then theres something that needs fixing. Will reply once ive figured it out

**Comment by gitwengz** [comment]
Thanks!!
