### ISSUE TITLE
Hide profile

### ISSUE THREAD

**Issue by bjeenie2** [jedi-gg/swgoh.gg.public#455]
Make it possible to hide your profile for others except for members of your guild.
Make it possible that your profile can't be searched by google. (and if it still happens show them a 404...)

**Comment by danpaulson** [comment]
Game data is publicly accessible, by us and anyone with the tools. We won't be hiding game data. If you'd like to remove your SWGOH.GG account you can email me (danpaulson@gmail.com), but your game profile will remain public.
