### ISSUE TITLE
Not updating with time change to account

### ISSUE THREAD

**Issue by Keszey** [jedi-gg/swgoh.gg.public#458]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
For example I mpved my payout up an hour and took first place today. It was recorded as third as I was in third place at the time of my original payout.
https://swgoh.gg/p/935513752/

**Comment by sanktanglia** [comment]
we currently dont automatically update your payout time but its something wed like to support, did you update it on the website?

**Comment by Keszey** [comment]
No, I didn't you can pull this, I didn't think to do that.
