### ISSUE TITLE
UTC time offsets are limited to "on the hour" therefore all :30 and :45 are missing

### ISSUE THREAD

**Issue by Zanth** [jedi-gg/swgoh.gg.public#459]
I see that this is not the first time this issue has been mentioned:

https://github.com/jedi-gg/swgoh.gg.public/issues/112
https://github.com/jedi-gg/swgoh.gg.public/issues/236

but each of those tickets were closed without any followup messages.  My timezone is in French Polynesia (Taoihae) - UTC-9.5 offset.  My profile: https://swgoh.gg/p/918225742/

Thank you in advance for any help you might offer.

**Comment by sanktanglia** [comment]
we hope to have a fix for this soon, i expect to roll it out in the next week or so

**Comment by scobenes** [comment]
This is most likely an old bug
