### ISSUE TITLE
incorrect nrs on  the ranking on guild leaderboard with average arena ranking

### ISSUE THREAD

**Issue by Iwan55555** [jedi-gg/swgoh.gg.public#460]
The leaderboard rankinglist - Guild Arena Average   , we talked before about this... 
and it should be the individual guildmember arena average ranking from all players together divided by the number of registered players...
Ofcourse no need to say again that guild must be in top 200 of either haat/rancor board.. we know that.

This is atleast what you before explained and for a long period it worked like that
Now over a month that does not seem to be correct anymore... 
and i am not talking about the empty places on the individual players which if u click on the player u can actually see.. but the total nr...

for example look at : https://swgoh.gg/g/84/team-steroid/

at the moment of posting it only has 2 players with a ranking above 9 and rest is all around 1,2,3
and if u count em up (not the actual day but the average rankings) and u divided em with the registered 
u just need 2 seconds to alrdy figure that nr is not correct looking quick over the averages
members u get a way lower average then 8.94 as shown on your leaderboard..

**Comment by sanktanglia** [comment]
so part of the problem is our guild sync process is busted due to some changes in the game server so once that is fixed up it will be back to recalculating the averages nightly. Thats also something to remember, the value shown on the listing is calculated nightly and the ones on the page are whatever is current in the db. I am taking a 2nd look at the calcs to see whats up though

**Comment by sanktanglia** [comment]
btw I think i have figured it out and it looks like its just a weird bug with our usage of elastic search, im making some tweaks around it now that should fix it up, will post when its live

**Comment by Iwan55555** [comment]
thnx!  thats fast work done! great job!

**Comment by sanktanglia** [comment]
ok new code is still calculating the averages for all guilds but your guild was the one I tested on. The details page will now show all users in the guild with their average rank over the last 30 days. We also decided to swap the average rank that we use for scoring to be average current rank, so its more clear. Let me know if you spot anything weird, thx for the report!
