### ISSUE TITLE
Abilities get responding with HTML

### ISSUE THREAD

**Issue by Krahegwen** [jedi-gg/swgoh.gg.public#461]
When doing a request to https://swgoh.gg/api/abilities it responds with status code 200 (OK) but the response is a wrap of the response inside HMTL and not directly the JSON

**Comment by Krahegwen** [comment]
![image](https://user-images.githubusercontent.com/15855474/49696585-129c9b00-fbac-11e8-8d86-35ae902fe5bd.png)

**Comment by Krahegwen** [comment]
![image](https://user-images.githubusercontent.com/15855474/49696593-48418400-fbac-11e8-9571-0921e93bb1e9.png)

**Comment by sanktanglia** [comment]
hmm odd, i think we need to fix how the api responses cache based on response type, can you try now?

**Comment by Krahegwen** [comment]
Solved
