### ISSUE TITLE
IG-2000 and Jango Fett not showing up on their hard nodes

### ISSUE THREAD

**Issue by KalSarkon** [jedi-gg/swgoh.gg.public#462]

**Comment by KalSarkon** [comment]
Jango Fett and IG-2000 were assigned hard nodes in the 5 December update, but they are not showing up on their new nodes in the battle database.  Could be you guys just haven't gotten to it yet, but thought I would point it out in case it was missed.  Thanks!

Links to appropriate nodes in battle database:

- [LS- 6](https://swgoh.gg/db/missions/lightside/?stage=M06)
- [LS-8](https://swgoh.gg/db/missions/lightside/?stage=M08)

Text from [5 December Update](https://forums.galaxy-of-heroes.starwars.ea.com/discussion/189249/scheduled-update-12-05-2018):
> **Jango Fett**
> Jango Fett will be available on Light Side Battles 8-D Hard Node
> Jango Fett will replace the Stormtrooper, the character currently on Light Side Battles 8-D Hard. The Stormtrooper will continue to be farmable in Light Side Battles 3-C Hard.
> **IG-2000**
> IG-2000 will be available on Light Side Battles 6-E Hard
> IG‌-2000 is an addition to Light Side Battles 6-E Hard and does not replace any possible rewards currently available there.

**Comment by scobenes** [comment]
This is most likely an old bug
