### ISSUE TITLE
Feature suggestion: Character filter for farm location

### ISSUE THREAD

**Issue by kuko01** [jedi-gg/swgoh.gg.public#464]
When checking `My Characters`, there is a filter for `Categories`, `Alignment `and `Ability Classes`. It would be really nice to be able to filter for `Farm locations`  e.g. Cantina energy, Hard node, Cantina Shop, etc.

**Comment by sanktanglia** [comment]
I like this! adding it to our todo

**Comment by sanktanglia** [comment]
nope just some internal notes we keep in slack, we had an updates page at one point but it seems to have broken

**Comment by emptied** [comment]
👍  on this, came here to make that suggestion. Just finished a cantina farm and it was a pain to figure out where to start pumping that energy next.

**Comment by kuko01** [comment]
That way exactly the reason why I opened this suggestion for the first place :D

**Comment by temaat89** [comment]
Came here to suggest this feature.  Glad it is already being worked on!

**Comment by sanktanglia** [comment]
this is now live!
