### ISSUE TITLE
Member of guild removed, still visible

### ISSUE THREAD

**Issue by QuiVallSte** [jedi-gg/swgoh.gg.public#467]
Hi, I am an officer from the guild https://swgoh.gg/g/24845/jedimastersnl/. We removed a member a couple of weeks ago from our guild in the game. He still shows up in the list on SWGOG.GG. Can you remove this person for us?

This is the profile of the member which is still linked to our guild:
https://swgoh.gg/p/868458647/

Thanks!

**Comment by sanktanglia** [comment]
ill get them removed, its part of an issue with data quality im working on fixing up

**Comment by QuiVallSte** [comment]
Thanks!
