### ISSUE TITLE
Malware distribution through advertising

### ISSUE THREAD

**Issue by tdm00** [jedi-gg/swgoh.gg.public#472]
### WITHOUT URLS, YOUR TICKET WILL NOT BE RESPONDED TO
https://swgoh.gg/p/191155833/

### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
When going to view my profile page at https://swgoh.gg/p/191155833/ at 12/18/2018 10:04:10 AM EST one of the ads that loaded attempted to load malware to my system. This was detected by my network virus scanning system and I was alerted to it. Unfortunately it did not provide me the advertisers domain that was flagged with the malware. I realize this may limit your ability to determine which ad site may have tried to deliver this malicious payload, but hopefully with the URL and date/time stamp above you're logging or Google Analytics could help narrow it down.

**Comment by sanktanglia** [comment]
unfortunately we dont have any visibility on the ads or control over which one is shown as we partner with another company for our ad rotation, ill reach out to them to let them know though
