### ISSUE TITLE
Site Redirects to Flash Install 

### ISSUE THREAD

**Issue by rwgrier** [jedi-gg/swgoh.gg.public#473]
There are times when I load the site in Safari on my desktop that I'll be redirected to a different site and asked to update/install Flash. It won't happen on every page load. 

I am not sure if it's an ad or something on the site. I do not have ad blocking turned on for this site.

URL: https://swgoh.gg
Browser: Safari 12.0.1 (14606.2.104.1.1)
macOS: Mojave 10.14.1 (18B75)

**Comment by scobenes** [comment]
This is most likely an old bug, or related to a malicious ad provider
