### ISSUE TITLE
Mods displayed in game are not displaying in swgoh.gg

### ISSUE THREAD

**Issue by justke86** [jedi-gg/swgoh.gg.public#474]
There are many mods that I can see in my mod list within the swgoh app, however they are missing from swgoh.gg, even after a performing a manual sync, these mods are still not available within swgoh.gg.

This is occurring as of 11/20/2018.

Below are two screenshots of the same mod filter showing at least 2 missing mods, just to show that the issue is there.

<img width="916" alt="screen shot 2018-12-20 at 10 19 13 pm" src="https://user-images.githubusercontent.com/4230647/50322944-6a3cdf80-04a5-11e9-9874-ec130701ee5e.png">

![screenshot_20181220-221249](https://user-images.githubusercontent.com/4230647/50322958-788afb80-04a5-11e9-9783-5a085d904a03.png)

**Comment by sanktanglia** [comment]
whats your ally code?

**Comment by justke86** [comment]
952-364-867

**Comment by sanktanglia** [comment]
We only know about the mods you currently have equipped on your characters.
