### ISSUE TITLE
Fleet arena history does not show rank in payout time

### ISSUE THREAD

**Issue by orik007** [jedi-gg/swgoh.gg.public#477]
Hey

Im always first in fleet arena in my payout time.
https://swgoh.gg/p/468537586/

Still in history graph it show different ranks, probably cause you have one global time when you take ranks.

My suggestion is to take payout time for each player. (maybe its same for arena)
Thanks

**Comment by sanktanglia** [comment]
it takes time to sync fleet arena, which is why it can be 15-20 minutes after payout time. We already use the payout time you set in our settings to scan people, but we have hundreds of thousands of players to scan, so we cant scan them all in a single minute

**Comment by orik007** [comment]
ok, thanks for answer. Didnt know you have to actually scan the rank online. I thought for some lastFleetArenaRank field, but EA has no API :-). GJ then.
