### ISSUE TITLE
Broken links to ships from profile collection pages 

### ISSUE THREAD

**Issue by Turkey007** [jedi-gg/swgoh.gg.public#478]
If you go to a ship in someone's profile, e.g. https://swgoh.gg/p/176994547/characters/hounds-tooth
and you click the ship's name, it links to:
https://swgoh.gg/characters/hounds-tooth/ 

But it should link to:
https://swgoh.gg/ships/hounds-tooth/

**Comment by scobenes** [comment]
This is a bad link.  the fact you can see hounds tooth on a character template is actually the bug
