### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by FabTimm** [jedi-gg/swgoh.gg.public#479]
Hello,

I've stopped the game today and would like that my login, account and infos are deleted.
url: https://swgoh.gg/p/499532292/ or Username URL
https://swgoh.gg/u/mad_cat/.

Thanks for all.

Mad Cat

**Comment by FabTimm** [comment]
Anyone out there ?

**Comment by sanktanglia** [comment]
sorry ill try to find some time to do this this week

**Comment by FabTimm** [comment]
Still not done ?

**Comment by scobenes** [comment]
If anyone needs to delete an account there is a button in your profile settings to do so. https://swgoh.gg/settings/profile/
