### ISSUE TITLE
Arena Zero Rank

### ISSUE THREAD

**Issue by JimiC** [jedi-gg/swgoh.gg.public#480]
Arena rank should not consider zero (0) as highest rank.

Reproduction steps:
- Make a new account in Heroes
- Make an account with `swgoh.gg` before `Squad Arena` is available in-game for the player.
- Start participating in `Squad Arena` in-game.
- The issue is presented (ss below).

https://swgoh.gg/p/219266166/
![image](https://user-images.githubusercontent.com/1716442/50539393-502b8d00-0b88-11e9-9072-3d8ee05a4dbf.png)

Proposing starting rank to be 99999

**Comment by scobenes** [comment]
This is most likely an old bug
