### ISSUE TITLE
API: Bad arena rank of some players in request guild

### ISSUE THREAD

**Issue by cadetill** [jedi-gg/swgoh.gg.public#481]
I'm retrieving info about our guild from API and it returns a bad rank arena. ie:
I retrieve this from a query guild
https://swgoh.gg/api/guild/37003/
......."arena_rank":15,"arena_leader_base_id":"DARTHTRAYA","last_updated":"2018-12-27T16:05:19.420639","name":"El del Sable".....

but from a query player (that is correct)
https://swgoh.gg/api/player/427725828/
........"leader":"DARTHTRAYA","rank":1},"name":"El del Sable"........

thanks for comments

**Comment by sanktanglia** [comment]
each api request has its own cache, so its possible the player and guild api call would be cached with different data. it appears the guild data has the previous days player data for example, before it updated
