### ISSUE TITLE
API: arena rank

### ISSUE THREAD

**Issue by cadetill** [jedi-gg/swgoh.gg.public#482]
to solve this issue

https://github.com/jedi-gg/swgoh.gg.public/issues/481

it is possible to add average arena rank into API response?

**Comment by cadetill** [comment]
how about this? Any implementation or do you have dismiss the proposal?

Thanks :-)

**Comment by scobenes** [comment]
This isn't most likely needed anymore since squad arena is no longer necessary.  And on top of that I think we would only provide latest and not an average via the API
