### ISSUE TITLE
User sync seems to be broken for ~30 days...

### ISSUE THREAD

**Issue by shodge12** [jedi-gg/swgoh.gg.public#483]
I have a user in my guild who is no longer syncing.  He reports that the swgoh.gg account is ok but the data from swgoh.gg does not refelct is past ~30days of growth.

User is MythicOne - 513-423-589

Can you pls check the account and see if something is up with it?

Thanks,
-Stan
SMaster3263827 315-565-565

**Comment by sanktanglia** [comment]
there is no user profile associated with this user and thus it doesnt sync regularly. if your guild mate logs into swgoh.gg and configures his profile to sync daily it will sync him. we are looking at the possibility of allowing ways for us to scan entire guilds even if they arent registered

**Comment by shodge12** [comment]
This is interesting because prior to ~30 days ago - it worked fine.  We will work with him again.

**Comment by shodge12** [comment]
Perhaps I am not understanding your comment as well.  The user has a profile:
https://swgoh.gg/p/513423589/
Are you saying the sync check box is not set?

Thanks,
-stan

**Comment by sanktanglia** [comment]
not only that there is no profile in our db pointing to that ally code, so not sure if he changed it or what happened but yes there is no profile associated with that ally code that has the check box set so it wont sync automatically
