### ISSUE TITLE
Fleet Arena Ranks Not Syncing

### ISSUE THREAD

**Issue by Vassago01** [jedi-gg/swgoh.gg.public#485]
My Fleet Arena Rank has not updated since Sunday, 1/13 and I noticed the Current Rank is inaccurate as well. I tried syncing and waiting past payout times, but it has not synced. 

My Profile: https://swgoh.gg/p/972146854/

Thank you for creating/supporting this site. It's very useful.

**Comment by sanktanglia** [comment]
yeah we missed a day or 2 of syncing when we switched over to some new backend tech, should be back to normal today or tomorrow
