### ISSUE TITLE
Missing zeta/omega report

### ISSUE THREAD

**Issue by Porthos72** [jedi-gg/swgoh.gg.public#487]
Now,  this topic isn't super urgent,  but whenever I got to the Zeta/omega report, it shows all characters have stats of 0. I don't know why its like that, I guess it could be a glitch, but I thought I might as well report it.

**Comment by sanktanglia** [comment]
yep thats on us, will have this fixed up soon, thx

**Comment by sanktanglia** [comment]
this is now fixed
