### ISSUE TITLE
Guild Squad Templates "An Error Has Occurred"

### ISSUE THREAD

**Issue by noctisperformance** [jedi-gg/swgoh.gg.public#488]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
Hi, 

I have created a bunch of team templates for my guild to follow but whenever we click into it, it says Error Occurred. I cleared my cache and reset everything to clean and it did not do anything. Not sure if this is a bug or something. ]

https://swgoh.gg/g/43070/dawnofenigma/squad-templates/

I appreciate any help as these templates are to assist those who are getting ready for HSTR! 

Best,
 Brandon

**Comment by nosirrahdrof** [comment]
I have had the same issue all day today as well (1/21/2019).    The issue persists across devices/browsers, and my guildmates are also experiencing this problem.

**Comment by AdmiralP** [comment]
Unfortunately we are seeing the same thing when attempting to view any of our guild's templates as well.

https://swgoh.gg/g/18742/shifting-veers/squad-templates/

![image](https://user-images.githubusercontent.com/33196541/51498514-68a85500-1d8c-11e9-9c69-2a9092638408.png)

**Comment by sanktanglia** [comment]
should be fixed up now, sorry about that
