### ISSUE TITLE
Cannot see updated guild squad details after refresh

### ISSUE THREAD

**Issue by TinTin-R** [jedi-gg/swgoh.gg.public#493]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Hi, I am an officer of the guild Dutch Poison (https://swgoh.gg/g/5039/dutch-poison/).
My swgoh.gg player account is https://swgoh.gg/p/662689726/
We cannot see updated guild squad details after refresh. Several members have obtained Jedi Training Rey in the last couple of days, but even after the current refresh on 27 Jan 2019 the data in the squad templates is not refreshing with this detail.

Squad template URL: https://swgoh.gg/g/5039/dutch-poison/squad-templates/61749/

**Comment by rvfmac** [comment]
Largely resolved now

**Comment by sanktanglia** [comment]
its possible the cache times are different between those 2 pages, can you add a cache breaker to it like https://swgoh.gg/g/5039/dutch-poison/squad-templates/61749/?t=whatever and see if it shows the correct data?

**Comment by rvfmac** [comment]
I tried that but the two are still visible there

**Comment by scobenes** [comment]
This is most likely an old bug
