### ISSUE TITLE
player api not working? 404 when using the player read api

### ISSUE THREAD

**Issue by aribas** [jedi-gg/swgoh.gg.public#494]

**Comment by aribas** [comment]
https://swgoh.gg/api/player/ally_code/
of course with the correct ally code returns a 404. I did not get the player api running. Do i miss something or is this wrongly used? How can i use the player api.

The other methods of the api are working (abilities, characters, and some others)

**Comment by TimKdba** [comment]
I'm getting the errors on the api as well.  Also, 504 and 503 errors on the site https://swgoh.gg/p/859768427/

**Comment by sanktanglia** [comment]
we are doing some infrasturcture maintenance, should be fixed up in an hour or so

**Comment by TimKdba** [comment]
Looks like it's back up, thanks for the info!
