### ISSUE TITLE
Galactic power differences arent matching.  2 players with same starred toons have 2different scores.

### ISSUE THREAD

**Issue by SANTAJEDI** [jedi-gg/swgoh.gg.public#495]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREc ADY BEEN CREATED
C

**Comment by sanktanglia** [comment]
Can I get a link to where you are seeing this issue?

**Comment by SANTAJEDI** [comment]
Hope those screen shots help. We both have everything starred but 2 toons.  And both if those are 5* each.


Sent from my Galaxy Tab® A
-------- Original message --------From: sanktanglia <notifications@github.com> Date: 1/29/19  1:59 PM  (GMT-05:00) To: "jedi-gg/swgoh.gg.public" <swgoh.gg.public@noreply.github.com> Cc: SANTAJEDI <Jgraves00965@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jedi-gg/swgoh.gg.public] Galactic power differences arent
  matching.  2 players with same starred toons have 2different scores. (#495) 
Can I get a link to where you are seeing this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jedi-gg/swgoh.gg.public","title":"jedi-gg/swgoh.gg.public","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jedi-gg/swgoh.gg.public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sanktanglia in #495: Can I get a link to where you are seeing this issue?"}],"action":{"name":"View Issue","url":"https://github.com/jedi-gg/swgoh.gg.public/issues/495#issuecomment-458663753"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jedi-gg/swgoh.gg.public/issues/495#issuecomment-458663753",
"url": "https://github.com/jedi-gg/swgoh.gg.public/issues/495#issuecomment-458663753",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sanktanglia** [comment]
I didnt get any screenshots, can i get the ally codes of the 2 people who are different?

**Comment by SANTAJEDI** [comment]
Im not a techie sorry.

662-433-916

984-861-517

**Comment by sanktanglia** [comment]
also, which unit were you seeing the differences on?

**Comment by SANTAJEDI** [comment]
The galactic power difference section.  The second column thats says stars.

**Comment by SANTAJEDI** [comment]
The galactic power difference one. Under the second column "stars"


Sent from my Galaxy Tab® A
-------- Original message --------From: sanktanglia <notifications@github.com> Date: 1/29/19  2:57 PM  (GMT-05:00) To: "jedi-gg/swgoh.gg.public" <swgoh.gg.public@noreply.github.com> Cc: SANTAJEDI <Jgraves00965@gmail.com>, Author <author@noreply.github.com> Subject: Re: [jedi-gg/swgoh.gg.public] Galactic power differences arent
  matching.  2 players with same starred toons have 2different scores. (#495) 
also, which unit were you seeing the differences on?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jedi-gg/swgoh.gg.public","title":"jedi-gg/swgoh.gg.public","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jedi-gg/swgoh.gg.public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sanktanglia in #495: also, which unit were you seeing the differences on?"}],"action":{"name":"View Issue","url":"https://github.com/jedi-gg/swgoh.gg.public/issues/495#issuecomment-458684631"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jedi-gg/swgoh.gg.public/issues/495#issuecomment-458684631",
"url": "https://github.com/jedi-gg/swgoh.gg.public/issues/495#issuecomment-458684631",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sanktanglia** [comment]
So weve tracked it down to a couple of things. First off those 2 accounts dont have the same stars on all characters, the carth has different number of stars between them. The other thing is that ship star gp is included in this calc, but ship star GP isnt 100% just from star levels(as noted on the ship pages). We are debating whether to include ships on this page, but as far as I can tell, theres no errors with the calcs

**Comment by SANTAJEDI** [comment]
Ok thanks
