### ISSUE TITLE
Guild Unit Search Broken

### ISSUE THREAD

**Issue by ijgeoffrey** [jedi-gg/swgoh.gg.public#496]
The Guild Unit Search feature appears to be broken. I tried to look up certain units in our TW opponent guild, here: https://swgoh.gg/g/13774/active-casuals/unit-search/

As soon as I select a toon, the whole search area disappears. Trying to type in the toon and hit Enter yields the same result.

Before: https://prnt.sc/mdwqhx
After: https://prnt.sc/mdwqra

**Comment by BlackV** [comment]
Futher to this

It works fine for me when searching for units the guild has

But if i select a unit the guild has 0 of (i.e. GL Kylo/Rey)  it breaks same the after screen shot above

**Comment by BlackV** [comment]
![swgohissues01](https://user-images.githubusercontent.com/8619546/81747298-f79a2d00-94fb-11ea-84b4-ed2e4e1df023.png)
![swgohissues02](https://user-images.githubusercontent.com/8619546/81747300-f8cb5a00-94fb-11ea-962b-20e33fdcf085.png)
![swgohissues03](https://user-images.githubusercontent.com/8619546/81747303-f9fc8700-94fb-11ea-92ee-cd75cbd0942a.png)

**Comment by scobenes** [comment]
This is most likely an old bug
