### ISSUE TITLE
Sith Raid Phase 3 bug

### ISSUE THREAD

**Issue by Ninjabagel** [jedi-gg/swgoh.gg.public#497]
Don't know if there was a recent update to the sith raid but i've gotten two new bugs in it, both during phase 3 of the raid. Last week during the run one of the lightsabers bugged out and was flying all over then became untargetable but was still alive, i could hit it with AOE and when i deselected Treya my characters would sometime hit it on auto till it was destroyed (this was near the end so she enraged and ended my run soon thereafter so i don't know if it would have continued when the lightsabers came back up) i haven't seen this bug since. Just today though I just got revan and went in with him and twice in a row now. after the first initial topple of Treya and damage, when she gets back up, i get 1 hit on the lightsabers and then it's as if it never finishes the attack. The animations stop but my abilities never show back up so i can't click any, I can change my target but when i click auto everyone still just sits there. The option to retreat is still greyed out as if i'm mid attack still so i can't retreat so my only option is to restart the client. I restarted once and went back in and got the same bug a second time. It is only happening when i go in with Revan, i tried a different team and the raid worked fine. I am on Android and my ally code is 916-867-462 if that is needed

**Comment by sanktanglia** [comment]
we cant help with support for the game, sorry
