### ISSUE TITLE
Guild members on site, but not in API

### ISSUE THREAD

**Issue by arbster** [jedi-gg/swgoh.gg.public#498]
https://swgoh.gg/g/4756/no-limit-gentlemdns-club/
https://swgoh.gg/api/guild/4756/

Two members of this guild joined 5 days ago, appear on the swgoh.gg website but don't appear in the API extract, linked above.  The two members are Larg and Rohania.  A third member, Arbster, joined on the same day and DOES appear in both places.

**Comment by sanktanglia** [comment]
this is because the cache of the api is different of the website, if you add a cache breaker to the api you will see the updated results https://swgoh.gg/api/guild/4756/?t
