### ISSUE TITLE
Some characters's pages redirect too many times, causing page to not load

### ISSUE THREAD

**Issue by AgentRG** [jedi-gg/swgoh.gg.public#499]
When visiting links to some of the characters, the links redirects too many times, eventually causing the page to fail loading. Happens on multiple browsers.

Some characters are Akbar, light side Bastila Shan and Fulcrum.

Link to Akbar https://swgoh.gg/characters/admiral-ackbar/
Screenshot https://i.imgur.com/eF2O52F.png

**Comment by scobenes** [comment]
This is most likely an old bug
