### ISSUE TITLE
Magmatrooper Gone?

### ISSUE THREAD

**Issue by kbisho12** [jedi-gg/swgoh.gg.public#500]
https://swgoh.gg/characters/magmatrooper/ is a dead link right now.... 

I haven't found any other pages that are gone, but I can't get to Magmatrooper by going in from the main unit selection screen or from a user->character->character data...

It pops the error: "There were too many redirections. Error Code: INET_E_REDIRECT_FAILED"

**Comment by sanktanglia** [comment]
yeah sorry we are tracking down a redirect bug, all fixed up now, thx for the report
