### ISSUE TITLE
Guild Members Showing on Roster still not in API after 5 days

### ISSUE THREAD

**Issue by KalSarkon** [jedi-gg/swgoh.gg.public#502]
This is the first of two issues with API's I will be posting. 

Our guild's API page does not reflect two members who rejoined the guild 4-5days ago.  Our guild API is:
[https://swgoh.gg/api/guild/9951/](url)

JayBoanerges and Bameiro Kull do not show up in the API.  They have showed up on the guilds regular page for several days now.  I know it has been 4-5 days since their liftetime raid tickets are showing 3000 and 2400 respectively. 

I am not sure whether the issue is the API is not updating at all, or if it is just not adding these members.

Thanks for looking into this.

**Comment by danpaulson** [comment]
Hey there,

We're aware that the guild API is currently hit or miss. This comes down to caching, and honestly a bigger problem that it's a massive load on our servers. I'm currently architecting how the guild API works to be a cascading caching system that will hopefully provide very up-to-date data as well as being much lower overhead for us, but I don't currently have an ETA on that.

**Comment by KalSarkon** [comment]
Thanks for the update.  I very much appreciate the service you provide here.
