### ISSUE TITLE
Same Mod showing on multiple characters

### ISSUE THREAD

**Issue by KalSarkon** [jedi-gg/swgoh.gg.public#503]
This is the second of two issues I am posting.

The same mod is showing up on multiple characters.  This is happening on both the website and in the player API file.  This mod, which is correctly shown on Darth Nihilus, is also showing on two other characters.  Here is a [filtered view of my mods from the website](https://swgoh.gg/p/798399449/mods/?slot_1=1&set_4=1&tier_3=1&stat2_5=1&stat2_42=1&stat2_49=1&stat2_55=1&sort=secondary_stat_49&sort_direction=desc) illustrating this:

![image](https://user-images.githubusercontent.com/33123458/52277382-9e1f7780-2922-11e9-86f2-8915f6e60b52.png)

Looking at the [player API](https://swgoh.gg/api/guild/9951/), I can confirm that this is the same mod, ID TUlrrjmkR6SPl0X4o8HNhg.  The API also shows it on all three characters.

There are about a dozen other mods in my portfolio where this is also happening.  I did some major mod shuffling last Friday, The issues seem to be related to mods I swapped between characters at that time.

**Comment by sanktanglia** [comment]
So we have fixed this issue up on your account for now, but let us know if you know of anyone else experiencing this or you experience it again, we are working on fixing it up across the board
