### ISSUE TITLE
Guild Unit search filter issues after second search

### ISSUE THREAD

**Issue by arctouch-raphaellupchinski** [jedi-gg/swgoh.gg.public#505]
Guild unit search is not bringing the full data after the second request.
When fetching unit data from our guild (https://swgoh.gg/g/27131/viciados-de-dagobrah/unit-search/) we can only get the appropriate data when the page loads. It correctly outputs the amount of toons or ships that match the star count.

If we change the unit name and re-do the search, it'll only list the first N toons available in the previous request.

For instance:
I search for 7* Holdo intially: 
![image](https://user-images.githubusercontent.com/36644047/52524760-f8ed0200-2c87-11e9-80e0-3ba851e1cc05.png)

Then search 7* Ezras:
![image](https://user-images.githubusercontent.com/36644047/52524770-0bffd200-2c88-11e9-892a-9cfd610293c8.png)

It brings 7 results too, even though we have many more Ezras than that.
A clean 7* Ezra search brings this:
![image](https://user-images.githubusercontent.com/36644047/52524790-3487cc00-2c88-11e9-844b-1f9ee45a3176.png)
(currently have 50 of him)

**Comment by sanktanglia** [comment]
thanks will look into this, we are working to rework alot of this page

**Comment by arctouch-raphaellupchinski** [comment]
This is by far the best feature of the site, I'm glad it's receiving some love :)

**Comment by arctouch-raphaellupchinski** [comment]
Also, I believe many guilds implement this by themselves, but I think that the page could have  a mode inside the guild to list the characters or ships it lacks the most.
Like showing a list of all toons you have less of X at 7* (could be X=5)
This would also be useful for TB, as we'd be able to, at a glance, identify if a platoon can be completed or not.

Just a suggestion, I'm sure it involves far too much calls to the API to get it all for all users, but could be a case of reverse searching by guild.

**Comment by scobenes** [comment]
This is most likely an old bug
