### ISSUE TITLE
Outdated shipments

### ISSUE THREAD

**Issue by Porthos72** [jedi-gg/swgoh.gg.public#506]
So today I looked at the shard shipments section of your website, but noticed that it appeared to be outdated. I noticed at least one character (young han) wasn't listed. I'm assuming it just needs to be updated, but I thought it was worth mentioning. Also, if you had the time, adding what ship blueprints or what gear can be acquired through shipments would be nice too, but those are just some ideas. Thx.

**Comment by scobenes** [comment]
Shipments are hard to get data from in game as we cannot see the full list always.  This data may be inaccurate or we may just get rid of it.
