### ISSUE TITLE
API: search guild don't return arena and fleet_arena data

### ISSUE THREAD

**Issue by cadetill** [jedi-gg/swgoh.gg.public#507]
Searching info about guilds I see that the structures of arena and fleet_arena from the players returns null
ex: https://swgoh.gg/api/guild/37003/

However, if I search info about 1 single player, the info of these structures is good informed
ex: https://swgoh.gg/api/player/471192528/

Thanks

**Comment by sanktanglia** [comment]
for the guild call you have to include ?include_arena=1 to get back arena results, we added this to improve server stability

**Comment by cadetill** [comment]
perfect, you need to update the documentation then :-)
