### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by MasterJoJoBinks** [jedi-gg/swgoh.gg.public#510]
My account no longer syncs at 6PM based timezone selected.  It appears to be syncing at 12:00 am UTC time every time.
https://swgoh.gg/p/675678798/

**Comment by sanktanglia** [comment]
we now get the sync time from the game backend, are you sure this is not the correct time for you?

**Comment by MasterJoJoBinks** [comment]
Yes, it is the correct time from a game standpoint.  I had a different time zone chosen so the sync would happen in the middle of the day where I could take better advantage of the sync.  If this is new norm, can you change the web page to reflect that?  The web page says: "Data is synced at 6pm in the selected timezone. DST is NOT observed."  I suppose it could say: "Data is synced at 6pm in the timezone provided by the game. DST is NOT observed. Time zone selected here has no effect on sync time"

**Comment by sanktanglia** [comment]
yeah sorry we are working on removing all of that from the site, i just recently pushed the change to sync based on the in game data recently as it took a lot of backend work to get done

**Comment by MasterJoJoBinks** [comment]
Well I say that ... it does force a new sync when the timezone is changed.  So that functionality needs to remain in place.

**Comment by MasterJoJoBinks** [comment]
I do appreciate the work you guys do, thank you!

**Comment by MasterJoJoBinks** [comment]
It would be great it that functionality could remain.  I use your guys site and data to import into a database that I use to manage my almost 1000 mods.  Changing a bunch of mods then getting the synced data from here allows me to change more mods without waiting for auto refresh.  Hence why I had it refreshing about 12:00 central time.  Again you guys have done great work!

**Comment by sanktanglia** [comment]
we are working on a premium program where with a small donation youd be able to sync much more often automatically, likely hourly. Stay tuned for updates and info on it

**Comment by MasterJoJoBinks** [comment]
That sounds good, I would be willing to donate.
