### ISSUE TITLE
Unit Search Data is very aged in compared to the guild refresh as of date

### ISSUE THREAD

**Issue by acidf-swgoh** [jedi-gg/swgoh.gg.public#511]
When using the unit search https://swgoh.gg/g/#/guild-name-here/unit-search/ the information shown for the guild as at the date in the top corner of the https://swgoh.gg/g/#/guild-name-here/ is not correct. The data is as of a date much before the last refresh. The data looks to be over a week old at this point.

Thank you for your time in resolving this issue.

**Comment by scobenes** [comment]
This is most likely an old bug
