### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by andinho91** [jedi-gg/swgoh.gg.public#512]
Hi.
I've been reading there is a few people with the same issue as me.
I recently tried changing my timezone to match ingame arenarank, however it will not change regardless of which timezone I pick.
This is the account in question:
https://swgoh.gg/p/798579845/
The actual timezone is GMT+5:30, but thats not an option on your site. So I'd like to put it back to GMT+6 instead.
Could you help me with this?
Thanks.

**Comment by sanktanglia** [comment]
yeah sorry i need to update the text on that page, we now sync based on your in game sync time, so we can support time zone changes and half hours.

**Comment by andinho91** [comment]
Hey.
Okey, so this will be fixed automatically in near future? Because right now the sync for arena rank os off, giving me wrong rankings.
Thanks for your time.

**Comment by scobenes** [comment]
This is most likely an old bug
