### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by Megastone77** [jedi-gg/swgoh.gg.public#513]
Hi, I have used your site since July 2016 it is fantastic. I changed my PO to 13.30 GMT when the time zone changes were first implemented and changed my sync to +5gmt so it recorded my time at 13.00 GMt, which is free , so I was in 1st. From the 7th February for some reason it started recording my PO time at 14.30gmt and no matter what time zone I change it to it always syncs at 14.30gmt. I mean ideally I would like it at 13.30 GMT when my actual PO is but is there a reason it started syncing 1.5 hours later than usual and is there a way I can fix it? Thx - This is my account - https://swgoh.gg/p/289983917/

**Comment by sanktanglia** [comment]
so we currently read your payout time from the game data now, so it should be syncing based on what your actual payout time is. ill some poking around to see why this might be off for you

**Comment by Megastone77** [comment]
That's great, thank you.

**Comment by Megastone77** [comment]
Thanks a lot the issue syncing 1 hour after PO in arena has been resolved for a few days now. Ships still sync an hour late though 😬

**Comment by scobenes** [comment]
This is most likely an old bug
