### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by BabyPalmer** [jedi-gg/swgoh.gg.public#514]
https://swgoh.gg/p/655938688/

i have a problem with the arena rank, always 1.
but stop to sync sometime ago.

thank you for your time 👍

**Comment by sanktanglia** [comment]
your issue has to do with your very unique payout time, which doesnt appear to be on the hour/30 minute mark. will think about how we can handle this going forward

**Comment by BabyPalmer** [comment]
https://www.timeanddate.com/time/time-zones-interesting.html

i can’t select the correct time, but i get the nearest, but why one continue some days and the other stop.
thank you for your fast reply.
kind regards

**Comment by sanktanglia** [comment]
we rolled out the new sync on different dates for fleet and regular sync, you wont be able to fix this by changing time zones on .gg, well have to update our code to handle people with your odd payout times

**Comment by nnovi** [comment]
https://swgoh.gg/p/318344397/

My payout is 15 minutes after what I have currently in swgoh.gg sync settings.

**Comment by nnovi** [comment]
Any update on update issue? My swgoh didn't update for last 10 days https://swgoh.gg/p/318344397/

**Comment by scobenes** [comment]
This is most likely an old bug
