### ISSUE TITLE
Sync is factoring in DST

### ISSUE THREAD

**Issue by Azraelrulez** [jedi-gg/swgoh.gg.public#515]
Hi, I've seen the sync issues others have posted in regards to sync time zone etc.. I'm from India (+5.30 GMT) and we don't observe DST at all. Since the site started sync based on in game data, I'm noticing all my syncs are at 7 PM IST. I'm in a EST guild and I noticed that all guild activities are also pushed an hour back compared to EDT, That's why I'm assuming something similar is happening here, that DST is somehow affecting the payout time. I've been scratching my head, changing time zones till I noticed you're taking the time zone from in game. My profile <https://swgoh.gg/p/865667248/>.

**Comment by sanktanglia** [comment]
hey, we need to update the language on the site, as we now sync based in the in game payout time

**Comment by scobenes** [comment]
This is most likely an old bug
