### ISSUE TITLE
Enhancement Request: Sort Squad Templates

### ISSUE THREAD

**Issue by AdmiralP** [jedi-gg/swgoh.gg.public#516]
I would like to request the ability to sort the guild's squad templates.

Since we have created a number of squads over time it would be helpful for our members to be able to sort these in alpha order. Better yet would be the ability to customize the order, but alpha sort would be great. That way we can use a naming convention to organize the templates and make it easier for our members to find them. In this particular case we have loaded a number of Heroic Sith squads and would like our team to be able to easily go in and find a team or teams dedicated to a specific phase.

Another sorting option might be to sort them by the category.

Thanks for the work you all put into this. It's an extremely beneficial tool.

**Comment by sanktanglia** [comment]
yep will def add this to my todo list

**Comment by AdmiralP** [comment]
Thanks for the quick response, and thanks again for the site!

**Comment by AdmiralP** [comment]
Sorry if it may have taken a while to get a thank you here as a family emergency has kept me away from my guild duties. I'm trying to play catch up there, and noticed that you deployed the filters for the squad templates. This is an enormous help, and I just wanted to give my thanks for the development. Again, thanks to everyone on your crew. This tool is amazing, and it really just keeps getting better.
