### ISSUE TITLE
Leader Abilities

### ISSUE THREAD

**Issue by Mezilok** [jedi-gg/swgoh.gg.public#517]
Under  "Star Wars Galaxy of Heroes Top Leader Abilities"
Seen here:
https://swgoh.gg/abilities/leader/?page=2

Darth Nihilus' Unique "Lord of Hunger" present being listed as a Leader Ability

**Comment by BabyPalmer** [comment]
yep, when the hability is shared with other used like leader, see others traya.

**Comment by scobenes** [comment]
This is most likely an old bug
