### ISSUE TITLE
Player API not Updating

### ISSUE THREAD

**Issue by KalSarkon** [jedi-gg/swgoh.gg.public#518]
Thought I would flag this.  I suspect this is similar to a [prior issue I posted](https://github.com/jedi-gg/swgoh.gg.public/issues/502) on Guild API a few weeks ago.  My [Player API](https://swgoh.gg/api/player/798399449/) has not updated for 4 days.  Today is the 25th and the API update date is:
         "last_updated": "2019-02-21T23:04:10.176337",

I really appreciate you all providing this service.  Should I just reset my expectation on API updates?

Thanks!

**Comment by sanktanglia** [comment]
nope, we have been making some tweaks to the cache timeouts for the api and other pages, and i just rolled that out, so the api should clear daily along with the other pages, should be fixed for you now

**Comment by KalSarkon** [comment]
Thanks!
