### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by ZiroG** [jedi-gg/swgoh.gg.public#519]
Several people in my guild, including myself, are experiencing "502 Bad Gateway" errors if the page we are trying to access loads partially.  Or a Error 502 Cloudflare error page if the page doesn't load at all.

Pages that have thrown this error include the main swgoh.gg page.
As well as individual player pages such as: https://swgoh.gg/p/356254621/

**Comment by sanktanglia** [comment]
yeah our servers get hit super hard around the start of TW from automated tools and we are working on improving the affect it has on the main site
