### ISSUE TITLE
Character information for User displaying incorrectly

### ISSUE THREAD

**Issue by ecdr** [jedi-gg/swgoh.gg.public#521]
If I look at the generic character information, it displays with multiple columns
of information.
e.g., 
https://swgoh.gg/characters/finn/
Shows a graphic on the left, a column of abilities in the middle, a column on the right with statistics.

However, if I look at the character information for one of my characters, e.g.,
https://swgoh.gg/p/862179542/characters/finn

It comes out as a linear list of links, then a list of pictures, then a few stats - all down the left hand side
with no formatting.

This is in Firefox 62.0 (64 bit) on Windows.  Same thing happens in Opera 57.0.3098.116 (again on Windows, no plugins, portable version).

I tried to include a screenshot - but it keeps saying something went wrong.

Same thing happens with the gear needed screen
https://swgoh.gg/p/862179542/gear-needed/

My Mods and Squads screens have the same problem.

**Comment by sanktanglia** [comment]
looks like you got cached css from a deploy earlier, it should be cleared now, thx for the report

**Comment by ecdr** [comment]
Is this just a temporary thing which will go away in a while?  That one character seems to work, but others don't.  
e.g.
https://swgoh.gg/p/862179542/characters/kylo-ren-unmasked
https://swgoh.gg/p/282498734/characters/plo-koon

I tried clearing my browser's cache (since you mentioned cache - even though it happened in another browser as well).  That did not seem to help.

**Comment by sanktanglia** [comment]
figured it out, sorry about that, had our secondary web server on and it wasnt updated with the newest css
