### ISSUE TITLE
Characters deleted are already here

### ISSUE THREAD

**Issue by Memoi** [jedi-gg/swgoh.gg.public#523]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

https://swgoh.gg/p/111748917/

Click on revan and you will see

**Comment by sanktanglia** [comment]
not sure what the issue is, can you give more detail?

**Comment by Memoi** [comment]
My account was ban and EA removed some characters, in swogh.gg I see the character before the ban. For example https://swgoh.gg/p/111748917/characters/jedi-knight-revan is always G12 but if you see on Arena Highest rank https://swgoh.gg/p/111748917/ Revan is not anymore G12.

My GP is also the same before the ban 4.8M but it's 4.6M now

**Comment by ndye** [comment]
Well, that is an edge case so not very important. You cheated you got banned so you don't get the nice stuff everyone else does.
