### ISSUE TITLE
Player API has not updated for 5 days

### ISSUE THREAD

**Issue by KalSarkon** [jedi-gg/swgoh.gg.public#526]
We've seen this [before](https://github.com/jedi-gg/swgoh.gg.public/issues/518), but it seems to have started back up again.  My api has not updated since March 11.

https://swgoh.gg/api/player/798399449/

Thanks for providing this service.

**Comment by sanktanglia** [comment]
I think i finally tracked this down, i cleared out the caches as well, let me know if you spot it again, thx for the update
