### ISSUE TITLE
Player profile arena sync has not synced on over 30 days

### ISSUE THREAD

**Issue by BlackV** [jedi-gg/swgoh.gg.public#527]
My arena rank has stopped syncing.

Time: New Zealand Standard Time (+12/+13)
Profile: https://swgoh.gg/p/472971433/

I have not changed my payout time (not changed anything actually) as per some of the other posts

profile is syncing correctly aside from that

**Comment by sanktanglia** [comment]
we should have this issue fixed up in a day or so, its due to how we swapped our prociessing to be based on payout and for some reason your payout time gets missed, will post in here when its fixed up

**Comment by Tpilott** [comment]
Hi, I have the same issue and payout time, will it resolve for everyone?

https://swgoh.gg/p/373141332/

**Comment by sanktanglia** [comment]
theres about 650 people with that payout and they will all get fixed, yes

**Comment by BlackV** [comment]
Thanks for your reply. I'll wait for the fix.

**Comment by cheekycutie** [comment]
Just jumping on this thread too as I've also been waiting months for this fix. Hope to see things sorted soon

**Comment by nnovi** [comment]
I asked on other task also few weeks ago. Can you fix my payout also?
https://swgoh.gg/p/318344397/

**Comment by sanktanglia** [comment]
just a heads up everyone with that same payout should be fixed, @nnovi yours is a diferent issue because you appear to have a :15 minute payout? if so we dont support those yet and even if we did wed still be 15 minutes off in syncing you

**Comment by hindsitedev** [comment]
@sanktanglia yes, it's 15 minutes offset. Even delaying sync (so can't understand, how 15 offset can be different with 0 or 30 minutes offset sync) is better that empty arena and only manual profile sync.

**Comment by nnovi** [comment]
@sanktanglia yes, it's 15 minutes offset. Even delaying sync (so can't understand, how 15 offset can be different with 0 or 30 minutes offset sync) is better that empty arena and only manual profile sync.

**Comment by BlackV** [comment]
I never updated this.
My issue is fixed, I guess outstanding is the 15 min offset issues

Thanks
