### ISSUE TITLE
Typo in guild unit search explanation text

### ISSUE THREAD

**Issue by cdbelyeu** [jedi-gg/swgoh.gg.public#528]
![image](https://user-images.githubusercontent.com/6653193/54568308-5158a300-499c-11e9-8ed0-8ba5dc954bda.png)

Sample url: https://swgoh.gg/g/1875/fights-like-a-girl/unit-search/

In explanation text there is a typo. "How dows it work?" should be "How does it work?"

**Comment by scobenes** [comment]
This is fixed thanks
