### ISSUE TITLE
Player ID can't be found

### ISSUE THREAD

**Issue by stillmiles** [jedi-gg/swgoh.gg.public#530]
I am new to the site but, it is all pretty self explanitory. I've tried everything to sync the game to my account, but it continues to say that the Player Id is not found... It isn't that confusing of a process, and I've tried all the necessary variations of O's and 0's. Is the sync portion of the site down?

**Comment by sanktanglia** [comment]
whast your ally code?

**Comment by stillmiles** [comment]
584-229-398

**Comment by sanktanglia** [comment]
ther was a problem with the service that did our manual sync, give it a try now

**Comment by stillmiles** [comment]
it worked man thank you
