### ISSUE TITLE
Mod API has mods on wrong characters

### ISSUE THREAD

**Issue by KalSarkon** [jedi-gg/swgoh.gg.public#532]
Sorry to keep bugging you, but....

The mod API for my character has the mods on the wrong characters.  It seems pretty pervasive.  Every toon I've looked at has them messed up.  One example:

The [web page for my Palpatine](https://swgoh.gg/p/798399449/characters/emperor-palpatine) shows the correct mods that are actually on him.   But the [API ](https://swgoh.gg/api/players/798399449/mods/)shows a completely different set.  I did a little snooping and it looks like the mods the API shows on Palp are actually the ones on [Nihilus](https://swgoh.gg/p/798399449/characters/darth-nihilus).  And the API isn't showing any mods on Nihilus at all.

**Comment by sanktanglia** [comment]
its just a caching issue, the caches on the web and the caches on the api are on different timers so they could def be off from each other. You can add a cache breaker to the end of either url(?whatever) and youll get an uncached copy so you can verify
