### ISSUE TITLE
500 server error on profile

### ISSUE THREAD

**Issue by khmcintyre2013** [jedi-gg/swgoh.gg.public#533]
https://swgoh.gg/u/scotsmanjr/
Not syncing and not loading

**Comment by khmcintyre2013** [comment]
https://swgoh.gg/u/975621232/

**Comment by khmcintyre2013** [comment]
Can anyone help with this?

**Comment by sanktanglia** [comment]
sorry for the delay, will look into it

**Comment by khmcintyre2013** [comment]
Any updates?  Thanks in advance.

**Comment by sanktanglia** [comment]
still working on it sorry, will post when ive got an update, hope to have time soon

**Comment by sanktanglia** [comment]
Should be all fixed up now, sorry about that!

**Comment by khmcintyre2013** [comment]
Great.  Looks good.  Thank you.
