### ISSUE TITLE
Internal Guild API Pull - Last Updated 3/26

### ISSUE THREAD

**Issue by jafoster78** [jedi-gg/swgoh.gg.public#534]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Doing a pull via json and converting into a C# model. From there I move into SQL

https://swgoh.gg/api/internal/maedalore-rrime/guild/58965/

No errors on the pull, No errors on SQL. What I am running into however is that the API data doesn't appear to actually be updating for the guild. I can see all the members on the site. I wait for the next TW to start (the previous one before today's) and the site gets very buggy. I pull data on another guild, get data updated for that day. I pull data on mine, still 3/26. So I wait. No Change. Today another TW. Site gets bogged down. I wait. I can get into data again on the site. I see rosters. I see update times. I pull guild data. Same date. 3/26. 

Here is the C# for the pull. 

            string json = "";
            using (WebClient wc = new WebClient())
            {
                json = wc.DownloadString("http://swgoh.gg/api/internal/maedalore-rrime/guild/58965/");
                
            }

Is there something I am missing?

**Comment by sanktanglia** [comment]
the correct url for the guild api is https://swgoh.gg/api/guild/58965/, if I go there im seeing it update properly, ill double check the guild api cache clearing to be sure though
