### ISSUE TITLE
Loading guild squad template doesn't work

### ISSUE THREAD

**Issue by clemus45** [jedi-gg/swgoh.gg.public#537]
![image](https://user-images.githubusercontent.com/10583114/57380014-5372fd00-71a8-11e9-9c9d-ebd8239725f6.png)

**Comment by sanktanglia** [comment]
is it still having errors? I was able to load it successfully for my guild and I seee the guild api call working for your guild as well, we had some issues yestertday causing problems, sorry about that

**Comment by clemus45** [comment]
It works today.
