### ISSUE TITLE
HTTP-403 when trying to download JSON file in python

### ISSUE THREAD

**Issue by DaiRenJinn** [jedi-gg/swgoh.gg.public#542]
Tried to download the JSON files from swgoh.gg/api in python:
------
from urllib.request import urlopen
link = "https://swgoh.gg/api/characters/"
f    = urlopen(link)
doc  = f.read()
print(doc)
------
Request errors out tho:
urllib.error.HTTPError: HTTP Error 403: Forbidden

Doing it in curl work
$ curl https://swgoh.gg/api/characters/
   <- Work just fine

Is there a special header I have to pass in the python request?

**Comment by sanktanglia** [comment]
maybe try specifying json explicitly?
https://swgoh.gg/api/characters/?format=json

**Comment by DaiRenJinn** [comment]
Found my 'missing link' trolling through the messages out blog post....
I was missing an HTTP header:

r = requests.get('https://swgoh.gg/api/characters/',headers={'x-api-identifier':'<my key>'})

That works just fine :-)
