### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by Porthos72** [jedi-gg/swgoh.gg.public#543]
Hi, today I went on to the website, and it said I had to sync my collection. It logged me in, but kep5 making me re sync my account. I don't know if this is a bug or what, but it is a little annoying

**Comment by sanktanglia** [comment]
yep we upgraded some of our internal ibraries and are tweaking some things to fix it up soon, shouldnt be too much longer, thx for the report

**Comment by danpaulson** [comment]
This _should_ be resolved now.
