### ISSUE TITLE
Trigger Sync

### ISSUE THREAD

**Issue by ChildishForces** [jedi-gg/swgoh.gg.public#544]
Hey guys,

HUGE fan of your work, this is an invaluable tool that has allowed me to build some really cool stuff for my guild. In order to ensure total data coverage I was over the moon when I discovered Guildmaster Sync, $10 is a minuscule fee measured against the utility it provides and so bought it immediately. Since I did that I noticed that the API documentation features a method to trigger a sync. It would be absolutely optimal if I could use this endpoint to ensure 50/50 profiles before I ETL the data into my own DB for our app. So far I can't figure out how to make it work, and noticed there was a couple of other small issues in the API. 

My questions are:
- Are there any plans to review the route structure of the API?
- Is there currently a way to trigger a sync on my guild with a HTTP request?

Thanks again!

Chris

**Comment by sanktanglia** [comment]
yeah so we have the ability for you to update both your guild and player via the api.
You can post to 
https://swgoh.gg/api/players/975621232/trigger-sync/
https://swgoh.gg/api/guilds/34442/trigger-sync/

and make sure to include the header x-api-identifier and set it to your api id on https://swgoh.gg/settings/
It will consume a player or guild refresh token for your account though. As for your first question, atm we dont have any plans to change up much of the api in order to avoid issues with others(and ourselves) consuming it

**Comment by ChildishForces** [comment]
Hey, thanks for the quick reply! I seem to be having some issues getting this working. Regardless of whether or not I have the x-api-identifier set it seems to be responding with status 405 and the following body:

```
{
    "detail": "Method \"GET\" not allowed."
}
```

This is the case regardless of the HTTP verb I use. (POST is what the API says, and what I primarily tried, despite what the error says)

**Comment by sanktanglia** [comment]
what url are you using? make sure you are using /players,
https://swgoh.gg/api/players/442772691/trigger-sync/ is what i just tried and it worked fine for me

**Comment by ChildishForces** [comment]
I'm attempting to trigger a guild sync as a large swath of my guild members do not use swgoh.gg (to their loss) and this will ensure total coverage of data. Let me paste my request for you here:

```
POST /api/guilds/10194/trigger-sync/ HTTP/1.1
Host: swgoh.gg
x-api-identifier: ce777d7c-8cdb...
Accept: */*
Cache-Control: no-cache
accept-encoding: gzip, deflate
referer: http://swgoh.gg/api/guilds/10194/trigger-sync/
Connection: keep-alive
cache-control: no-cache
```

**Comment by sanktanglia** [comment]
hmm, i was able to post to that just fine. make sure you have spare guild refresh tokens and you are sending to https

**Comment by ChildishForces** [comment]
Ahaaaa! It was the protocol! Thank you very much. Perhaps there is some kind of proxy that transforms all requests to HTTP to a GET verb? Anyway, that's it working now! 👍
