### ISSUE TITLE
Receiving 402s on Player read

### ISSUE THREAD

**Issue by ChildishForces** [jedi-gg/swgoh.gg.public#547]
Hi guys, as of today I started receiving 402 Payment Required on all player reads from the API.

**Comment by sanktanglia** [comment]
this means you are requesting the player api too fast and you need to slow down. What is the use case of your app and how fast are you requesting data?

**Comment by ChildishForces** [comment]
It's making requests for each player in the guild, as the guild read is not as comprehensive as the individual player response. What is the timeout until the ratelimit is lifted?

**Comment by ChildishForces** [comment]
To be clear, this should only be performed once a day, but I'm developing a feature at the moment that means I've had to call it more often than usual.

**Comment by ChildishForces** [comment]
It wouldn't be necessary if the guild read response could include individual players associated arena and fleet arena objects.
