### ISSUE TITLE
Confusing Request Docs

### ISSUE THREAD

**Issue by ChildishForces** [jedi-gg/swgoh.gg.public#548]
Hey again guys,

Sorry, I feel like I'm never done adding tickets, I was wondering if there's some trick I am missing with a few methods:

- Character Read - the ID mentioned in the docs appears to refer to some arbitrary number (the property "pk") that doesn't seem to be referenced anywhere else in the data.
- Ability Read - Again, using the "base_id" property doesn't return anything and I can't see any other property that works. I am also looking to be able to read ability descriptions from the API, data which exists as it's available on the main site (perhaps it's available under ability read but not sure, haven't successfully called it.)

Cheers, and sorry, again!

**Comment by ChildishForces** [comment]
Any word on this guys? Can you at least confirm if it's a bug?

**Comment by scobenes** [comment]
Sorry about not getting back to you, but for anyone else searching, the API docs are sort of informal and automagically generated.  The intention for characters and abilities is for someone to get the full lists from https://swgoh.gg/api/characters/ and https://swgoh.gg/api/abilities/ and use in memory logic to stitch things together.  Making individual requests for each one I do not believe will ever be well supported
