### ISSUE TITLE
'My ships' page shows invalid ship stats

### ISSUE THREAD

**Issue by azgo** [jedi-gg/swgoh.gg.public#549]
Hi,
The 'My ships' page right stat box is filled with seemingly basic values.
E.g. https://swgoh.gg/p/733577424/ships/tie-silencer where it shows low HP, 0 protection, 0 potency, low speed, etc
The total power shown is close but not in sync with mine (54669 vs 55284 ingame).
0 prot or potency is clearly invalid, but e.g. my ship has 99999 HP vs the 24354 shown, 196 speed vs 137 shown.

The invalid values are consitetntly invalid of all my ships' stat pages.

Brgds,

**Comment by sanktanglia** [comment]
yeah we are aware of this bug, we should have it fixed up this weekend, thx for the report
