### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by darcybowen** [jedi-gg/swgoh.gg.public#550]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
There seems to be a sync issue for the guild I'm in https://swgoh.gg/g/8471/allince-dgobah/
TheCharmingNavigator left the guild about 3 weeks ago and is still showing up on the guild list. The list has 50 showing up including the one is no longer in the guild. We currently have 50 actually in the guild so one is missing in addition to the one that shouldn't be there any more.

**Comment by sanktanglia** [comment]
thats super weird, not sure why the charming navigator wasnt syncing but hes removed now

**Comment by darcybowen** [comment]
Thanks!
