### ISSUE TITLE
Please delete my Account

### ISSUE THREAD

**Issue by Baldsch** [jedi-gg/swgoh.gg.public#553]
Dear Sir or Madame,

I am unable to find a way to delete my account/my profile. 
I am not playing anymore and i want to erase it. Would you be so kind an delete the Profil?

https://swgoh.gg/p/744599252/
it is named also baldsch.

Thank you very much in advance.
Yours Sebastian

**Comment by scobenes** [comment]
If anyone needs to delete an account there is a button in your profile settings to do so. https://swgoh.gg/settings/profile/
