### ISSUE TITLE
Ship Skills showing up in Character skills

### ISSUE THREAD

**Issue by JoeyJ0eJ0e** [jedi-gg/swgoh.gg.public#554]
Hello,

Several of my characters that are crew members have their ship skills in their character skills as level 1. When you go to the ship they are a crew member of, the skill is higher than 1. I've included pictures of Darth Vader, as an example. 

![vader](https://user-images.githubusercontent.com/52294208/60287888-3f0dcf80-98d0-11e9-975b-185fcd2ea955.JPG)
![vader 1](https://user-images.githubusercontent.com/52294208/60287929-55b42680-98d0-11e9-94ba-a5142cb88ccd.JPG)

https://swgoh.gg/p/611788771/ships/tie-advanced-x1
https://swgoh.gg/p/611788771/characters/darth-vader

**Comment by scobenes** [comment]
This is definitely an old bug
