### ISSUE TITLE
top-characters is not being updated

### ISSUE THREAD

**Issue by SwedeBull** [jedi-gg/swgoh.gg.public#555]
How often does the pages update?  Or is it "live" data from player syncs?

**Comment by shaizew** [comment]
Note my malak (player Vic Osena) based on today’s stats should be listed in top 5 for armor but I’m not shown.

**Comment by scoot1585** [comment]
sorry about that, it was missing TTL (time-to-live) values for the pages, so they weren't being uncached as much as they should.  I added rules for Top Players/Top Characters/g13 player data that should update every hour.  Thanks for the heads up
