### ISSUE TITLE
Zeta % reporting for some characters incorrect (Malak and JKR for example)

### ISSUE THREAD

**Issue by MisterPete** [jedi-gg/swgoh.gg.public#556]
I see some almost certainly incorrect zeta reporting.  Take a look at the zetas for Malak and Jedi 
Knight Revan (and possibly other characters, but these stood out)

https://swgoh.gg/stats/ability-report/?sort=percent_of_unit_gear&page=2

Darth Malak Gnawing Terror: 97,21% of all Malak, 73.09% of G11+ Malak
Darth Malak Jaws of Life: 98.50% of all Malak, 66.81% of G11+ Malak
Jedi Knight Revan Direct Focus: 94.30% of all JKR, 65.51% of G11+ JKR
Jedi Knight Revan Hero: 96.65% of all JKR, 60.51% of G11+ JKR
Jedi Knight Revan General: 98.10% of all JKR, 51.11% of G11+ JKR

These statistics must be swapped or in some other way incorrect?

In pretty much all other cases the percentage for good zetas on good characters are higher for G11+.  And I can't imagine that only around half of the Jedi Knight Revan G11+ have the three zetas, that's gotta be wrong.  If you swap the "% of all" with the "% of G11+" then it looks plausible.

-MisterPete

**Comment by MisterPete** [comment]
Darth Revan also seems to have these numbers backwards on that page.

**Comment by scobenes** [comment]
This is most likely an old bug
