### ISSUE TITLE
Player ID not found

### ISSUE THREAD

**Issue by ZiroG** [jedi-gg/swgoh.gg.public#558]
Hi,

I'm trying to help a guild member with their swgoh.gg account constantly giving a Player ID not found error when they try to enable syncing.  Ally code is 426-241-831.

We've tried using the Player ID lookup tool and trying the resulting value.  We've tried every variation of characters where there might be some doubt (zero vs O for example), and every attempt returns the same error message.  Any help you could provide would be appreciated.

**Comment by sanktanglia** [comment]
https://swgoh.gg/p/426241831/ I was able to sync your account, your player id is 
-IzfocOWT7qAbSm7YBEOFg

**Comment by ZiroG** [comment]
That's weird, that's the exact ID we were trying and kept getting the error message

**Comment by ZiroG** [comment]
The quick response is much appreciated.  Thank you!
