### ISSUE TITLE
TB Platoons

### ISSUE THREAD

**Issue by jhm2568** [jedi-gg/swgoh.gg.public#559]
Unable to view/navigate to the TB Platoons data as it always causes a redirect to login.

Sample URL: https://swgoh.gg/g/22944/house-crimson-nova/tb/ls/1/
Redirects to https://swgoh.gg/accounts/login/?next=/g/22944/house-crimson-nova/tb/ls/1/

Same happens with Geonosian TB URL
https://swgoh.gg/g/22944/house-crimson-nova/tb/ds-genosian/2/

**Comment by sanktanglia** [comment]
Sorry about that, fixed up now

**Comment by jhm2568** [comment]
Thank you!
