### ISSUE TITLE
Refreshed profile, show's I've used my daily refresh but data not updated.

### ISSUE THREAD

**Issue by MandalorianMercenary** [jedi-gg/swgoh.gg.public#563]

**Comment by MandalorianMercenary** [comment]
https://swgoh.gg/p/131761381/

**Comment by scoot1585** [comment]
Hey sorry, the services for interacting with the CG player data is down at the moment and we aren't able to bring it back up until tomorrow.  Sorry for the inconvenience and we are working to make this better for the future.
