### ISSUE TITLE
PlayerID is not found and Lookup Service is Down

### ISSUE THREAD

**Issue by TheLastSnowman** [jedi-gg/swgoh.gg.public#564]
Getting the Player ID not found. Have tried every combination of my ID that I and others in my guild can think of. Also, the lookup service says it's down or gives me an "Internal Server Error" every time I try to use it.

swgoh.gg Username:
TheLastSnowman (User # 351276)

Ally Code: 136-696-459
ID: 1YKI439rSv09S4ZWk536DA 

I have also tried:
1YKI439rSvO9S4ZWk536DA
1YKl439rSv09S4ZWk536DA
1YKl439rSvO9S4ZWk536DA
1YK|439rSv09S4ZWk536DA
1YK|439rSvO9S4ZWk536DA

**Comment by scoot1585** [comment]
Hey sorry, the services for interacting with the CG player data is down at the moment and we aren't able to bring it back up until tomorrow.  Sorry for the inconvenience and we are working to make this better for the future.

**Comment by TheLastSnowman** [comment]
Not sure what time you were hoping to have it back up by but now just getting 502 bad gateway error on the sync and 500 internal server error on the player ID lookup

**Comment by sanktanglia** [comment]
Will be a few more hours still, stuck in traffic atm

**Comment by sanktanglia** [comment]
should be all fixed now
