### ISSUE TITLE
Luminara Unduli - Master Healer's Blessing mechanics

### ISSUE THREAD

**Issue by fmseixas** [jedi-gg/swgoh.gg.public#565]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Luminara Unduli Master Healer's Blessing mechanics have items from GK leader ability

https://swgoh.gg/characters/luminara-unduli/ability/master-healers-blessing

**Comment by scobenes** [comment]
This is most likely an old bug
