### ISSUE TITLE
CT-5555 "Fives" Uniques are named the same in player's character screen

### ISSUE THREAD

**Issue by VReaperV** [jedi-gg/swgoh.gg.public#570]
Pages for specific player Fives have both of his Uniques named "Tactical Awareness" (see, for example, [here](https://swgoh.gg/p/517273547/characters/ct-5555-fives)).

![Screenshot_2019-08-25-18-51-19-140_com android chrome](https://user-images.githubusercontent.com/10687142/63652506-85b16600-c769-11e9-9623-a9b695158079.png)

**Comment by SnakesOnAPlane** [comment]
I’m also missing his Tactical Awareness zeta on my account. It doesn’t happen for everyone (some show both zetas).

**Comment by scobenes** [comment]
This is most likely an old bug with ship skills

**Comment by SnakesOnAPlane** [comment]
Thx
