### ISSUE TITLE
API Display Ships Skills on Characters

### ISSUE THREAD

**Issue by psytor** [jedi-gg/swgoh.gg.public#572]
As described in the subject.

When using the player API https://swgoh.gg/api/player/"allycode"

The ships skills are displayed in the Characters Skills.

For example Jedi Consular has 4 skills instead of 3 and one of them is his specialskill_JEDISTARFIGHTERCONSULAR02.

**Comment by psytor** [comment]
Just to confirm, the Guild API seems working properly as I made the test to make sure and the Characters don't seem to have the Ship Skills

**Comment by scobenes** [comment]
This is most likely an old bug
