### ISSUE TITLE
Grand Arena battle frozen

### ISSUE THREAD

**Issue by vacsek** [jedi-gg/swgoh.gg.public#574]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
Dear All,
While I was in Grand Arena Championship battle, with the Triumvirate team against Ewoks. After some attacks the game frozen. So I lost.
Can you check and solve it?
Regards,
Vacsek

**Comment by scobenes** [comment]
We are not affiliated with CG or EA and can't do anything about ingame issues.
