### ISSUE TITLE
Punch It! is showing as a character skill for Chewbacca

### ISSUE THREAD

**Issue by aeckerson97** [jedi-gg/swgoh.gg.public#575]
On my character page for Chewbacca it is showing Punch It! as a character skill. Punch It is one of the skills for Hans Millennium Falcon. Link to character page https://swgoh.gg/p/188382585/characters/chewbacca
![swgohgg chewie skills](https://user-images.githubusercontent.com/54901668/64266238-e6733800-cef9-11e9-816c-c77b9f85acfe.png)

**Comment by scobenes** [comment]
This is most likely an old bug related to ship abilities
