### ISSUE TITLE
my api works the web not updated

### ISSUE THREAD

**Issue by BabyPalmer** [jedi-gg/swgoh.gg.public#577]
Hello,
the api I thing up to date well (last_updated":"2019-09-07T12:23:26.157240)
https://swgoh.gg/api/player/655938688/
but on the web no
https://swgoh.gg/p/655938688/

that is for all, arena rank, characters, ships.
only when I manually sync, update on the web, but doesn’t write on arenas.
my big problem is for the auto sync for the guild, I always show less than I have.

thank you in advanced.

**Comment by sanktanglia** [comment]
the api and the website are on different cache timers, depending on when they were last hit. To keep the website running well we have to cache results. If you need to get a "more live" result, you can add a cache breaker to the url(like https://swgoh.gg/p/655938688/?whatever) but thta will still only get what is current in our db
