### ISSUE TITLE
Ads attempted to install Malware

### ISSUE THREAD

**Issue by htd42** [jedi-gg/swgoh.gg.public#581]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
I fully understand that advertising is vital for the great free service you provide. However, today and last friday I was immediately redirected to a site that claimed my Mac was out of date and advised me to install a supposed fix. Since I was using an iPad, I only browse in private mode and I had no other tab open than swgoh.gg at the time I am worried that one of the ads has triggered this unwanted behavior.

**Comment by scobenes** [comment]
Appreciate the report but we've changed ad providers since you created this.
