### ISSUE TITLE
Malicious Ad Popup and Browser Redirection

### ISSUE THREAD

**Issue by claymoore229** [jedi-gg/swgoh.gg.public#583]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

One of your ad providers is serving malicious ads that redirect to a scam site.  If I leave the site open my page is hijacked to a scam site and this ad pop-up appears. 
![SWGOH-gg-2019-11-06](https://user-images.githubusercontent.com/57451848/68316318-4071b480-0087-11ea-9950-61c295ff88a6.jpg)

https://imgur.com/a/hVEYqt7

Here is the scam site (dashes added to break the the link)
http://happy-luckyparkclub-com/bonus/com-us-cc-s10-iph11-cdn/lp3.php?c=4fzfkk7xz4vz0&k=12c4e32e108430fea83e514a81b2a77e&country_code=US&carrier=-&country_name=United%20States&region=Florida&city=Palm%20Harbor&isp=BRIGHT%20HOUSE%20NETWORKS,%20LLC&lang=en&os=Windows%2010&osv=&browser=Chrome&browserv=78&brand=Desktop&model=Desktop&marketing_name=Desktop&tablet=4&rheight=768&rwidth=768

**Comment by claymoore229** [comment]
More scam ads from LuckyParkClub.  Broken English, Walmart is more than 15 years old.  Please report this to your ad service or find a more reputable ad service.
![SWGOH-gg-2019-11-08](https://user-images.githubusercontent.com/57451848/68487909-fb2dbe00-0211-11ea-85ca-f623bc923a00.jpg)

**Comment by danpaulson** [comment]
Thank you, this is helpful. These are obviously not intended or wanted, and we're investigating with our ad provider.
