### ISSUE TITLE
Mk 5 Athakam Medpac missing characters

### ISSUE THREAD

**Issue by tdm00** [jedi-gg/swgoh.gg.public#586]
The [Mk 5 Athakam Medpac page](https://swgoh.gg/db/gear/130/mk-5-athakam-medpac/) is missing the following characters that use this item at G11

- [ ] Plo Koon
- [ ] Juhani
- [ ] Qui-Gon Jinn

[Image](https://cl.ly/1dd440bf665e)

**Comment by scobenes** [comment]
That page does not show units if they need it as an ingredient for a different piece.  Each of those people need this at g11 https://swgoh.gg/db/gear/137/mk-8-loronar-power-cell/
