### ISSUE TITLE
Link in README (https://updates.swgoh.gg) not working

### ISSUE THREAD

**Issue by markadamdouglass** [jedi-gg/swgoh.gg.public#588]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Link in README (https://updates.swgoh.gg) not working.

I was unsure if you were aware, so you could either get it working, or remove the link.

**Comment by scobenes** [comment]
I am not aware of this subdomain and is no longer active in our stack

**Comment by ollily** [comment]
Hi, I created a pull request #741 to have the readme file updated.

**Comment by scobenes** [comment]
Appreciate the PR, there is a lot outdated on that readme, but it is probably good to get rid of that link.
