### ISSUE TITLE
Guild Unit Search guild member link should go to unit

### ISSUE THREAD

**Issue by NducTiOnomBi** [jedi-gg/swgoh.gg.public#589]
When I search a unit in a guild and I click on the guild member with that unit, the link should take me to the unit of the guild member, and not just to the profile of the guild member. 

It should behave this way because the user is there to look at specific units and not guild members. 

This would simplify navigation as well, because if the user goes to the guild member unit, and they wanted to look at the guild member, it actually easier to do this from the guild member unit page, than it is in the current form to find the unit in the guild members collection.

**Comment by scobenes** [comment]
We updated this so that it now goes to unit
