### ISSUE TITLE
I don't want my GAC history public. Pls delete my account.

### ISSUE THREAD

**Issue by dontpostmystratbro** [jedi-gg/swgoh.gg.public#590]
Please delete my swgoh.gg account.  Publishing GAC history with no option to make private gives an unfair disadvantage to those players that don't know their battle history is being published.  If it can't be accessed in game, it shouldn't be accessible by external resources.

https://swgoh.gg/u/de-mo-jsa/

**Comment by danpaulson** [comment]
We can delete your SWGOH.GG profile, but your game profile (and GAC History) will remain on the site. This data is not exclusive to us, and is available to Discord bots and other sites as well.

**Comment by dontpostmystratbro** [comment]
How will it remain on the site if my profile is deleted?  Also, do you know who at CG is managing the release of this player data?  I have some concerns about the precedent it is setting.

**Comment by mksun00** [comment]
I am in agreement with the original poster of this thread. I am fine if there were a privacy setting, which is now disabled. I am fine if others can view what i used on their own profiles after i used it. To have it up permanently, nah...

Please also delete my swgoh.gg account: https://swgoh.gg/p/616475462/

**Comment by zhil-a** [comment]
Please delete my swgoh.gg acc
Gac info and tactikal, privat  !
https://swgoh.gg/p/115357357/

**Comment by dontpostmystratbro** [comment]
The more I'm discovering about this the more I am leaning towards just quitting the game.  This isn't a .gg thing.  CG is making this data public.  Soon someone will create a bot that analyzes GAC history and gives you a likely probability of what your opponents def will be (and of course your opponent will know your habits too).  CG might as well burn down the office and collect the insurance money...

**Comment by danpaulson** [comment]
I am working on a feature for self-serve account deletions. As noted, player profiles with game data will still be live (along with GAC History), but your personal information will be removed. I will update this thread when that ships.

**Comment by danpaulson** [comment]
You are now able to self-serve account deletion on the site.

https://swgoh.gg/settings/delete/
