### ISSUE TITLE
My account is synced but i keep getting a 404 error

### ISSUE THREAD

**Issue by xKhaoticx** [jedi-gg/swgoh.gg.public#591]

**Comment by 513Metallicus** [comment]
I am having the same issue as are many of my guild mates.  The link to my profile is https://swgoh.gg/p/313447983/.  Also, I am a Patreon member.  Not sure if that had something to do with the issue.

**Comment by xKhaoticx** [comment]
I deleted my swgog.gg account and created it again. When i went to sync again i kept getting a bad gateway error.

**Comment by 513Metallicus** [comment]
This issue is affecting many of my guild.  Some profiles are accessible, but many are not.  Is it only affecting Patreons?

**Comment by xKhaoticx** [comment]
Im not a patreon. I was wondering if i was having issues because im not one but i guess not

**Comment by 513Metallicus** [comment]
It may be related to this... https://www.reddit.com/r/SWGalaxyOfHeroes/comments/e97di0/guilds_growing_56_million_gp_overnight/?utm_medium=android_app&utm_source=share

**Comment by djrubin11** [comment]
I am also having this issue. At first I don't see a way of accessing my profile. Then I go to sync and settings and I see my profile URL. When I go to it I can see my team but then if I do to any of the profile sections like GAC History I get a 404 error.

**Comment by ModemMisuser** [comment]
Same deal.  I'm logged in, can go to "Settings and Sync" and everything looks fine.  If I click on "sync collection" along the top, I get the "hey you need to make an account or login" in order to sync.

And my profile's 404'ed too - https://swgoh.gg/u/vendraen/

**Comment by sanktanglia** [comment]
we had major db issues last night, will take most of the day to restore the missing data
