### ISSUE TITLE
Missing characters and zetas section problem

### ISSUE THREAD

**Issue by Guill118** [jedi-gg/swgoh.gg.public#593]
I seem to be missing a bunch of characters on my account. Ally code 932325566. My arena team is apparently missing Darth Revan and Bastila Shan Fallen, and I know that they aren't the only two missing from the characters section (I searched for my Nightsister Spirit and it wasn't there).

Not sure if it's directly related, but the "My Zetas" section seems to be totally broken, giving an Error 500 message.

![Screenshot_20191211-115752_Chrome](https://user-images.githubusercontent.com/57004099/70643321-c1841480-1c0e-11ea-89f7-1198171fea24.jpg)

**Comment by sanktanglia** [comment]
we had major db issues last night, will take most of the day to restore the missing data
