### ISSUE TITLE
Galactic War Report Podcast Appearance by @danpaulson

### ISSUE THREAD

**Issue by mol-gugek** [jedi-gg/swgoh.gg.public#596]
Not an issue but a definite hat tip to @danpaulson for showing up on the [Galactic War Report Podcast](https://radiofreetatooine.com/galactic-war-report-episode-182-dishing-on-data-with-dan/) he talked a bit with the host about the GAC feature, some of the collaboration with Capital Games, and some of the thinking behind the implementation.

Many thanks for addressing some a lot of the concerns there and showing that the homework is being done. I hope the feature can get polished a bit more. And finally many thanks to the entire swgoh.gg team for supporting the Galaxy of Heroes community for all these years.

![200w_d](https://user-images.githubusercontent.com/22840539/70850823-94c53c80-1e5c-11ea-92a4-a86cc65ed665.gif)

**Comment by danpaulson** [comment]
Appreciate the kind words! I’d love to do more pods like that in the future, though listening back I’ll certainly need to invest in a better sound setup. The technical part of what we do could potentially be interesting to a certain audience, but perhaps sleep inducing to the wider folks.

Anyways, again thanks and glad you enjoyed it.
