### ISSUE TITLE
My profile shows no ships on the profil overview

### ISSUE THREAD

**Issue by 144michi** [jedi-gg/swgoh.gg.public#597]
https://swgoh.gg/p/969367163/
Ally Code 969-367-163

Thanks.

**Comment by danpaulson** [comment]
This looks like a widespread issue, will investigate shortly.

**Comment by sanktanglia** [comment]
Figured this out, we hadnt turned the fleet sync back on after our db issue, its back on now and should catch up today/tom

**Comment by 144michi** [comment]
> 
> 
> Figured this out, we hadnt turned the fleet sync back on after our db issue, its back on now and should catch up today/tom

Sorry but my profile overview is just the same.

**Comment by 144michi** [comment]
Now its there.
