### ISSUE TITLE
Issue : Sync Player ID 

### ISSUE THREAD

**Issue by harryawesome** [jedi-gg/swgoh.gg.public#598]
I've newly registered SWGOH GG and have been trying to sync my Player ID. However the sync never gets active, besides Player ID lookup tool shows "Network issue" and I cannot find my Player ID. Wifi works perfectly, I'm wondering if there is anything related to Google chrome setting? Or simply bug.

**Comment by sanktanglia** [comment]
should be fixed now, we had to update our tools cuz of a client update
