### ISSUE TITLE
Payout Chart Times Displaying as UTC

### ISSUE THREAD

**Issue by Vas01** [jedi-gg/swgoh.gg.public#600]
After I login my fleet and ship payout charts, and the same charts for others, display time in UTC when I hover over the lines. It no longer displays the payout times in my local timezone (Eastern US). Is there a way to fix this or a setting I can update so they will display in Eastern US again like it used to?

https://swgoh.gg/p/972146854/

**Comment by scobenes** [comment]
Because of issues with daylight savings, we are just showing everything as UTC anymore
