### ISSUE TITLE
Sync Player ID

### ISSUE THREAD

**Issue by SSV-swgoh** [jedi-gg/swgoh.gg.public#601]
Hi,
I'm trying to help a guild member with their swgoh.gg account constantly giving a Player ID not found error when they try to enable syncing. Ally code is 441-192-542/
We've tried using the Player ID lookup tool and trying the resulting value. We've tried every variation of characters where there might be some doubt (zero vs O for example), and every attempt returns the same error message. Any help you could provide would be appreciated.

**Comment by scobenes** [comment]
This is for anyone else who may find this.  If you have issues do try the id help tool at https://swgoh.gg/id-help/ and if that doesn't work.  Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need
