### ISSUE TITLE
Galactic Power discrepancy on Guild Overview Page

### ISSUE THREAD

**Issue by tonyrosario** [jedi-gg/swgoh.gg.public#606]
The value of total Galactic Power on the guild page does not match the sum of each individual member's GP.

This is important so that guild officers can use GP to create a plan for end-game content, like LS/DS Geo TB.  Is there any idea what could be causing the discrepancy?  After asking around, the total GP on the overview page is closer to the actual in-game value.

https://swgoh.gg/g/5057/caw-patrol/
Total GP listed = 311,549,881
Summed (via google sheets) = 319,899,340

This is repeatable on any guild's page.
https://swgoh.gg/g/840/rh-old-republic/
Total GP listed = 267,228,480 
Summed (via google sheets) = 276,929,510

**Comment by danpaulson** [comment]
This has been fixed CG side.
