### ISSUE TITLE
Relics from swgoh.gg/api

### ISSUE THREAD

**Issue by mncubbie813** [jedi-gg/swgoh.gg.public#607]
After pulling in data from swgoh.gg/api/guild & swgoh.gg/api/player it looks like there is something funny with the relic data. For example it says that all of my characters are R1 which obviously isn't the case. My Bossk was listed at R4 but he's only R2. My CLS, Han, Chewie, Thrawn, Old Ben & Jango are listed at R7 but they are only R5. Is the data wrong or is there something wrong on my end? My ally code is 763752939.

**Comment by cprovick** [comment]
It looks like the power and relic related info is wrong for all toons. this is causing issues for character analysis and also other apps/websites that use this data. Can this be corrected?

**Comment by sanktanglia** [comment]
the relic numbers arent levels, they are an enum value the game uses 1 is locked, 2 is unlocked, 3 is Relic 1, 4 is relic 2 etc
