### ISSUE TITLE
402 problem for gac history data redux

### ISSUE THREAD

**Issue by DylanTusler** [jedi-gg/swgoh.gg.public#608]
Sorry for duplicate subject line. I wasn't sure whether a reply to a closed post would be noticed. I am really having trouble with this 402 and gac data. I am only browsing through my guild members looking mainly at their fleet battles, and after I get through a handful, I get 402s all the time.

sanktanglia offered to check my log data if I supplied my IP address. Its actually annoying me enough now that I think I'll take up that offer. My IP is 58.96.35.15

Please advise what I can do to avoid this problem?

Here are the 3 last URLs I visited that gave me 402 errors:
https://swgoh.gg/p/531915519/gac-history/
https://swgoh.gg/p/363167469/gac-history/
https://swgoh.gg/p/294211998/gac-history/

**Comment by scobenes** [comment]
This is most likely an old bug
