### ISSUE TITLE
Unable to view 12/29 GAC history

### ISSUE THREAD

**Issue by sweatje** [jedi-gg/swgoh.gg.public#609]
I have been unable to view GAC history for 12/29 via  https://swgoh.gg/p/449656666/gac-history/?gac=5

I get an error 
"DATA ERROR: There is either no data for this GAC, or our servers are having trouble retrieving the data."

 This problem has persisted since the button showed up which allowed me to navigate to it, and I have tried several times over the past week without getting a different result so I don't believe it is a cache or page limit issue.

I am able to successfully browse to the history for 12/22 via https://swgoh.gg/p/449656666/gac-history/?gac=4 and 12/15 via https://swgoh.gg/p/449656666/gac-history/?gac=3 without issue.

**Comment by danpaulson** [comment]
We had issues scraping these old GACs - will hopefully be better going forward.
