### ISSUE TITLE
Deleted account still syncing 

### ISSUE THREAD

**Issue by stashamarie** [jedi-gg/swgoh.gg.public#611]
I deleted my account but it is still syncing everything and showing my history. From my understanding swgoh.gg is an optional tool  and not a requirement. What’s the point of me deleting the account if nothing changes except me not being able to sign in the account. Can this be fixed?

**Comment by danpaulson** [comment]
We remove all user data, but player data (from the game) is not deleted. This data is available via many sources, and this is the functionality intended by CG.

**Comment by stashamarie** [comment]
Wow, so there is not way to stop it?  Does the game automatically sync your game account even if you dont open a swgoh.gg account?

**Comment by danpaulson** [comment]
Your game data is available publicly via a number of known methods. Discord bots and other sites, along with our site, are able to access any users game data in this manner. While a lot of users do have profiles on swgoh.gg, we have many game profiles that do not have users attached to them.
