### ISSUE TITLE
API for GAC generating 500 error

### ISSUE THREAD

**Issue by hansenwebco** [jedi-gg/swgoh.gg.public#613]
Was looking at the API endpoint for GAC history but I'm getting an error when trying to pull data:

GET:
https://swgoh.gg/api/player/761961747/gac/7/

also tried

GET:
http://swgoh.gg/api/player/761961747/gac/7/

Not sure if I'm using the wrong ID for instance id, or it's something maybe not done yet?

**Comment by sanktanglia** [comment]
the gac api isnt public yet, you are just seeing the internal api we use that isnt available

**Comment by SamYouatt** [comment]
Has this api been made public yet?

**Comment by scobenes** [comment]
There are no immediate plans to make a public API right now.
