### ISSUE TITLE
Alignment Filters on Characters view return no results

### ISSUE THREAD

**Issue by ZiroG** [jedi-gg/swgoh.gg.public#614]
Go to a profile, select characters, select filters option, choose alignment option, choose either alignment (light or dark) to apply filter.

Character page returned is empty with no toons showing.  For example, see this page which is blank with just the applied filter name showing: https://swgoh.gg/p/651429194/characters/?f=Light+Side

Maybe this is left-over from issue #573?

**Comment by azgo** [comment]
It'd be very cool to fix this (probably) remainder of #573 .
Guildwise it's very hard to guide some members without it :/

**Comment by m43l5tr0m** [comment]
Almost two years later, still broken...

**Comment by scobenes** [comment]
its fixed

**Comment by azgo** [comment]
Yes, it's working properly for some time, can't exactly tell when it was fixed, but thanks for the work
