### ISSUE TITLE
GAC history: H&P does not display correctly when saved as PDF

### ISSUE THREAD

**Issue by BomaFett** [jedi-gg/swgoh.gg.public#615]
I like to save my GAC history as PDF files (print>save as PDF) for offline viewing. However, Health and Protection bars show as full on every character on the PDF. I am attaching a couple of PDFs from my last match so you can see what I mean.

[GAC 5.3.3 Defense.pdf](https://github.com/jedi-gg/swgoh.gg.public/files/4203027/GAC.5.3.3.Defense.pdf)
[GAC 5.3.3 Offense.pdf](https://github.com/jedi-gg/swgoh.gg.public/files/4203028/GAC.5.3.3.Offense.pdf)

# Please read the FAQs in this repo's README before posting.

**Comment by scobenes** [comment]
Saving to PDF isn't something we will support.
