### ISSUE TITLE
Unable to Sync Guild data

### ISSUE THREAD

**Issue by Dasmook** [jedi-gg/swgoh.gg.public#617]
hello. I am now a Patreon of the website, but I am unable to Sync my guild page. Any insight as to why this feature is unavailable?

**Comment by Dasmook** [comment]
https://swgoh.gg/g/428/alpha-squad/

**Comment by sanktanglia** [comment]
do you see the button to sync the guild? i was able to click it and sync the guild manually myself. Have you linked patreon in your settings on https://swgoh.gg/settings/ and do you see your guild benefits? You can also try logging in/out to see if it is cached for you

**Comment by Dasmook** [comment]
![DD412547-A291-490A-BD7A-57ECAF6FDE11](https://user-images.githubusercontent.com/61429308/75180997-4ad5be00-570b-11ea-84c4-3061b7191e5d.png)
Hello, I see the sync button, but I am unable to select. Screenshot attached.

**Comment by Dasmook** [comment]
I tried signing out and logging back in to see if that would fix it, but I am still unable to sync my guild page.

**Comment by Dasmook** [comment]
I am still experiencing this issue on my end. Still can’t sync guild data after 12 hours since you manually updated it.

**Comment by sanktanglia** [comment]
can you send me your ally code? i can try and find some time to debug it after my regular job today, if not it may be a day or 2

**Comment by Dasmook** [comment]
184-132-947. I am still experiencing this issue. If you’re able to sync the guild for me while you research, that would be greatly appreciated! Thanks!

**Comment by sanktanglia** [comment]
yep just synced it for you, will be diving into it in more detail soon

**Comment by danpaulson** [comment]
It looks like you are the "Pro Sync" tier ($3), which doesn't have guild refresh capabilities. Let me know if that isn't the case!

**Comment by Dasmook** [comment]
Thanks, I guess I assumed the 5 refreshes was for both player and guild. I just upgraded my paetron membership to the $10, but my perks are still showing the benefits of the $3 level. Is there typically lag time to getting the perks to update before I can use them?
