### ISSUE TITLE
GAC history missing

### ISSUE THREAD

**Issue by Pepiteskiller** [jedi-gg/swgoh.gg.public#618]
Hi, my GAC history is missing for 14/02/2020 : https://swgoh.gg/p/823653674/gac-history/

[](https://swgoh.gg/p/823653674/gac-history/)

**Comment by Wreend** [comment]
Same here https://swgoh.gg/p/247776473/gac-history/

**Comment by molrakea** [comment]
I thought this could be pulled even if they took down their SWGOH profile.
https://swgoh.gg/p/921765573/gac-history/

I can't pull anything for current opponent.

**Comment by scobenes** [comment]
We attempt to pull as much as we can, but may not always get it because of the way we access it.  I hope we got it eventually for ya.
