### ISSUE TITLE
Squad Templates Link from Guild Page throws a 302 and Redirects to Login

### ISSUE THREAD

**Issue by johnhall1141** [jedi-gg/swgoh.gg.public#619]
Seeing this issue in chrome and firefox on both android and MacOS and incognito and private windows.

Request URL: https://swgoh.gg/g/65729/yavin-a-blast-too/squad-templates/
Request Method: GET
Status Code: 302 
Remote Address: 104.18.42.180:443
Referrer Policy: no-referrer-when-downgrade
age: 33952
cf-cache-status: DYNAMIC
cf-ray: 56b35d76d92ff355-ATL
content-type: text/html; charset=utf-8
date: Wed, 26 Feb 2020 16:41:11 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
location: /accounts/login/?next=/g/65729/yavin-a-blast-too/squad-templates/
server: cloudflare
status: 302
via: 1.1 varnish (Varnish/6.0)
x-cache: ZIP
x-frame-options: SAMEORIGIN
x-varnish: 564334220 534775169
:authority: swgoh.gg
:method: GET
:path: /g/65729/yavin-a-blast-too/squad-templates/
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cookie: __cfduid=d661f07c36e47bfc0f428fb2e38420c4f1582734116; _ga=GA1.2.366618495.1582734118; _gid=GA1.2.1003429643.1582734118; _ym_uid=158273411929627691; _ym_d=1582734119; _ym_isad=2; _ym_visorc_53284504=w; pbjs-id5id=%7B%22ID5ID%22%3A%22ID5-ZHMO_7MvBIoRgBd9zTvrJcBVjtLTBWNyFKIa3NpHvQ%22%2C%22ID5ID_CREATED_AT%22%3A%222020-02-19T13%3A06%3A59.205Z%22%2C%22ID5_CONSENT%22%3Atrue%2C%22CASCADE_NEEDED%22%3Atrue%2C%22ID5ID_LOOKUP%22%3Atrue%2C%223PIDS%22%3A%5B%5D%7D; pbjs-id5id_last=Wed%2C%2026%20Feb%202020%2016%3A22%3A01%20GMT; __gads=ID=275a192dc9164e7f:T=1582734153:S=ALNI_Ma_bDYF3FFrzUVtMcwyDCZnxqBSPw; sessionid=1bc72g4nzpsvp2a35attuqa5y0kp0ayo; freewheel-detected-bandwidth=417; GED_PLAYLIST_ACTIVITY=W3sidSI6IlBFL1QiLCJ0c2wiOjE1ODI3MzQ5ODAsIm52IjowLCJ1cHQiOjE1ODI3MzQ5NDcsImx0IjoxNTgyNzM0OTQ4fV0.; __qca=P0-46639041-1582735160168; csrftoken=jFqrp3FqVuudpdsO2C1DtAHZXCpfwqwX6zDNcnDdwhnfbCSrsWzhF9wZz1IjXAOs
referer: https://swgoh.gg/g/65729/yavin-a-blast-too/
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

`

**Comment by Milus121** [comment]
Same here 
If I go to squad-templates I immediately log out of site

**Comment by polaris2828** [comment]
Me too: takes me to the log in page.

**Comment by MikeTwin** [comment]
I have this problem too!
Username OKNY https://swgoh.gg/p/857244961/
Link squad: https://swgoh.gg/g/57910/4pda-ziost/squad-templates/

**Comment by r4p6-swgoh** [comment]
Here ist the same problem sometimes. In the morning it works an 3 hours later there es a problem

**Comment by mhonok** [comment]
Hello, same issue just affter created a new template.
https://swgoh.gg/g/39766/exar-kun-the-dark/squad-templates/

**Comment by mhonok** [comment]
seems corrected thanks

**Comment by mhonok** [comment]
Ahhh no, issue appears again :
https://swgoh.gg/g/39766/exar-kun-the-dark/ and i click on squad template and i've been redirecte to https://swgoh.gg/accounts/login/?next=/g/39766/exar-kun-the-dark/squad-templates/

**Comment by mhonok** [comment]
Juste before, i updated the title of one team template. strange...

**Comment by scobenes** [comment]
This is most likely an old bug
