### ISSUE TITLE
Cannot Access Squad Template on the Guild Page

### ISSUE THREAD

**Issue by LloyldIngrid** [jedi-gg/swgoh.gg.public#623]
When Trying to access the Squad Template Section for our guilds first Heroic Sith Raid. It keeps bringing me back to the login screen and when I go back to that section it does so again in an infinite loop.

Please Advise

**Comment by LloyldIngrid** [comment]
Update. Tab links to https://swgoh.gg/g/47627/the-makashi-guardians/squad-templates/
But actually loops back and takes me to
https://swgoh.gg/accounts/login/?next=/g/47627/the-makashi-guardians/squad-templates/

once login is resubmitted it takes me right to

https://swgoh.gg/

and the loop continues

**Comment by speakimp** [comment]
Same thing happened to me today. Here’s my guild page: https://swgoh.gg/g/4880/drop-1t-like-its-h0th/

**Comment by scobenes** [comment]
This is most likely an old bug
