### ISSUE TITLE
Darth Maul & Captain Han Solo - 0.000 modifiers for attacks

### ISSUE THREAD

**Issue by jdlbrosz** [jedi-gg/swgoh.gg.public#624]
Two characters have damage modifiers of 0.000 where there clearly should be non-zero values.

Darth Maul's basic (raging storm) and special (whirling blades): https://swgoh.gg/characters/darth-maul/
Captain Han Solo's basic (disabling shot) https://swgoh.gg/characters/captain-han-solo/

**Comment by danpaulson** [comment]
This will be fixed in a future update.
