### ISSUE TITLE
GAC History shows inccorect HP/Prot

### ISSUE THREAD

**Issue by kernal42** [jedi-gg/swgoh.gg.public#627]
In GAC history, units with 1 hp are shown as dead.  Battle was offensive loss Traya vs Bugs.  
[Battle](https://swgoh.gg/p/514561751/gac-history/?gac=16&r=3&a=d)
[SWGOH screenshot](https://www.dropbox.com/s/b04x9aa2a0m9j1t/Screenshot_20200420-122530.png?dl=0) 
[SWGOH.GG screenshot](https://www.dropbox.com/s/lcovxuyztkzn60g/ScreenshotFromSWGOH.png?dl=0):

**Comment by scobenes** [comment]
Hard to tell at this point. We show the data as we get it directly from CG.
