### ISSUE TITLE
My Player ID doesn't work 

### ISSUE THREAD

**Issue by AnakinTheGreat** [jedi-gg/swgoh.gg.public#628]
I just joined SWGOH.GG and i was trying to sync my acc ,but although i type my Player ID correctly i cannot sync it can it be resolved somehow or what should i do .

**Comment by jegeda** [comment]
I cannot use it either, I have checked and checked again trying every variation but nothing works, is there a way this issue could be fixed?

**Comment by drew033** [comment]
Still not working...

**Comment by danpaulson** [comment]
This should be fixed now.
