### ISSUE TITLE
Galactic Legends Gear needed not showing gear needed

### ISSUE THREAD

**Issue by bjeenie2** [jedi-gg/swgoh.gg.public#633]
When you go to https://swgoh.gg/p/____/gl-gear-needed/ you see that Supreme Leader Kylo Ren is already selected but no gear list is showing.
When selecting Rey the gear for her is showing. If you reselect Kylo the gear is not showing

**Comment by bjeenie2** [comment]
Its also not showing for the newly added jedi knight luke

**Comment by scobenes** [comment]
works fine for me on one of my guild mates?.. can u paste me a link for one that doesnt work?

ex: https://swgoh.gg/p/819189368/gl-gear-needed/

**Comment by bjeenie2** [comment]
Well its not working on this one: https://swgoh.gg/p/735712576/gl-gear-needed/

**Comment by scobenes** [comment]
that person has everything needed for JKL
![image](https://user-images.githubusercontent.com/3346556/89940415-17b2b880-dbdf-11ea-8ba9-0081de620010.png)
and everything for kylo
![image](https://user-images.githubusercontent.com/3346556/89940460-26996b00-dbdf-11ea-9210-bdeee23e6a2e.png)

but missing for rey:
![image](https://user-images.githubusercontent.com/3346556/89940502-3749e100-dbdf-11ea-99bf-ce8975cd66dd.png)

**Comment by bjeenie2** [comment]
Well thats kinda weird as it was a link used from my dwgoh.gg account and i’m farming rey and luke atm... 
i tried it again on my smartphone and now its showing correctly. Weird.

**Comment by scobenes** [comment]
yea weirdness, but glad you can see it!
