### ISSUE TITLE
CT-5555 "Fives" - 5S ship ability "Umbaran Missile Pods" showing up on his character sheet

### ISSUE THREAD

**Issue by CoRrRan** [jedi-gg/swgoh.gg.public#635]
https://swgoh.gg/p/675746713/characters/ct-5555-fives
https://swgoh.gg/p/363964994/characters/ct-5555-fives

Fives shows "Umbaran Missile Pods" as an ability on his character stat sheet, as linked above. (First one is mine, 2nd is YouTuber Black Mamba's, where I found this error.)

Actually: also happens with Darth Vader's "I have you now".  This ship ability also shows up on DV's character stat screen:
https://swgoh.gg/p/675746713/characters/darth-vader

Just noticed Bossk has the issue too:
https://swgoh.gg/p/675746713/characters/bossk

But not ALL of the characters have this...

![image](https://user-images.githubusercontent.com/23401111/87015709-10f2e900-c1ce-11ea-9bfd-bc139a8eff53.png)

**Comment by danpaulson** [comment]
This is a known issue - fix is likely coming with a site re-write
