### ISSUE TITLE
404 Page not found error

### ISSUE THREAD

**Issue by JediAhsoka** [jedi-gg/swgoh.gg.public#636]
I keep getting a 404 page not found error whilst trying to link my player ID to my swgoh.gg account, I'm clearly entering the ID correctly, and there seems to be no solutions on here. hopefully someone can offer some sort of resolution.

**Comment by siltwodelek** [comment]
Same here, URL is https://swgoh.gg/p/277778958/. Thought it might just take few hours, but it‘s been over a day now.

**Comment by eacopela** [comment]
same here

**Comment by KiwiGourou** [comment]
Same thing, and it's really frustrating...

**Comment by stunner470** [comment]
Hello
Sorry created the same issue again. 
Same here
My account is syncrd but I cannot access my page https://swgoh.gg/p/944183897/
The data is availalable in echo bots but the page is not accessible on swgoh.gg
Please help
Regards

**Comment by Sunfyre86** [comment]
Hello, I just registered and I don't know if I could sync my account, but I get that same error. https://swgoh.gg/p/795548132/

**Comment by sanktanglia** [comment]
We are working on tracking down the issue

**Comment by sanktanglia** [comment]
This is now fixed, sorry about that!

**Comment by siltwodelek** [comment]
Cannot login. Due I need to create a new account?

**Comment by JediAhsoka** [comment]
Yes. If you create a swgoh.gg account and link you’re in-game account to
it, you should be able to sync them and view your roster on the website.
The sync feature has been fixed now.

**Comment by siltwodelek** [comment]
Yeah, sorry, cleared cache, now everything works. Thanks a lot!

**Comment by JediAhsoka** [comment]
Sweet! No problem!
