### ISSUE TITLE
404 Page not Found 

### ISSUE THREAD

**Issue by stunner470** [jedi-gg/swgoh.gg.public#638]
Hello 
My account is syncrd but I cannot access my page https://swgoh.gg/p/944183897/
The data is availalable in echo bots but I cannot access my characters at swgoh.gg
Please help thank you
Regards

**Comment by eacopela** [comment]
Hello, 
I am having the same issue still, the previous ticket I was a part of was closed without resolution. 
Link for reference. 
https://swgoh.gg/p/796727876/

**Comment by KiwiGourou** [comment]
Same thing for me ! It said resolved but it's still not working... here is my link: https://swgoh.gg/p/939526324/

**Comment by sanktanglia** [comment]
have you tried syncing again in your settings? that should fix it

**Comment by stunner470** [comment]
Thank you everything is fixed now
