### ISSUE TITLE
Error 404 when going on my page

### ISSUE THREAD

**Issue by KiwiGourou** [jedi-gg/swgoh.gg.public#639]
Hello,
My account is syncronised but I cannot access my page: https://swgoh.gg/p/939526324/
I already reported in someone else's ticket, and they told us it was fixed, but it's still not working for me....
Can someone fix this please?
Best regards

**Comment by sanktanglia** [comment]
have you tried syncing again in your settings? that should fix it

**Comment by KiwiGourou** [comment]
Yes, I already tried that and it didn't work unfortunately

**Comment by PixEye** [comment]
This one looks fixed (no more 404 error at this [link](https://swgoh.gg/p/939526324/)).

**Comment by Oxys88** [comment]
Не могу зайти на свою страницу. Выдает ошибку 404. https://swgoh.gg/p/697141215/ повторная синхронизация не помогает.
