### ISSUE TITLE
Formatting on 1024x768.

### ISSUE THREAD

**Issue by twood17** [jedi-gg/swgoh.gg.public#643]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Adding the `Galactic Challenges` to the nav has adjusted the format.  It has occurred across all the pages I have visited.  I have attached a photo.

https://ibb.co/8gGx2bp

![swgoh gg layout](https://user-images.githubusercontent.com/45881482/90564921-1865c480-e174-11ea-867a-5775ce192a05.png)

**Comment by danpaulson** [comment]
I've cleaned this up in the nav.
