### ISSUE TITLE
SWGOH.GG doesn't update my profile automatically

### ISSUE THREAD

**Issue by ceuba22** [jedi-gg/swgoh.gg.public#644]
My arena ranking has not been updated since August 12th. Everything else is updated except the rating. The classification of the fleet arena is updated as normal. Would you help me?

https://swgoh.gg/p/897178631/

**Comment by Ferril9909** [comment]
I just noticed mine is also not updating
https://swgoh.gg/p/934848883/

also, my Galactic Legends gear required is not updating based on recent upgrades I have performed.  I only have 5 characters to relic yet it still shows I require 600 kyros.

**Comment by scobenes** [comment]
We are having issue with the scanner lately, your profiles may be getting affected.  We are trying to add additional logging to find the source of the problem.

**Comment by danpaulson** [comment]
This appears to be resolved.
