### ISSUE TITLE
Guild still showing removed player profiles

### ISSUE THREAD

**Issue by Ferril9909** [jedi-gg/swgoh.gg.public#646]
We've dropped two players over the last 5 days... They still show in our member list.  The guild data is correct, but the profiles still show
https://swgoh.gg/g/31367/juiceboxheroes/

The two dropped members are Big Ravioli, 183-894-633 , who has joined Chirpa's Raiders in game
https://cdn.discordapp.com/attachments/522497959879770125/745950411634114640/Screenshot_20200820-061439.png

and Swamptrooper, who has yet to join a new guild
https://cdn.discordapp.com/attachments/522497959879770125/745950411260952636/Screenshot_20200820-061941.png

**Comment by danpaulson** [comment]
This appears to be updated now - likely coincided with our guild sync issues.
