### ISSUE TITLE
500 error message

### ISSUE THREAD

**Issue by jamesxz1** [jedi-gg/swgoh.gg.public#650]
I recently joined swgoh.gg but I am unable to sync my account to the service. I have tried variety of either 0s or Os and even tried to replace a obvious 1 with a Capital I, 

The player ID checker is also not helping 

Any suggestions for this?

**Comment by AdmiralP** [comment]
When you copy and paste the recommended player ID from the player ID checker into your account, what message, if any, do you get?

**Comment by jamesxz1** [comment]
I just get this page each time

James.

**Comment by jamesxz1** [comment]
The player ID checker doesn’t work either same message appears

James.

**Comment by jamesxz1** [comment]
How I’m receiving a notification that the player id checker is down

**Comment by AdmiralP** [comment]
Looks like they may just be experiencing some downtime. I am guessing the checker will be up and running fairly quickly. I have helped out probably ten players in my guilds, and it has always been reliable when I copy and paste the content. Either way, these guys are generally pretty quick to respond and help you get setup so I am certain you will get there. Sorry I could not be of more help. Good luck!

**Comment by danpaulson** [comment]
Hey folks - indeed our player scanner is down. This unfortunately happens from time to time when there's a client update, and sank, who is the master of all client-ness, is traveling with family atm. We'll be back up and running asap.

**Comment by CadeVenx** [comment]
I get same error with my profile (https://swgoh.gg/p/957254583/). Seems to have started around the same time as my profile stopped syncing (5 days ago now). For some reason my fleet arena rank still updates but nothing else (arena rank, GL gear needed, etc) does.

**Comment by MorpheusV3** [comment]
@danpaulson we able to get a ETA on when it might be back up and running?

**Comment by danpaulson** [comment]
Likely today or tomorrow barring any unseen issues.

**Comment by CadeVenx** [comment]
My profile refreshed yesterday for the first time in several days but didn't refresh today. The 500 error at least seems to be gone but I am getting an unable to find profile error when I try to manually sync.
