### ISSUE TITLE
problem with player ID sync

### ISSUE THREAD

**Issue by NOTxXJORDANXx** [jedi-gg/swgoh.gg.public#651]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
I have tried muiltiple times to sync my account with no luck

**Comment by scobenes** [comment]
This is for anyone else who may find this. If you have issues do try the id help tool at https://swgoh.gg/id-help/ and if that doesn't work. Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need
