### ISSUE TITLE
swgoh profile not refreshing

### ISSUE THREAD

**Issue by Toryjn** [jedi-gg/swgoh.gg.public#652]
My swgoh profile has stopped refreshing. Last time it refreshed was 2 days ago.  How do I fix this?  I can not manuelly refresh either.  The timer is endless counting down from 1 minute and once it gets to 0 it resets.

How should I alleviate this? 
https://swgoh.gg/p/953437287/

**Comment by CadeVenx** [comment]
I'm experiencing the same issue with my profile: https://swgoh.gg/p/957254583/. It's now been 4 days since my arena rank and galactic legend gear needed have updated. Curiously, my fleet arena rank last synced 2 days ago. When I try manually syncing my profile, I get a 500 internal server error.

**Comment by mcebey1891** [comment]
Same error here!

**Comment by petersphilo** [comment]
I have a very similar issue, when I try to sync manually, the page tries to refresh, times out, then just shows the same data as before...
https://swgoh.gg/p/687663425/

**Comment by PixEye** [comment]
Fleet arena rank is outdated (several days ago): https://swgoh.gg/p/649159626/#fleet-arena-rank-chart
Here is a screenshot:
![image](https://user-images.githubusercontent.com/570446/96242281-96432200-0fa3-11eb-9c67-3fa57b21ae45.png)
And I confirm that this is not the first time.

**Comment by Who-Daat** [comment]
Same issues... can’t get my profile to sync... also says my player I’d does not exist... but it most certainly does... player I’d used to work, haven’t changed it, tried to resubmit it and says doesn’t exist... any thoughts / solutions?

**Comment by NeuDamage** [comment]
This seems to be a widespread issue.  I am seeing it on my account as well as on those of shardmates.  For example, I have been #1 in both arenas everyday but the update / recorded time is so late (or entirely missing for the day) that my rank as shown in SWGOH.gg is no longer very useful.
![2020-11-18 18_29_02-GL Gear xlsx - Excel](https://user-images.githubusercontent.com/74392484/99613501-88325800-29cc-11eb-9ff4-f9c7a85bea96.png)

**Comment by scobenes** [comment]
This is most likely an old bug when we were having server issues
