### ISSUE TITLE
Guild synch doesn't work but uses up refreshes

### ISSUE THREAD

**Issue by Oblivionus** [jedi-gg/swgoh.gg.public#653]
This is the 2nd day in a row when triggering a synch for my guild has not worked.
This is actually a recurring problem that I had in the past as well, but it was never this persistant.

I use one (of my daily 2) synchs and the following happens:
The request timed out at some point with a screen showing where it happened ( I didn't take a screenshot)
(up to Cloud Server it was ok, but swgoh.gg was not (red x)).
When I go back to my guild's page, both synchs have been used up.
Also, the guild doesn't update on its own (see picture), it has been 2 days now.

I am sorry, but this plain sucks.
The guild synch is about the only reason why I am paying monthly for my patreon membership because it is really useful.
But your servers have been messing this up for some time now, and it doesn't seem to matter to you.
Instead you introduce new features, instead of making sure the existing ones work first.

![grafik](https://user-images.githubusercontent.com/71875296/94248399-b6407200-ff1e-11ea-8a3a-e8d63705d735.png)

**Comment by sshotrod38** [comment]
I am a monthly supporter on patreon and decided to become a patron in order to use the guild sync. I am experiencing the exact same issue described above.

**Comment by MobilityOne** [comment]
Yep. Unable to sync guild for 6 days. Most recent error reported...
Error 502  Ray ID: 5da2241faff5f575 • 2020-09-29 02:05:47 UTC
Bad gateway

**Comment by scobenes** [comment]
Sorry about this, we had a lot of server issue back around this time.  This is most likely an old bug
