### ISSUE TITLE
Multiple Web Site Problems

### ISSUE THREAD

**Issue by dragonflii2** [jedi-gg/swgoh.gg.public#654]
1) https://swgoh.gg/settings/sync/ -- It was failing to find the player ID (even though there are very few 'lookalike characters' in my ID and I had tried all combinations.  But now it just returns a 500: Internal Server Error

2) https://swgoh.gg/id-help/ -- "It would appear the PlayerID lookup sevice is down. Please try again later."

**Comment by chrisbauschka** [comment]
I am having the same issue.  I receive the error "* Player ID not found. Please ensure you typed it correctly." when I attempt to sync my Player Id at the site "https://swgoh.gg/settings/sync/".  There are no unclear characters in my Player ID and I have entered and verified multiple times.  I also receive the same error in the ID lookup help link above.

**Comment by scobenes** [comment]
This is most likely an old bug when we were having server issues
