### ISSUE TITLE
Can’t connect previous account to new email 

### ISSUE THREAD

**Issue by AJWall** [jedi-gg/swgoh.gg.public#655]
Hey, I’m wanting to swap my player ID from an old Swgoh.gg account I can no longer access to my new one? Just wondering how I do that as now when I try to put in my player ID it says it’s linked to an account (obviously the older one)

**Comment by scobenes** [comment]
For anyone else with a similar issue: Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
