### ISSUE TITLE
Adds not allowing the site to be usable without addblock enabled. 

### ISSUE THREAD

**Issue by fingaz88** [jedi-gg/swgoh.gg.public#658]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

I'm trying to navigate your site and the new adds that you've added with video's at the top of the screen never go away on a mac. you can't click any of the navigation bars because the adds are covering them. It doesn't matter what browser I use, I have the same issues until I turn add blocker on and remove them from the page. I'd like to help support you guys with add revenue but something is up with the coding and how it is displayed on systems that is keeping the pages from being usable at all. I will try and attach a screenshot but the video's at the top of the screen just repeat over and over without any way of removing them. Forcing me to turn on add blocker.
<img width="1305" alt="Screen Shot 2020-10-08 at 11 53 10 AM" src="https://user-images.githubusercontent.com/72570241/95489757-e6dfcd00-095c-11eb-921b-e150b4655d46.png">

**Comment by scobenes** [comment]
We have changed ad providers since this was created.  It shouldn't be an issue still.
