### ISSUE TITLE
Strange skill in profile character page

### ISSUE THREAD

**Issue by rcaval** [jedi-gg/swgoh.gg.public#660]
In my profile's Ashoka Tano's character page, it appears to be a strange skill called "Turnabout". Same skill can be found in other profiles too. It seem to have leaked from the ship's page

https://swgoh.gg/p/469181459/characters/ahsoka-tano
https://swgoh.gg/p/291422326/characters/ahsoka-tano

<img width="599" alt="Screen Shot 2020-10-20 at 08 15 42" src="https://user-images.githubusercontent.com/1876988/96578972-74e87b80-12ac-11eb-8512-ccecf2487d55.png">

**Comment by scobenes** [comment]
This is most likely an old bug with ship abilities
