### ISSUE TITLE
500 error message after clicking "click here to link once pledged"

### ISSUE THREAD

**Issue by beardmonk75** [jedi-gg/swgoh.gg.public#663]
I became a guildmaster sync patron and clicked "Click here to Link Once Pledged" on the swgoh.gg settings page.
clicked the "allow" button for swgoh.gg to access my profile, but then all I get is a 500 error message.

my profile is https://swgoh.gg/p/191342329/

**Comment by scobenes** [comment]
So I unlinked my patreon, removed swgoh from permissions on my patreon and then relinked it again without any issues.  

The way I understand what happened, it sounds like the 500 error is on patreon's side.  I would try a couple things:

1. Turn off ad blockers
2. Make sure cookies and such aren't blocked
3. Try a different browser

Everything on our side looks to be working as intended, and you might have also hit something during when they might have had some issues.  Hope some of these help ya get that connected.
