### ISSUE TITLE
Some players' arena history graphs aren't showing

### ISSUE THREAD

**Issue by HokieFiend** [jedi-gg/swgoh.gg.public#664]
There are some players whose arena history graphs aren't showing up on their profile pages. Here is an example:

https://swgoh.gg/p/314986458/

**Comment by scobenes** [comment]
Some people are synced through guild means, but they never registered an account to begin the daily automatic arena/fleet scanning.  This seems to be one of those accounts that exists bc we synced them via their guild (most likely).  Or I think if they removed their playerId from their account at some point we disable showing the historical information.

Unless the person is complaining about this, this seems to be working as intended.
