### ISSUE TITLE
Make your data columns fully visible. 

### ISSUE THREAD

**Issue by zlov137** [jedi-gg/swgoh.gg.public#666]
Go to SLKR under units and you'll see (in Chrome, Safari, TOR) your twin flanking ads, yet you cant scroll over to see how many zetas beyond 4 people have for that unit in your guild without shrinking every other thing including the guild members' names.

Sure, there weren't characters with more than 4 zetas when SWGOH.gg launched, but now that there are 6 on GL(s). Maybe make it so you can scroll over and see the full compliment of zetas without having to shrink all the other sections?

Maybe add a section discerning if the GL has its ultimate or not as well?

**Comment by scobenes** [comment]
Yea this is old table plugin and needs updating.

**Comment by scobenes** [comment]
I updated this so it is dynamic and also shows omicrons now
