### ISSUE TITLE
Baze Malbus shard locations

### ISSUE THREAD

**Issue by Wilbur691** [jedi-gg/swgoh.gg.public#669]
Can you please verify the shard locations for Baze Malbus. I have checked every Guild Events Store refresh for 3 months and there hasn’t been a single Baze shard at all. Maybe it was a one time offer, but I believe that he has been removed, since I’ve checked every refresh for 3 months and have still yet to see him show at all.

**Comment by scobenes** [comment]
Some of the shard locations were based off spreadsheets people did, it is not possible for us to know certain shard shops like guild store.  We may get rid of it so we don't have potential bad information for ones we cannot be 100% on.  If you find some source that has a good list, make a new post and we may update it.
