### ISSUE TITLE
Personal and Guild collection out of sync. 

### ISSUE THREAD

**Issue by DarthJJ** [jedi-gg/swgoh.gg.public#671]
My character collection is not synced to my guild.
I have unlocked Sith Eternal Emperor for quite some time now, but this isn't reflected in our guild data. another member (who unlocked later than me) is visible in the guild overview. 

my profile: https://swgoh.gg/p/393333993/characters/ (search for SEE)
my guild: https://swgoh.gg/g/5039/dutch-poison/unit-search/ (search for SEE)

A refresh of both my guild and personal profile did not work. 

Correct personal overview: 
![image](https://user-images.githubusercontent.com/9209118/102185355-3983bb00-3eb1-11eb-86f4-9dbae92847c5.png)

Incorrect guild overview:
![image](https://user-images.githubusercontent.com/9209118/102185397-4c968b00-3eb1-11eb-938b-4108e966dcc3.png)

Upon further research, it seems that more units and players in my guild are affected.
If I look at Moff Gideon for example, according to the guild overview only 20 people have unlocked him, but when I look at some  members who are not in that overview, they also have moff gideon unlocked (including myself)

**Comment by NickRJanssen** [comment]
I found this issue while testing my bot. I got different data for personal and guild commands.

**Comment by danpaulson** [comment]
Thanks - investigating today.

**Comment by DarthJJ** [comment]
It seems like some sort of sync has happened. 
Not all, but more SEE are visible in my guilds overview, and all Moff Gideon's are updated.
