### ISSUE TITLE
Arena Rank not syncing correctly

### ISSUE THREAD

**Issue by Lunatiq23** [jedi-gg/swgoh.gg.public#672]
My arena rank is not syncing correctly. I have been finishing 1st daily during my payout but this is reflected incorrectly on my profile page.

https://swgoh.gg/p/526614848/

**Comment by DasButch** [comment]
the same happens to me, though only in squad arena. while fleet arena is recorded at the right time and witht the right payout spot, squad arena recording time "jumps" in a wide range and always recording at the wrong time lately. 

https://swgoh.gg/p/888646262/

**Comment by mnkkl** [comment]
Same. Just found it out, but I guess it's been out of synch for some time. It checks the rank at a random time wildly, so that the graph is super wavy. I do take 1st on both arena and the fleet arena is working correctly.

https://swgoh.gg/p/936362293/

**Comment by scobenes** [comment]
service was completely unresponsive, but we restarted it and should be back to recording it.  holiday delay.
