### ISSUE TITLE
swgoh.gg profile linking

### ISSUE THREAD

**Issue by aljobie** [jedi-gg/swgoh.gg.public#674]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
Hi, 

I am trying to associate a SWGOH player id to my profile but it is already associated.  Is there any assistance for this?

account: https://swgoh.gg/p/527788677/

profile I need linked: aljobie17

Thank you,

Aljobie

**Comment by scobenes** [comment]
For anyone else with a similar issue: Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
