### ISSUE TITLE
Arena out of sync

### ISSUE THREAD

**Issue by wmr1980** [jedi-gg/swgoh.gg.public#675]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Hi guys

Fleet seems to be in sync but arena is all over the place. This has been happening for a while - my payout is 7pm UTC and pretty much for the last few weeks it's been synching at all sorts of random times. Are you aware of this?

**Comment by SaulAshtar** [comment]
Hi there,
I’ve the exact same issue. Interested by the answer.

**Comment by scobenes** [comment]
This is most likely an old bug when we had server issues
