### ISSUE TITLE
Allow CORS on your API

### ISSUE THREAD

**Issue by Dewilap** [jedi-gg/swgoh.gg.public#676]
Hello, 

Your API is not allowing CORS. These makes it hard to call it via Javascript. I need to go over cors-anywere proxy. Could you be so kind to allow CORS?

I saw the same issue here #275 but it's closed. 
Have you done something or not ? 

Best regards,

**Comment by AdmiralP** [comment]
I obviously do not work for them, but I cannot imagine they will do this for a number of reasons. 

First and foremost, doing so would allow others to create public websites and apps that pull from their resources. That would be costly, and effect performance on their own product.

You should not have any issue using JavaScript locally in your development, but no, it will not work if you are attempting to make a publicly available app or website. 

Just something to be aware of, but I believe these API resources are available to users that want to program tools limited to the use of the individual player. That player can disseminate that information to their guild if they choose to do so. It is not being made available for use in creating publicly available applications.

**Comment by scobenes** [comment]
Currently we will not offer access to the APIs with an origin of *.  You will have to proxy it or access it via a server if you wish to use it.
