### ISSUE TITLE
Linking account to Player_id fails as account has the ID

### ISSUE THREAD

**Issue by Pentalthorm** [jedi-gg/swgoh.gg.public#678]
My account had a different, but now invalid e-mail.
and now I cannot Sync nor update with current player ID.

SWGOW.GG account is "pentalthorm" which relates to philjudd70@gmail.com - this has changed from pjudd@clear.net.nz
Player_id the pentalthorm shold link to is "kO74hX6eSvmDoDwChQ5YmA"

Can you please help

**Comment by scobenes** [comment]
For anyone else with a similar issue: Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
