### ISSUE TITLE
My swgoh account is still updated even if I deleted my account in swgoh.gg

### ISSUE THREAD

**Issue by xkristal** [jedi-gg/swgoh.gg.public#679]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Hi,
I deleted my account in swgoh.gg to ensure that my swgoh player data will be no more updated in swgoh.gg . But player data are still updated and I do not want it (because of GAC). Can I somehow make GAC data invisible  or whole my player data (I know that old player data can not be removed from swgoh.gg statistics).
My player data: https://swgoh.gg/p/436474451/
swgoh.gg username:  xkristal , swgoh player name: Kristal
When account is deleted there is written:
What is not being deleted?
*** Your Player profile with Characters, Ships, GAC History. This is publicly available data from the game client and not exclusive to SWGOH.GG ***
There is mentioned GAC history. So I expect that GAC history will be preserved but it will be no more updated.

I created my swgoh.gg again and linked it already with player account to proof you that it is my account.

**Comment by Zawu2** [comment]
Have you found a solution, how to stop this site from showing your gac history to everyone ?

**Comment by danpaulson** [comment]
GAC data can not be made private.

**Comment by Zawu2** [comment]
I dont want to make it private. I want sqgoh.gg to stop updating it. 
  
  
   There are players whos gac data is not updating.. I want the same 
  
  
   
    Dan Paulson <notifications@github.com> hat am 19.02.2021 17:22 geschrieben:
   
   
    
   
   
    
   
   
    GAC data can not be made private.

**Comment by danpaulson** [comment]
I'm going to add a page to lookup opponents if they do not exist on the site. But all game data (IE SWGOH data) is public and will remain so.

**Comment by danpaulson** [comment]
Our intention is to add a page to lookup players by allycode and sync their data / GAC. We will not be making any data private - that is not the intent of the data being made available by the game. I will update this thread as we work on this, my guess would be early next week.

**Comment by Zawu2** [comment]
Right, this will be a great slution, when you add this page. Thx for the info and sorry for multiple posts. Was angry
  
  
   
    Dan Paulson <notifications@github.com> hat am 19.02.2021 19:04 geschrieben:
   
   
    
   
   
    
   
   
    Our intention is to add a page to lookup players by allycode and sync their data / GAC. We will not be making any data private - that is not the intent of the data being made available by the game. I will update this thread as we work on this, my guess would be early next week.

**Comment by xkristal** [comment]
Yes . It seems to me as fair solution , great

**Comment by xkristal** [comment]
Now I found a way to sync data of my opponent who is not registered to swgoh.gg BUT gac history is not displayed there yet. 
I know that now it can not be fixed but is it expected that it will be somehow solved in the future for the players who are not registered yet to swgoh.gg. If you sync some player for the first time then I guess there is no way how swgoh.gg could know GAC history.

**Comment by scobenes** [comment]
we will attempt to sync and get the last gac history of any new player added through this https://swgoh.gg/scan-player/
