### ISSUE TITLE
Access Data of old account unknown, created new account, but can't synchronize

### ISSUE THREAD

**Issue by AE1451** [jedi-gg/swgoh.gg.public#680]
Many years ago I created an account on SWGOH.gg. Now I wanted to log in again, but I wasn't able to remember with which adress and password I signed in once. So I created a new account and wanted to synchronize my SWGOH.gg-profile with my player-ID in in the game. It failed, because my old account is still remembered by the system. What can I do? The old username is AE, the new one AE1451. I would be glad if you can help me. Thank you!

**Comment by DrkVc3** [comment]
same problem

**Comment by AE1451** [comment]
Problem solved. After long search (and many tries) I was able to restore my old account data. New account is deleted now and old account is synced.
