### ISSUE TITLE
GAC history missing 

### ISSUE THREAD

**Issue by Plumbermike84** [jedi-gg/swgoh.gg.public#681]
Hey there! I just joined your site yesterday and I was wondering how long does it take for my GAC history to show up

https://swgoh.gg/p/673484226/gac-history/

**Comment by ShowLoTi** [comment]
Same

**Comment by scobenes** [comment]
We attempt to scan as often as we can, but the data is eventually consistent, which means we cannot guarantee when we get it.  Generally after 24hrs a majority of people are updated.
