### ISSUE TITLE
Arena tracker doesnt track my daily progress

### ISSUE THREAD

**Issue by glViolett** [jedi-gg/swgoh.gg.public#682]
Hello. https://swgoh.gg/p/496642589/ this is my profile. For some reason arena and fleet arena progress isnt tracking anymore. Can you have a look into it please?

**Comment by glViolett** [comment]
Pried to sync, to update profile - didnt work. Maybe nbecause I set my payout time as to :15 minutes?

**Comment by scobenes** [comment]
This is most likely an old bug and yes players with non hour/half hour payouts cause issues
