### ISSUE TITLE
Please delete my account

### ISSUE THREAD

**Issue by Zawu2** [jedi-gg/swgoh.gg.public#683]
I cant finde a way how to delete my account,, to stop swgoh.gg from showing my GAC history to everyone.
Plese delete my account and data.
My profile
https://swgoh.gg/p/718579377/

**Comment by danpaulson** [comment]
GAC data can not be made private. You can delete your account here if you wish (https://swgoh.gg/settings/delete/) but game data (not account data) is still live, including GAC. This is in line with CG's intention for GAC data.

**Comment by Zawu2** [comment]
Thx for the fast reply. Is there a possibility to stop swgoh.gg to update new data from My GAC ?
  
  
   
  
  
   There are alot of opponents, whos GAC data is not updating and shown as empty
  
  
   
    Dan Paulson <notifications@github.com> hat am 19.02.2021 17:23 geschrieben:
   
   
    
   
   
    
   
   
    GAC data can not be made private. You can delete your account here if you wish (https://swgoh.gg/settings/delete/) but game data (not account data) is still live, including GAC. This is in line with CG's intention for GAC data.
