### ISSUE TITLE
Pls unsync my account

### ISSUE THREAD

**Issue by Zawu2** [jedi-gg/swgoh.gg.public#684]
When i made an account on your site, You started to sync my gameaccount.
I have deleted my account and i want that you also unsync my gameaccount.
I know that you dont delete old history. I am fine with it. I want that you stop updating new dsta.

Why you updating gamedata for players, whou created an account once on your site, even when they delete it?
Sync for everyone, even when they never created an account on your site or give the possibility to stop it for people who made this mistake and created account on your site

**Comment by danpaulson** [comment]
Please stop creating multiple threads. I will update #679 with progress.
