### ISSUE TITLE
GAC counter filtering missing parameters

### ISSUE THREAD

**Issue by hyperionap** [jedi-gg/swgoh.gg.public#687]
The filtering mechanism for GAC counter are leading to an incomplete URL
For instance, I clicked in Nute inside the GG counters page:

https://swgoh.gg/gac/counters/GRIEVOUS/?season=15&sort=win_percentage&d_unit=

If you type "NUTEGUNRAY" in the URL the filter works ok.

Regards,
Hyperion

**Comment by dwcullop** [comment]
Both `a_unit` and `d_unit` parameters are affected.

The filtering feature is amazing and was sorely needed, but this makes it unusable (although you can work around the issue if you have a list of the character's ID strings available).

Thanks in advance,
Dexatronic#2112

**Comment by scobenes** [comment]
This is most likely an old bug
