### ISSUE TITLE
Need to switch player id to new .gg account

### ISSUE THREAD

**Issue by Thegyroman** [jedi-gg/swgoh.gg.public#688]
So I have a swgoh account that I would like to use swgoh.gg for, but there is already an account associated with that player ID. Is it a possibility for me to have those profile synced or have the player id added to the new account (or some other way for me to have access to the .gg)?

Old .gg account that I don't have access to: https://swgoh.gg/p/241397779/

New .gg account that I will be using: 241swgoh@gmail.com (Username: Boson)

**Comment by scobenes** [comment]
For anyone else with a similar issue: Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
