### ISSUE TITLE
Player ID already connected to another account

### ISSUE THREAD

**Issue by MrKnatterton** [jedi-gg/swgoh.gg.public#690]
Hello.

I just created an account on swgoh.gg and tried to link it with my SWGOH account here: 

https://swgoh.gg/settings/sync/

Sadly I always get the massage "Player ID already attached to an account". I've never linked my account before, so I don't know what to do. I would be glad if someone could help me.

My ingame name is: MrKnatterton
My ally Code is: 346-821-316

Thank you!

**Comment by Blackluster1511** [comment]
Did you get a reply from swgoh?

**Comment by AdmiralP** [comment]
I recommend suppressing your player ID and only providing it to the site admins upon request. Your ally code is public, so that is not as important and can remain.

**Comment by MrKnatterton** [comment]
> Did you get a reply from swgoh?

So far nothing happend

**Comment by MrKnatterton** [comment]
> I recommend suppressing your player ID and only providing it to the site admins upon request. Your ally code is public, so that is not as important and can remain.

Thank you for the tip.

**Comment by scobenes** [comment]
For anyone else with a similar issue: Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
