### ISSUE TITLE
Character numbers don't match in game numbers

### ISSUE THREAD

**Issue by maste-ryan** [jedi-gg/swgoh.gg.public#691]
https://swgoh.gg/p/159776837/characters/sith-eternal-emperor
This SEE is R8 in game, but the health stats you guys have him calculated as G13 R0.  The mods are correct, but it's treating him as an R0 instead of R8 like he actually is.  This is not the only character, this is happening throughout several users pages.  I believe something may have went haywire with the new client released yesterday.

Been able to identify that this issue is mainly affecting R8 characters.

**Comment by scobenes** [comment]
This is most likely an old bug
