### ISSUE TITLE
Can not log in or reset pw

### ISSUE THREAD

**Issue by Johannm106** [jedi-gg/swgoh.gg.public#692]
Hello.

Today i logged out my account and i can not log back in now.
I already tried to reset my pw but i do not receive any mails. It must be the right adress/username.

Profile: https://swgoh.gg/p/615299369/

Can you help me with that please? 

Cheers

**Comment by scobenes** [comment]
For anyone else with a similar issue: Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
