### ISSUE TITLE
Account already Linked 

### ISSUE THREAD

**Issue by Blackluster1511** [jedi-gg/swgoh.gg.public#693]
My SWGOH player ID is already linked to a swgoh.gg account. Canyou please release the ID so I can link it to my swgoh.gg account?

https://swgoh.gg/p/197998684/

**Comment by DrkVc3** [comment]
Same problem

**Comment by snow907** [comment]
https://swgoh.gg/p/563611814/ need to unlink account don't have any clue what email I used trying to link new one but cant

**Comment by Paynetrain42** [comment]
I have the same issue 
https://swgoh.gg/p/921297388/

**Comment by alexwinter1119** [comment]
I have the same issue as well https://swgoh.gg/p/383375541/

**Comment by scobenes** [comment]
For anyone else with a similar issue: Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
