### ISSUE TITLE
Guild not sync’ing properly

### ISSUE THREAD

**Issue by camerak** [jedi-gg/swgoh.gg.public#694]
Our guild’s page is showing 51 members. However, 2 of those members have been out of the guild for over 2 months. The issue with our guild’s sync has been going on since mid January. One other has been removed but is still on the list as well.

SwiftIce, Benjin, Shaj’nei are the accounts that are no longer in our guild.

https://swgoh.gg/g/725/canadian-rebel-alliance/

**Comment by scobenes** [comment]
This is most likely an old bug when we had server issues
