### ISSUE TITLE
Many 500 errors in GAC history

### ISSUE THREAD

**Issue by jdblack1** [jedi-gg/swgoh.gg.public#696]
These URLs all return error 500 - 

Finn counters - https://swgoh.gg/gac/counters/FINN/
JML counters - https://swgoh.gg/gac/counters/GRANDMASTERLUKE/
DR counters, after clicking on BASTILASHANDARK as a defender - https://swgoh.gg/gac/counters/DARTHREVAN/?d_unit=
GG counters, after clicking the scissors to toggle off 99th percentile - https://swgoh.gg/gac/counters/GRIEVOUS/?cutoff=0

(Clicking on virtual any defender or attacker, or the scissors anywhere, also gives 500)

**Comment by scobenes** [comment]
This is most likely an old bug
