### ISSUE TITLE
Player Sync not working

### ISSUE THREAD

**Issue by RZ87** [jedi-gg/swgoh.gg.public#697]
I cant seem to sync my account and I get the internal message error everytime I do.

Username: RZ87
Ally code: 356-773-957

**Comment by BjoernLindner** [comment]
same problem here.
Supposedly player-id wrong, but also id-help currently offline and therefore no chance to set up an account correctly :(

**Comment by scobenes** [comment]
This is most likely an old bug when we had server issues.  If not please open a new ticket or come into discord and let us know
