### ISSUE TITLE
Account not syncing

### ISSUE THREAD

**Issue by RZ87** [jedi-gg/swgoh.gg.public#698]
I'm getting the 500 Server error message

Username: RZ87
Ally code: 356-773-957

**Comment by kyben03** [comment]
Same.

**Comment by scobenes** [comment]
This is most likely an old bug

**Comment by nickchamp1984** [comment]
@scobenes not really. As well I can't DM @sep on Discord.

The Player ID I've submitted is already attached to another account (I don't know/remember how it happened).

Hi @Sep, I need help with my SWGOH.GG account.

Player ID: Xq32e6PNQSKr_hPg-q8VnQ
Email: nick.pruchkovskiy@gmail.com

PS: https://swgoh.gg/p/537189761/ 

![photo_2023-09-12_16-19-13](https://github.com/jedi-gg/swgoh.gg.public/assets/47222866/dc9ae89e-32e2-4fff-ba91-873a61982c4e)
