### ISSUE TITLE
Cannot sync account. Player Id not recognised 

### ISSUE THREAD

**Issue by kyben03** [jedi-gg/swgoh.gg.public#699]
Can’t sync my account. 
keep getting wrong player id despite copying from profile. 
have then tried the link to find player id and that’s not working either.

**Comment by smittydj** [comment]
I have this problem too. I have typed everything correctly - also, player look up tool doesnt find me either....

**Comment by scobenes** [comment]
This is for anyone else who may find this. If you have issues do try the id help tool at https://swgoh.gg/id-help/ and if that doesn't work. Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need
