### ISSUE TITLE
Desync account from previous log in

### ISSUE THREAD

**Issue by OGDB1515** [jedi-gg/swgoh.gg.public#700]
I hope you can help remove the link between my swgoh account and the log in so I am able to sync my new log in. 
my player ID is: xKWFHrfPQe6w4l4USxFbyw

**Comment by DrkVc3** [comment]
Hi,
I have the same problem, can you suggest a solution?
Thank you

**Comment by danpaulson** [comment]
Reach out to me on Discord @ Sep#1111 and I can sort it.

**Comment by DrkVc3** [comment]
Discord tells me that you don't receive messages...
