### ISSUE TITLE
Someone set my info as public, please delete Profile

### ISSUE THREAD

**Issue by lizzardbyte** [jedi-gg/swgoh.gg.public#701]
Hi, I don't know how, but it seems that someone adds my profile to .gg, and it was not me.

How could I delete this profile: https://swgoh.gg/p/988615821/

Thanks in advance.

**Comment by danpaulson** [comment]
Profiles are public game data - we do not remove game profiles.

**Comment by lizzardbyte** [comment]
But can you set as private? Like before?
