### ISSUE TITLE
BB Echo not appearing in profiles/guild info

### ISSUE THREAD

**Issue by VReaperV** [jedi-gg/swgoh.gg.public#704]
Some players' profiles don't show the Bad Batch Echo even though they have him in-game. E. g: https://swgoh.gg/p/741324657/characters/?f=Bad+Batch. Similarly, unit search for that guild shows only 2 Echos: https://swgoh.gg/g/61/m-dw/unit-search/. Doesn't show up on my [profile](https://swgoh.gg/p/299128163/characters/?f=Bad+Batch) either, and unit search/templates for Echo on my guild show only 2 Echos.

**Comment by eDiveBuddy** [comment]
Not just echo. Hasn't counted new toons in a very long time.  Over 7 months behind.

**Comment by VReaperV** [comment]
> Not just echo. Hasn't counted new toons in a very long time. Over 7 months behind.

The rest of the Bad Batch were appearing fine in the templates etc. But now I'm seeing that stuff happening even with Aayla Secura.

**Comment by VReaperV** [comment]
Checked some stuuf and it looks like it uses some old data for some reason, e. g. my Piett in guild templates show up as 3* G8, while some time earlier he was correctly showing up as 7* G13.

**Comment by scobenes** [comment]
This is most likely an old bug
