### ISSUE TITLE
Missing unit avatar 

### ISSUE THREAD

**Issue by bfiliatreault** [jedi-gg/swgoh.gg.public#706]
In GAC history, missing unit avatar image.  See screenshot  attached. 

URL: https://swgoh.gg/p/916894954/gac-history/

### Also, if submitting a problem with user data, -PLEASE- include the URL of affecte
![Screenshots_2021-05-15-12-35-08](https://user-images.githubusercontent.com/1047518/118371502-ddfe4c00-b57a-11eb-966d-f0d09342c1a0.png)
d data.

**Comment by scobenes** [comment]
should be fixed we are having some server issues this weekend
