### ISSUE TITLE
/guild/ endpoint of the API returns a 503

### ISSUE THREAD

**Issue by DarthJJ** [jedi-gg/swgoh.gg.public#708]
I tried to fetch data for swgoh.gg/api/guild/5039 but I got an Error 503 Backend fetch failed

I also tried it with different guildIds, same result. 

/player/<allycode> seems to be working correctly.

**Comment by DarthJJ** [comment]
it seems it has been resolved for now. please feel free to close this issue

**Comment by danpaulson** [comment]
:+1: Yeah migrating to a new stack, sorry for the downtime.
