### ISSUE TITLE
API gives 403 due to CloudFlare

### ISSUE THREAD

**Issue by DarthJJ** [jedi-gg/swgoh.gg.public#709]
Hi,

Sorry to bother again,

But the API gives an 403 when access from either the command line or from code. Via the browser it works alright.

This started since yesterday. 

Is it possible you have configured cloudFlare in a more stricter mode? or activated the  I am under attack mode ?

**Comment by scobenes** [comment]
Not sure if this is still happening but have not heard of this being more widespread

**Comment by lc9900** [comment]
This is happening again when I tried to query swgoh.gg/api. Code and curl gets 403, while browser works.

**Comment by lc9900** [comment]
Here's a url I used https://swgoh.gg/api/abilities/
Get the following page as response, along with 403

```
Sorry, you have been blocked
You are unable to access swgoh.gg
Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

What can I do to resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.
```
