### ISSUE TITLE
Inaccurate info

### ISSUE THREAD

**Issue by Barney27** [jedi-gg/swgoh.gg.public#710]
Account not syncing properly. Characters levels not showing correctly, ranks are incorrect.

**Comment by superbeeny** [comment]
This has been happening to me too for a few days now. I can manually sync and characters show correctly. Then the following day it appears the data has reverted.

https://swgoh.gg/p/811683499/

**Comment by DarthJJ** [comment]
I can confirm that for me and some guild mates this is also the case. 
It appears that some days with changes are "missing"  meaning the changes of the last couple of days are in but data before that is missing..

**Comment by TinTin-R** [comment]
Supporting DarthJJ comment, way off for me: https://swgoh.gg/p/662689726/

**Comment by TinTin-R** [comment]
> Supporting DarthJJ comment, way off for me: https://swgoh.gg/p/662689726/
> Looks like the data is more than one week old at least

![image0](https://user-images.githubusercontent.com/47077714/119218030-58c8e900-bade-11eb-96a3-3e15e4d2a2df.png)


![Screenshot_2021-05-22_at_09 11 40](https://user-images.githubusercontent.com/47077714/119218034-5f576080-bade-11eb-8074-85dae74b1889.png)

**Comment by scobenes** [comment]
This is most likely an old bug and we have updated everyone;s characters multiple times since then
