### ISSUE TITLE
Images are not displaying when clicking the leader

### ISSUE THREAD

**Issue by ssheppard-73** [jedi-gg/swgoh.gg.public#711]
Click GAC Meta
Click Top Performing Counters
Click a leader
Images do not display - there is just a text overlay

![image](https://user-images.githubusercontent.com/54275986/119037993-a2032680-b980-11eb-8c08-31edbc659a3c.png)

**Comment by danpaulson** [comment]
Thanks - this is fixed now.

**Comment by ssheppard-73** [comment]
Thanks for the fast response!
