### ISSUE TITLE
Gear needed for GL not displaying for JML 

### ISSUE THREAD

**Issue by ricardostl** [jedi-gg/swgoh.gg.public#713]

**Comment by ricardostl** [comment]
Hello when signed in and on the “gear needed for galactic legend” it shows what gear I need for SEE, Rey and GLK (still need) but does not shoe gear needed for SLKR and JKL (which I have) but it is not showing gear needed for JML. https://swgoh.gg/p/854959875/gl-gear-needed/

**Comment by scobenes** [comment]
Not sure if this is still an issue, please let me know if it is.
