### ISSUE TITLE
Guild Unit search displays (0) for all units

### ISSUE THREAD

**Issue by ChuckNorrizSaber** [jedi-gg/swgoh.gg.public#714]
I am trying to do a unit search for the guild, and all of the units are showing (0) for the guild.  There was sync done very recently, so that isn't the issue.  This is the first time I have seen this happen, and I've used this feature many times in the past.  Any idea what the problem might be here?  Thanks everyone.

**Comment by scobenes** [comment]
This was most likely related to us doing server maintenance.  May happen again right now as we are doing it again, but should recover in next 24hrs
