### ISSUE TITLE
Grand Arena fleet battle not loading

### ISSUE THREAD

**Issue by manuelbrc** [jedi-gg/swgoh.gg.public#715]
Since the last update (this week) I can't do last fleet battle in Grand Arena. Everything works in other battles but when there's only the last fleet to get my oponent cleaned, It stays in loading forever. Already happened twice exactly the same, tried restarting but didn't work.

Update->Now I tried uninstall and reinstall and problem persists. I have Motorola One Vision

**Comment by scobenes** [comment]
We are not affiliated with CG/EA and cannot help ya with things that happen ingame.
