### ISSUE TITLE
I forgot my username and email to swgoh.gg account and I want to delete the player ID account

### ISSUE THREAD

**Issue by Vidswgoh** [jedi-gg/swgoh.gg.public#719]
I forgot my username and email to swgoh.gg account and I want to delete the player ID.

My swgoh.gg profile is https://swgoh.gg/p/651443182/
Ally code: 651-443-182
Ingame name: MINI vid

@danpaulson Could you assist in the matter? 🙂

**Comment by Vidswgoh** [comment]
Another person wants to connect the swgoh account to their swgoh.gg account and this is not possible as long as it is connected to my swgoh.gg account (which I forgot my username and email to...)

**Comment by danpaulson** [comment]
Send me a DM on Discord (Sep#1111) and I can help you sort this.
