### ISSUE TITLE
Player ID is already attached to an account!

### ISSUE THREAD

**Issue by BobyBushi** [jedi-gg/swgoh.gg.public#722]
I forgot my old email! I made a new one but I can't link with my account as it's still linked to the old account! https://swgoh.gg/p/828887514/ can you delete this one so I can link to the new account?

the new account is #454559

**Comment by prashantmoroliya** [comment]
I forgot my old credentials too and I don't remember which email id is associated with which account. https://swgoh.gg/p/429468482/ if possible can you please send me my username and email id on my email. Please.

**Comment by danpaulson** [comment]
You can send me a DM on Discord (Sep#1111) and I can help you recover the account.
