### ISSUE TITLE
Error logging in site. Resetting pw does not resolve

### ISSUE THREAD

**Issue by aerohead88** [jedi-gg/swgoh.gg.public#724]
Hello,

I cannot log into the site. Login page claims there is an error. I logged into the site many times before with no issue. I've reset my pw several times but with the same result. Could this be b/c I changed my name in game (Added MINI prefix to my in-game name)?

[https://swgoh.gg/p/455155111/](url)

https://swgoh.gg/p/455155111/

**Comment by PixEye** [comment]
Same problem here and I have a space in my nickname. It might be related. https://swgoh.gg/p/649159626/

**Comment by PixEye** [comment]
Workaround: I was used to enter my email address as the login but now it only works with the nickname without space.

**Comment by aerohead88** [comment]
Workaround doesn't work for me. I get the same error either way.

**Comment by danpaulson** [comment]
Thanks for the reports. I'm looking into this - hopefully have a solution in the next couple of days.

**Comment by darthxeno2526** [comment]
Same issues here

**Comment by monkold** [comment]
Same issue here, pw reset doesn't work

**Comment by danpaulson** [comment]
This should be fixed now - email or username now work for auth.

**Comment by aerohead88** [comment]
Confirmed working now. Thank you!! 

> This should be fixed now - email or username now work for auth.
