### ISSUE TITLE
Royal Guard appears on "what to zeta" list even when zeta is applied

### ISSUE THREAD

**Issue by TGTF** [jedi-gg/swgoh.gg.public#729]
My zeta on Royal Guard doesn't seem to be reflected on my zeta list:
https://swgoh.gg/p/755981582/zetas/

I 've had the zeta for over a month now

**Comment by scobenes** [comment]
This is most likely a caching issue.  If you swap a mod on RG and then resync it should update him.  Going to close this, but let me know if it doesn't fix it.

**Comment by TGTF** [comment]
Hi,

changed a mod. Re-synched the swgoh.gg profile (change in mod is showing,
6E arrow) but the zeta still doesn't.
[image: image.png]
also, in my profile page of RG, he's ship ability is showing as 1st
ability. The link redirects you to the proper page of the 1st ability of RG
though...
In any case, I don't really mind, just thought you should know.

Cheers
