### ISSUE TITLE
Guild page with 50 profiles almost empty

### ISSUE THREAD

**Issue by zatho-ger** [jedi-gg/swgoh.gg.public#732]
Our guild page appears almost empty:
https://swgoh.gg/g/77006/raiders-of-the-outer-rim/

it looked normal before and all players have their profile linked, as it is also said on the page

**Comment by KailonWrains0203** [comment]
Same thing happening with a lot of guilds in my alliance. Our guild has 49 people signed up and that normally show up. Only one profile there now.

**Comment by scobenes** [comment]
We have about 175k players synced.  We are trying to let the hourly syncs take it back over now and just turned em on earlier today.  There are going to be issues hooking everything back up (as we are finding).  The manual sync buttons for players and guilds should be working fine and can be done at any time currently.

You can go to your sync settings and click the "Update Profile" button to get your own account back online https://swgoh.gg/settings/sync/

Or we are more than happy to manually sync a guild if you need one done right now.

**Comment by scobenes** [comment]
Closing this issue as we have synced almost all of the people we know about.  if there are any profiles that are still problematic, we would want people to open a new ticket to let us know about it.  Thanks for bearing with us while we transitioned to the new hardware.
