### ISSUE TITLE
missing Stars filter in Unit Search within guild page

### ISSUE THREAD

**Issue by Salion920** [jedi-gg/swgoh.gg.public#733]
Good day,

Within the guild page's Unit Search page, there used to be a drop-down menu to toggle the minimum number of stars that would be considered in a character count within the guild.  This toggle has now disappeared.  Can we restore it?  Once toggled, it used to update the Unit drop down menu with the number of those toons the guild had at that star level, and when a character was selected, it would only display the toons which met the criteria.

I use the numbers from the Unit drop-down menu to assign platoons within my guild.  I have created an excel spreadsheet into which I copy those numbers to automatically compare the total amount of eligible characters we have versus how many are needed for that day's platoons.  It lets us strategize which platoons to skip and which meta characters we need to sacrifice to platoons.

However, now the only number that displays is the total number of those characters unlocked at ANY star level.  This means that I must visit the individual pages for each character in the game and manually count the number of characters that meet the star requirements.  What used to take 5 minutes to calculate will now take several hours each day.  Can we please have the old functionality restored?

Thank-you.

**Comment by scobenes** [comment]
I thought of way to compromise in functionality so there is now a "--" option in dropdown initially to show all users.  I think this should restore what ya had before and have the newer features of export and players without the units showing up for the case I wanted.
