### ISSUE TITLE
I can't access swgoh.gg because someone else is using my Player ID

### ISSUE THREAD

**Issue by chrismusic1993** [jedi-gg/swgoh.gg.public#735]
Hello, I just recently picked back up playing Star Wars Galaxy of Heroes, and apparently someone in my original guild gave out my login credentials to someone who has been managing my account without my permission for the past couple years. I immediately changed my passwords to gain control of my account again; however, when I attempt to sync my account to swgoh.gg again, it says my "Player ID is already attached to an account". The account it is referencing isn't one I own because I deleted my original swgoh.gg account when I retired from playing. My player ID is KwgDPB6YQ2WO8Nqm8D4rtQ and my Ally Code is 299-467-388. If it is possible, I would ask that this player ID be released, so that I can sync it with my new swgoh.gg account (Username: AVANTIS - User # 472397). I would really appreciate any help you could give!

**Comment by scobenes** [comment]
Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
