### ISSUE TITLE
guild unit search shows counts of 0 for all players

### ISSUE THREAD

**Issue by gorgatron1** [jedi-gg/swgoh.gg.public#736]
For example:

https://swgoh.gg/g/46657/brg-hope/unit-search/

<img width="276" alt="image" src="https://user-images.githubusercontent.com/53417942/149606004-c0134898-ec1c-4a54-a6e1-e20d39e353aa.png">

I see this across several guilds that I try.

**Comment by gorgatron1** [comment]
FWIW, I am logged in (Gorgatron) but it shows the same when I am not logged in.

**Comment by scobenes** [comment]
We updated some servers over the last few days and we are currently in the process of syncing everything.  I updated that guild manually and should be back to working.  All guilds should get back in order over the next 24 hrs

**Comment by gorgatron1** [comment]
Looks good, thank you!
