### ISSUE TITLE
GP problem

### ISSUE THREAD

**Issue by gritzkov** [jedi-gg/swgoh.gg.public#737]
Hey!
This guild ttl GP is wrong. 245+164mil is not 335mil.
https://swgoh.gg/g/840/rh-old-empirks/

![image](https://user-images.githubusercontent.com/97703157/150022233-246c50f2-bede-4245-9824-ca1ee1b8554a.png)

**Comment by scobenes** [comment]
That top galactic power is a summary of the profiles we have for the guild, and the bottom two are what CG reports in the guild info.  Basically those number can get out of sync sometimes. 

I updated the guild and its back to expected
