### ISSUE TITLE
Squad Template creating error

### ISSUE THREAD

**Issue by saiwaisai** [jedi-gg/swgoh.gg.public#739]
I cannot create Squad Templates for my guild:
![image](https://user-images.githubusercontent.com/11540468/150670527-8850ebce-33b6-43b0-a6dd-cd5a0aed4bb5.png)

I can see and open previously created templates, but cannot create new ones.
https://swgoh.gg/g/20690/solyomfeszek/a/squad-templates

**Comment by saneth** [comment]
Same here. I cannot edit existing squad templates anymore.

**Comment by scobenes** [comment]
Sorry about that, its fixed.  When I updated things to be better, it exposes some unintentional extra stuff we had on pages.
