### ISSUE TITLE
Zeta count on player profile is incorrect

### ISSUE THREAD

**Issue by Vaexqua** [jedi-gg/swgoh.gg.public#740]
For example, my profile page states 197 zetas in the summary area at the top, but the GAC bracket table (correctly) states 202. The actual zetas view also displays the correct number (easily checked by `document.querySelectorAll('.char-ability-img').length`).

https://swgoh.gg/p/681971255/

**Comment by scobenes** [comment]
Yea this is using an old way of counting zetas that got messed up with the new omicron changes.  Thanks for reporting

**Comment by scobenes** [comment]
Got this out with some other changes today.  Thanks again for letting us know
