### ISSUE TITLE
GAC bracket sorting by GP issue

### ISSUE THREAD

**Issue by kissackltd** [jedi-gg/swgoh.gg.public#743]
Hi,

In the GAC bracket page, if sorting by GP certain senarios are not sorted correctly. This looks to be due to alphabetical sorting resulting not compatible with whole numbers and decimals.
https://swgoh.gg/p/955833488/gac-bracket/

![image](https://user-images.githubusercontent.com/51233647/151252844-942bb4d2-e046-42db-afba-de229c71d978.png)

**Comment by scobenes** [comment]
Making updates to this UI, so probably won't fix it in this version, but appreciate the callout and should have an update for this soon.
